### ISSUE TITLE
flyctl secrets import prints secrets in output

### ISSUE THREAD

**Issue by hoyau** [superfly/flyctl#1014]
**Describe the bug**

`flyctl secrets import` prints the  imported secrets from the file in the output. I think these informations should be hidden per default, to have the possibility to use it in CI/CD without any workarounds.

example:
```
~ flyctl secrets import < .env

map[
  AppSecret1: SecretValue1
  AppSecret2: SecretValue2
]
Release vN created
```

expected behavior:
```
~ flyctl secrets import < .env

Release vN created
```

**Comment by ashalfarhan** [comment]
I would love to work on this, I think we can add a flag to determine if we should show the secrets after importing or not, but the default is `false` 🤔

**Comment by benwaffle** [comment]
I can no longer reproduce this. If someone can, happy to re-open this issue.
