### ISSUE TITLE
flyctl secrets set and import return error when there is nothing to update

### ISSUE THREAD

**Issue by justi7n** [superfly/flyctl#1015]
**Describe the bug**
`flyctl secrets import` and `flyctl secrets set` return an error when there is nothing to update (`Error No change detected to secrets`).
Perhaps it makes more sense to allow that scenario, and return exit code 0 instead of an error.

**Comment by remorses** [comment]
Now the error is `Oops, something went wrong!`

**Comment by numso** [comment]
I just ran into the same thing. If there is a reason these commands should exit with a status of 1 then maybe we could get a `--ignore-no-change-error` flag or something.

We set our secrets using Github Actions. Here's what we ended up doing for now to avoid those specific failures but still throw if something else goes wrong. Hope it can help someone:
```
jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          set +e
          out=`
            flyctl secrets set --app '${{ env.FLY_APP_NAME }}' \
              \
              SECRET_1='${{ secrets.SECRET_1 }}' \
              SECRET_2='${{ secrets.SECRET_2 }}' \
              \
            2>&1`
          status=$?
          if [[ $status == 0 ]]; then
            echo "Secrets successfully set!"
          elif [[ $out =~ "Error No change detected to secrets" ]]; then
            echo "No changes needed."
          else
            echo $out
            exit $status
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

**Comment by jsierles** [comment]
Unchanged secrets will now return a zero exit status.
