### ISSUE TITLE
Builders are reporting error on Platform API

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#102]
From the end of a build:

5bed26d33875: Pull complete
f11b29a9c730: Pull complete
930bda195c84: Pull complete
78bf9a5ad49e: Pull complete
5c9d3fab2775: Pull complete
3d9e25dd1e70: Pull complete
Digest: sha256:fb5ecb90a42b2067a859aab23fc1f5e9d9c2589d07ba285608879e7baa415aad
Status: Downloaded newer image for cloudfoundry/run:base-cnb
2020/04/01 15:57:27.169274 DEBUG:  pack 0.0.0 supports Platform API version(s): 0.1, 0.2
2020/04/01 15:57:27.169307 DEBUG:  Builder cloudfoundry/cnb:bionic has Platform API version: 0.3
Error Builder cloudfoundry/cnb:bionic is incompatible with this version of pack

Buildpacks bumped pack support to 0.3 at start of March, now the buildpacks themselves have moved to 0.3.

**Comment by michaeldwan** [comment]
Looks like we need to bump the library. I'll do that today.

**Comment by michaeldwan** [comment]
Fixed in the latest release
