### ISSUE TITLE
Error Post "https://api.fly.io/api/v1/cli_sessions": net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by solrevdev** [superfly/flyctl#103]
Cannot log in using `flyctl auth login`

This is what happened.

```bash
▲ (macmini.local) ~ curl https://get.fly.io/flyctl.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1041  100  1041    0     0   3234      0 --:--:-- --:--:-- --:--:--  3242
######################################################################## 100.0%
flyctl was installed successfully to /usr/local/bin/flyctl
Run 'flyctl --help' to get started
▲ (macmini.local) ~  flyctl auth login
Error Post "https://api.fly.io/api/v1/cli_sessions": net/http: TLS handshake timeout
```
This is my environment

```text
screenfetch -n
 solrevdev@macmini
 OS: 64bit Mac OS X 10.14.6 18G95
 Kernel: x86_64 Darwin 18.7.0
 Uptime: 44d 18h 24m
 Packages: 437
 Shell: zsh 5.8
 Resolution: 2560x1440
 DE: Aqua
 WM: Quartz Compositor
 WM Theme: Blue (Dark)
 Disk: 306G / 525G (59%)
 CPU: Intel Core i5-4278U @ 2.60GHz
 GPU: Intel Iris
 RAM: 8113MiB / 16384MiB
```

**Comment by mrkurt** [comment]
Is this still happening? If so, will you run `traceroute api.fly.io` and post the results?

**Comment by solrevdev** [comment]
▲ (macmini.local) ~ clear
▲ (macmini.local) ~ traceroute api.fly.io
traceroute: Warning: api.fly.io has multiple addresses; using 34.235.226.28
traceroute to hydrophobic-lark-9jejit2dqpovx254fei1kk1q.herokudns.com (34.235.226.28), 64 hops max, 52 byte packets
 1  192.168.104.254 (192.168.104.254)  0.753 ms  0.451 ms  0.306 ms
 2  80.252.75.209 (80.252.75.209)  0.677 ms  0.906 ms  0.898 ms
 3  51.219.214.81 (51.219.214.81)  0.988 ms  0.803 ms  0.746 ms
 4  195.162.118.140 (195.162.118.140)  3.669 ms  3.808 ms  3.667 ms
 5  * * *
 6  ae1-265.cr1-lon2.ip4.gtt.net (46.33.94.57)  4.356 ms  3.986 ms  3.869 ms
 7  et-10-1-0.cr4-nyc2.ip4.gtt.net (213.254.214.14)  72.587 ms  74.152 ms  75.210 ms
 8  a100-gw.ip4.gtt.net (173.205.58.70)  72.552 ms  72.597 ms  73.722 ms
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * *

**Comment by michaeldwan** [comment]
@solrevdev we made some routing changes to api.fly.dev over the past few days. Are you still seeing this issue?

**Comment by solrevdev** [comment]
@michaeldwan Yes I am still getting the same problem. 

▲ (macmini.local) ~ flyctl version
flyctl 0.0.114 4338663 2020-04-15 11:24:21.627856 +0100 BST m=+0.003131257

**Comment by mrkurt** [comment]
Yesterday's might've been due to an outage. Can you give it another try today?

**Comment by solrevdev** [comment]
@mrkurt  It's worked. I've logged in! Thanks so much

```bash
▲ (macmini.local) ~ flyctl version
flyctl 0.0.114 4338663 2020-04-16 15:38:04.451133 +0100 BST m=+0.034184732
▲ (macmini.local) ~ flyctl auth login
Opening browser to url https://fly.io/app/auth/cli/5f5f67f3c4e16a3606bd71b9c4b6dbdd
Waiting for session...Done
Successfully logged in as john@solrevdev.com
▲ (macmini.local) ~
```

**Comment by solrevdev** [comment]
I will close the issue now. Thanks all who helped and took a look at this for me.

**Comment by chrisma** [comment]
Hello, I'm currently getting a similar error again when trying to login. Is there a current outage?

`Error Post "https://api.fly.io/api/v1/cli_sessions": dial tcp: i/o timeout`

![image](https://user-images.githubusercontent.com/1652117/150685920-9b5d7485-3754-4e3e-baa6-cd4011aaf373.png)

`api.fly.io` responds to ping

![image](https://user-images.githubusercontent.com/1652117/150685986-d49f8803-27df-4095-9d37-747654041484.png)

**Comment by adelarsq** [comment]
@chrisma Any update on this? I'm having the same issue :|

**Comment by chrisma** [comment]
> @chrisma Did you solve? I'm having the same issue :|

It randomly worked at some point for me. I've just tried again and am getting the same error again. No idea what could have changed on my end.

**Comment by adelarsq** [comment]
@chrisma Thanks for the reply. Without any change it's working again after 2 days, so... 🤔

**Comment by echan00** [comment]
First time using fly.io and also having this problem...   

```
traceroute to api.fly.io (77.83.143.220), 64 hops max, 52 byte packets
 1  zyxel.home (192.168.1.1)  2231.507 ms  2.061 ms  2.583 ms
 2  * * *
 3  skc1-3331.hinet.net (168.95.32.122)  9.248 ms  8.473 ms  8.479 ms
 4  * * *
 5  tpdt-3032.hinet.net (220.128.25.38)  14.058 ms
    220-128-25-14.hinet-ip.hinet.net (220.128.25.14)  13.315 ms
    tpdt-3032.hinet.net (220.128.25.10)  13.277 ms
 6  pcpd-4101.hinet.net (220.128.12.37)  12.771 ms
    pcpd-4101.hinet.net (220.128.7.45)  13.330 ms
    tpdt-4114.hinet.net (220.128.4.173)  12.423 ms
 7  r4003-s2.tp.hinet.net (220.128.6.9)  80.321 ms
    pcpd-4001.hinet.net (220.128.6.157)  43.740 ms
    pcpd-4001.hinet.net (220.128.6.149)  51.268 ms
 8  63-218-56-101.static.pccwglobal.net (63.218.56.101)  37.506 ms  35.430 ms
    ae-20.r02.tokyjp05.jp.bb.gin.ntt.net (129.250.9.77)  45.462 ms
 9  hundredge0-4-0-3.br02.tok02.pccwbtn.net (63.218.250.229)  45.531 ms
    hundredge0-3-0-1.br03.hkg12.pccwbtn.net (63.218.174.201)  39.717 ms
    ae-3.r31.tokyjp05.jp.bb.gin.ntt.net (129.250.3.29)  45.109 ms
10  * ae-1.a00.tokyjp09.jp.bb.gin.ntt.net (129.250.7.38)  51.139 ms
    ae-0.a00.tokyjp09.jp.bb.gin.ntt.net (129.250.7.14)  49.259 ms
```

**Comment by echan00** [comment]
Found that the issue is because I am in Asia (Taiwan)... it works when I'm using a VPN

**Comment by iuriatan** [comment]
having the same issue here...

**Comment by iampopal** [comment]
having the same issue, any fixes?

**Comment by NullClock** [comment]
Same issue. I really need a fix.

**Comment by scottieb3** [comment]
For anyone else struggling with this, the issue for me was my local router's DNS resolver was specifically failing to resolve api.fly.io while resolving other domains fine. The macOS system resolver (used by curl, flyctl, and other applications) relies on this, while nslookup queries the DNS server directly — which is why nslookup succeeded but everything else failed.  Adding Fly.io's public API server IP to /etc/hosts resolved it.
