### ISSUE TITLE
Flyctl deploy fails on windows when Dockerfile not in working directory or is specified

### ISSUE THREAD

**Issue by Steveveepee** [superfly/flyctl#1038]
When deploying on windows, the build fails when Dockerfile is not in working directory, or specified in commandline.

* Operating system
* Windows 11
* `fly version` 0.0.341

```toml 
[build]
  dockerfile = '/docker/django/Dockerfile'
```
(relevant part)

** Command output: **

```text
Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3023907336/docker\django\Dockerfile: no such file or directory
```

Note the switching of / to \ in the file section of the command sent to the docker daemon.
Something happening [here:](https://github.com/superfly/flyctl/blob/44ea4881ae7d52c894d224aabb8a66a086ea66e9/cmd/deploy.go#L132)

**Comment by Steveveepee** [comment]
Looks like there is (for me) unexpected behavior with local paths when running `fly deploy`
eg: 
project root `E:\dev\project\`
dockerfile location `E:\dev\project\docker\django\`

current directory in CMD prompt. `E:\dev\project\docker\django`

Command:
`fly deploy ..\..\`
Expected outcome, (from `flyctl deploy [WORKING_DIRECTORY] [flags]`) is for the working directory to be ``E:\dev\project\` and the Dockerfile in the current CMD prompt folder to be found and applied.
Actual outcome, `E:\dev\project\Dockerfile not found`

**Comment by robertwt7** [comment]
Yess I have been looking into this issue for a while now as well!

I am trying to migrate my project from VPS to fly.

However doing this:
```
flyctl deploy ./ -c ./infrastructure/fly/fly.toml --dockerfile ./infrastructure/fly/Dockerfile
```

Gives me the exact same error

My project is [open source](https://github.com/robertwt7/meetsy/tree/master/api) and I always put everything under `infrastructure` folder

So if collaborators want to have a look it is also much easier..

**Comment by robertwt7** [comment]
I can confirm that this works on my mac, same command, but doesn't work on my PC

**Comment by ndarilek** [comment]
Wondering if this may be fixed as well? The path inserted in the configuration file appears to be absolute.

**Comment by Steveveepee** [comment]
Any movement on this @superfly

**Comment by ndarilek** [comment]
Still not able to reproduce. Please reopen with reproduction steps and I'll take a crack at fixing it. Thanks!
