### ISSUE TITLE
Add Docker registry login helper

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#104]
Since we run a registry, we should let people login and push directly to it. Right now folks can run `docker auth registry.fly.io` and put their fly token as the username, but that's a little opaque.

**Comment by mrkurt** [comment]
To push + deploy from our registry right now:

Get auth token:
```
flyctl auth token
```

Authenticate with our Docker repo, use token as username, `x` for password:
```
docker auth registry.fly.io
```

Build your Docker image, tag it for fly:

```
docker build . -t registry.fly.io/<app>:<tag>
```

Push to registry:
```
docker push registry.fly.io/<app>:<tag>
```

Deploy 
```
flyctl deploy -i registry.fly.io/<app>:<tag>
```

**Comment by DazWilkin** [comment]
For posterity and because I found this first when Googling...corrections:

+ Authenticate with Docker or Podman or ... use `x` for username and token as **password**
+ Should be `docker login registry`

Perhaps:

```
flyctl auth token | \
[docker|podman|...] login \
--username=x \
--password-stdin \
registry.fly.io
```

**Comment by nikvdp** [comment]
To anyone else arriving late to the party and encountering errors it appears with more recent versions of `flyctl` you now need to add the `--local-only` flag to the last command when deploying the image:

```
flyctl deploy --local-only -i registry.fly.io/<app>:<tag>
```
