### ISSUE TITLE
Homebrew version is outdated

### ISSUE THREAD

**Issue by ariofrio** [superfly/flyctl#1040]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

The latest version available [on Homebrew is 0.0.339](https://formulae.brew.sh/formula/flyctl#default), so the CLI adds the following message to every command response:

```
Update available 0.0.339 -> v0.0.341.
Run "fly version update" to upgrade.
```

However, running `fly version update` (which just calls `brew upgrade flyctl`) doesn't do anything:

```
Update available 0.0.339 -> v0.0.341.
Run "fly version update" to upgrade.
/bin/zsh -c
Running automatic update [brew upgrade flyctl]
Warning: flyctl 0.0.339 already installed
```

**Comment by jsierles** [comment]
Not sure what happened here, but now 0.344 is available.
