### ISSUE TITLE
Flaps client cannot be created externally

### ISSUE THREAD

**Issue by andresrsanchez** [superfly/flyctl#1052]
**Describe the bug**
Hi! Currently we are using the new `flaps` package to deploy machines, but the [New](https://github.com/superfly/flyctl/blob/master/pkg/flaps/flaps.go#L35) method tries to get the `api.Client` from the `Context` in [a internal method](https://github.com/superfly/flyctl/blob/master/internal/client/context.go#L14) like this:
```go
type contextKey struct{}

func FromContext(ctx context.Context) *Client {
	return ctx.Value(contextKey{}).(*Client)
}
```
So how we should create the [Client](https://github.com/superfly/flyctl/blob/master/pkg/flaps/flaps.go#L27) struct in the `flaps` package if the `contextKey` is internal? I think that @jsierles has context of this package.

Thanks!

**Comment by jsierles** [comment]
Hey! It's great to see people checking out this codebase. So, we're still in very early stages with this client. It's not really intended to be used outside of `flyctl` just yet. It uses our GraphQL API to establish a wireguard tunnel for connecting to the API end point, and that API is not intended to be used by customers, going forward. It also requires the `flyctl` agent to open that tunnel. So we don't want to export all of these internals, which may change or disappear at some point.

That said, we're working on formalizing some of this in flyctl now. What we could do is make it possible to use this client without flyctl internals. In other words, you'd be responsible for opening the tunnel, either with a permanent wireguard connection, or with something like `flyctl proxy`.

**Comment by andresrsanchez** [comment]
Oh okey no problem then i will wait until this client feels like ready to use, thanks!!!
