### ISSUE TITLE
Add buildpack/buildpacks to fly.toml

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#106]
The buildpack.io pack command allows builders and separate buildpacks to be specified on the command line. Replicate that in the fly.toml file to allow ad-hoc buildpacks to be used with various builders without having to create a builder manifest and package it.

**Comment by michaeldwan** [comment]
fly.toml supports builder and buildpacks right now (https://github.com/superfly/flyctl/blob/master/flyctl/app_config.go#L31)

Is that what you're looking for or something else?

**Comment by codepope** [comment]
Buildpacks is there, the singular buildpack isn't. If we could alias them, that would be great.

**Comment by codepope** [comment]
Fly.toml handles them, but the command line does not so this would not work...

docker apps create --builder cloudfoundry/cnb:cflinuxfs3 --buildpack flyio/deno-cnb

But it would be nice if it did.
