### ISSUE TITLE
flyctl api package invalid version

### ISSUE THREAD

**Issue by andresrsanchez** [superfly/flyctl#1068]
**Describe the bug**
Hi, we are using the api module from the flyctl package and when i tried to run `go get` the command returns: 
```
github.com/superfly/flyctl/api: github.com/superfly/flyctl/api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
So a `replace` in the `go.mod` is necessary, something like:

```
replace github.com/superfly/flyctl/api v0.0.0-00010101000000-000000000000 => github.com/superfly/flyctl/api v0.0.0-20220708073423-b6d7c3cf5161
```
I checked in the `flyctl` codebase and i found:
```
replace github.com/superfly/flyctl/api => ./api
```
Is this expected? Thanks!

**Comment by jsierles** [comment]
Can you try now to see if things improved?

**Comment by andresrsanchez** [comment]
awesome thanks @jsierles !!!
