### ISSUE TITLE
Allow using `--app` as a global option

### ISSUE THREAD

**Issue by remorses** [superfly/flyctl#1091]
In latest release `--app` cannot be used as a global flag

This prevents you from aliasing the fly command to be `fly -a appinthisfolder` which is very useful

For example i have the following scripts in my `package.json`

```json
"scripts": {
        "fly:dev": "flyctl -a notaku-website-preview",
        "fly:prod": "flyctl -a notaku-website-production",
}
```

**Comment by jsierles** [comment]
Can you be more specific about your use case? The commands you listed there would not do anything, as you're not calling any subcommand.

**Comment by remorses** [comment]
Instead of writing the full command I write `yarn fly:dev logs`

**Comment by jsierles** [comment]
`fly -a myapp logs` works for me. Some commands don't accept the `-a` flag. What are you trying to do?

**Comment by remorses** [comment]
Sorry, i run the command with the `--help` flag and gave the error but actually it works if you don't pass `--help` 😅
