### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by xtance** [superfly/flyctl#1099]
Excuse me, there are instructions on how to install on windows:
`iwr https://fly.io/install.ps1 -useb | iex`
But how to uninstall? (Couldn't find it in programs list on windows 10 ltsc)

**Comment by dangra** [comment]
All Fly related files are placed under your home at `$Home\.fly\bin` directory

**Comment by 96312** [comment]
@xtance @dangra Windows does have that file structure. You're thinking Mac.

**Comment by 96312** [comment]
@xtance @dangra Windows does not have that file structure. You're thinking Mac.

**Comment by dangra** [comment]
@96312 please see https://fly.io/install.ps1 

the section to read about is:
```ps
$FlyInstall = $env:FLYCTL_INSTALL
$BinDir = if ($FlyInstall) {
  "$FlyInstall\bin"
} else {
  "$Home\.fly\bin"
}
```

`FLYCTL_INSTALL` environment variable is usually unset on normal install, so the final installation path is `$Home\.fly\bin` on Windows.

"installation" here truly means copying files into that path. So removing the files is all you need to uninstall Fly CLI.

**Comment by Naresh9639** [comment]
run <b>echo %path%</b> in windows command prompt.
path is similar to C:\Users\yourUserName\.fly\bin

**Comment by XeanN** [comment]
Yo también estoy en la búsqueda de poder desinstalar

**Comment by skdishansachin** [comment]
I am using ubuntu, How can I uninstall/remove ?

**Comment by abhinandval** [comment]
> I am using ubuntu, How can I uninstall/remove ?

`rm -fr ~/.fly`

also remove the values you have added to `.bashrc` file

**Comment by Mullerian9** [comment]
How do I uninstall flyctl from my computer using PS.? I need to install a new version
