### ISSUE TITLE
v0.0.354: failed to fetch an image or build from source: Authentication required to access image

### ISSUE THREAD

**Issue by andig** [superfly/flyctl#1100]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
See https://community.fly.io/t/failed-to-fetch-an-image-or-build-from-source-authentication-required-to-access-image/6132/2.

As of .354, deployment from private repo has been broken. 353 still works.

* Operating system
* `fly version`
    fly v0.0.359 darwin/arm64 Commit: 15b0f802 BuildDate: 2022-07-23T12:26:56Z

** Paste your `fly.toml`

```toml
app = "evcc"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "andig/private-repo"
```

** Command output: **

```text
flyctl deploy
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'andig/evcc-cloud' remotely...
Error failed to fetch an image or build from source: Authentication required to access image "docker.io/andig/private-repo:latest"
```

**Comment by andig** [comment]
Confirmed https://github.com/superfly/flyctl/pull/1080 is the root cause. I can workaround using `CI=1`. Not sure if this is the intended behaviour as it breaks private repo access per default?

**Comment by dangra** [comment]
Hi andig. I haven't read the forum yet. But my recommendation would be to use `--local-only ` instead of CI=1 if the docker image can't be built on a remote builder.

**Comment by andig** [comment]
It would be nice if breaking changes could be clearly documented and communicated- this one has caught me cold. 

I think it‘s more a usability issue at this point. Since I‘m using the image option, the build is already done. Why should the deploy step involve any remote builders? Could I have expected that?

Please don‘t get me wrong- if you feel this is user error feel free to close.

**Comment by jsierles** [comment]
Let's continue on the forum so others will get wind of the discussion. Thanks!
