### ISSUE TITLE
deploy error: operation not permitted

### ISSUE THREAD

**Issue by agrinman** [superfly/flyctl#111]
Hi there,
I'm getting this error when I run `flyctl deploy`:

```
Creating build context... ⣽ Error chown /var/folders/02/40sf_b99089bx7r18h603f2r0000gn/T/263091513/<file_copied_in_docker_file: operation not permitted
```

Getting around this by running deploy with sudo, but it probably shouldn't need it. Is this expected or is something misconfigured on my end?

Thanks!
Alex

**Comment by michaeldwan** [comment]
@agrinman looks like flyctl is failing to create an archive of your working directory to send to docker. What OS are you on? Are you using a dockerfile? Are there any symlinks in the working directory?

**Comment by agrinman** [comment]
- macOS
- using a dockerfile 
- no symlinks

These are the relevant lines from the Dockerfile:
```
FROM alpine:latest

COPY ./target/x86_64-unknown-linux-musl/release/wormhole_server /wormhole_server
```

You can find the full project here: https://github.com/agrinman/wormhole

**Comment by gregmsanderson** [comment]
Getting same error, same OS. Latest version of flyctl, just downloaded.

A local docker build works.
A deploy using the "--remote-only" flag works.
But a deploy without that --remote-only fails, with the same error mentioned above: chown operation not permitted.
