### ISSUE TITLE
fly machine launch fails before region selection

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1152]
(flyctl 0.0.369 and 0.0.370)

When I run

`fly m launch`, an app gets created, but in region selection it errors:

```
[...]
Created app cool-tree-7451 in org personal
DEBUG --> POST https://api.fly.io/graphql

{
  "query": "query { platform { requestRegion regions { name code gatewayAvailable } } }",
  "variables": null
}

DEBUG {}
DEBUG <-- 200 https://api.fly.io/graphql (57.43ms)

{
  "data": {
    "platform": {
      "requestRegion": "lga",
      "regions": [
        {
          "name": "Amsterdam, Netherlands",
          "code": "ams",
          "gatewayAvailable": true
        },
[...]
        {
          "name": "Toronto, Canada",
          "code": "yyz",
          "gatewayAvailable": true
        }
      ]
    }
  }
}
Oops, something went wrong! Could you try that again?
```

**Comment by jsierles** [comment]
Should be fixed in #1149

**Comment by catflydotio** [comment]
I'm getting the same behaviour today with flyctl 0.0.372

**Comment by jsierles** [comment]
Doh, will revisit

**Comment by dangra** [comment]
This looks like a temporal error, I couldn't reproduce locally. @catflydotio do you mind trying again?

**Comment by catflydotio** [comment]
Sorry @dangra I missed this. Same behaviour with v0.0.388 darwin/arm64

**Comment by DAlperin** [comment]
@dangra @jsierles also facing this with v0.0.388 linux/x_86. When building from master, it fails at the same spot but with `panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by dangra** [comment]
@DAlperin do you have a way to reproduce it? that could help if you can share it here or privately.

**Comment by catflydotio** [comment]
Not @DAlperin, but I can always elicit "Oops, something went wrong! Could you try that again?" by calling `fly m launch` without the region flag.

It gets as far as successfully getting the platform regions from the API, but seems to fall down when it calls `prompt.SelectRegion(ctx, "", regions, requestRegion.Code)`.  I wonder if the problem's inside there. Since this isn't the function `fly launch` uses to show a regions prompt, I don't think it's used anywhere else (yet?).

**Comment by DAlperin** [comment]
Here is a screencast showing me building flyctl from master in docker, running it from docker, and it breaking.

[Screencast from 09-15-2022 02:19:20 PM.webm](https://user-images.githubusercontent.com/16063713/190480595-8c7979ba-880c-460c-b379-4aa36ba2b15e.webm)

**Comment by catflydotio** [comment]
Fixed by getting rid of `fly m launch` :)
