### ISSUE TITLE
Where Should I get Help

### ISSUE THREAD

**Issue by GerryG** [superfly/flyctl#116]
Going through the quick start and it goes great as  a user experience. I don't have my app yet running local on 8080 (I still have to re-check latest images for config and functionality) I work on http://decko.org/ and am the one most likely to do system engineering. Once upon a type it was building images at DockerHub and running Docker automation at Semaphore. Except ... bit rot.

It bombed at selecting an organization, is that an official identity at DockerHub or ? The help wasn't too obvious.

Thanks,
Gerry

**Comment by codepope** [comment]
Dropping a mail to support@fly.io will get you straight to support.

The organizations are groups for sharing apps on Fly. I've added a note to the hands-on (https://fly.io/docs/hands-on/configuring-fly/) re organizations to make that explicit and that you should select your own account name (which is your personal organization - the selection should have only your personal organization if this is your first time through unless you were invited). 

Dj

**Comment by GerryG** [comment]
Thanks, I'll do it again. I think that is what I saw, but it failed when I thought I had selected it.

I'd bet something else broke.
Thx
