### ISSUE TITLE
Migrate to new launch command with backported nomad support

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#1175]
`fly machines launch` should take over `fly launch`. Currently it works for machines apps only. Backporting it to support nomad fly.toml generation would allow us to finally deprecate old deployment and postgres code. And, we could use the new postgres and redis launchers from within it.

**Comment by redjonzaci** [comment]
Do we still want to do this?

**Comment by jsierles** [comment]
Old and crusty
