### ISSUE TITLE
Add 'fly scale vm' support to machines apps

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#1180]
Discussion: https://flyio.discourse.team/t/paas-changing-vm-sizes/730

**Comment by redjonzaci** [comment]
Can non-Fly.io employees help with this?
Because I wasn't able to access that discussion.

**Comment by jsierles** [comment]
Already done

**Comment by jsierles** [comment]
Nope it's good to clean this up! Also a nice reminder of what actually has been accomplished.
