### ISSUE TITLE
Support [processes] in fly.toml

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#1181]
Discussion: https://flyio.discourse.team/t/paas-changing-vm-sizes/730

TLDR, we should use the existing `[processes]` structure but allow augmenting as needed. We'll need to invent scale/region settings.

**Comment by redjonzaci** [comment]
Same question as https://github.com/superfly/flyctl/issues/1180#issuecomment-1705353063.

**Comment by jsierles** [comment]
Done
