### ISSUE TITLE
v0.0.373 fails pushing image with generic error and no useful info

### ISSUE THREAD

**Issue by brcarey** [superfly/flyctl#1183]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

Doing a flyctl deploy, upon successfully completing the build it then fails to push the image with an error message `Oops, something went wrong! Could you try that again?` (trying again did not fix it). 

**Rolling back to 0.0.372 fixed the issue**

* Operating system macos, ubuntu-latest
* `fly version 0.0.373`

** Paste your `fly.toml`

```toml
sensitive, nothing of note
```

** Command output: **

```text
deployment-1660693181: digest: sha256:33e427a7fdf80d46d0bd26d99dcc401cf0d1b05dd59efa4a4b9a51a9c1efbb97 size: 3684
--> Pushing image done
image: registry.fly.io/expertli-muncher-test:deployment-1660693181
image size: 2.1 GB
Oops, something went wrong! Could you try that again?
```

**Comment by jsierles** [comment]
Can you post your `fly.toml` contents?

**Comment by brcarey** [comment]
sure:
```
# fly.toml file generated for muncher on 2022-02-14T10:36:28+11:00

app = "expertli-muncher-test"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[env]
 <<redacted>>

[[mounts]]
  destination = "/data"
  source = "expertli_muncher_test_data"

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 500
    soft_limit = 400
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

**Comment by jsierles** [comment]
Can you try with the latest release v0.0.374?

**Comment by brcarey** [comment]
got the following from my local env:
```
ERRO[0601] Can't add file /Users/brcarey/work/blank/apps/expertli/public/webviewer/core/pdf/lean/PDFNetCWasm.br.wasm to tar: io: read/write on closed pipe 
ERRO[0601] Can't close tar writer: io: read/write on closed pipe 
DEBUG result image:<nil> error:error building: unexpected EOF
Error failed to fetch an image or build from source: error building: unexpected EOF
```
trying from github action now

**Comment by jsierles** [comment]
This looks like a different issue. Are the files you're uploading to Docker very large?

**Comment by brcarey** [comment]
yeh must have been my local env (home internet a bit flaky). Re-run from github action with `superfly/flyctl-actions@1.3` and it went green - assume it picks up the latest `flyctl` version on its own?

Thanks for the quick turnaround

**Comment by jsierles** [comment]
Yup, the latest is picked up. Thanks for the report!
