### ISSUE TITLE
"Cannot locate specified Dockerfile: Dockerfile" when changing Dockerfile name

### ISSUE THREAD

**Issue by amaurymartiny** [superfly/flyctl#119]
I have two apps on Fly, represeting two environments: `myapp-staging` and `myapp-production`; they each have their own `fly.{staging,production}.toml`.

I also have two Dockerfiles, mostly similar but with some minor differences. The two Dockerfiles live in the same folder in the same repo: `<root>/Dockerfile` and `<root>/Dockerfile.production`.

For the staging environment, I run:
```
flyctl deploy --config fly.staging.toml
```

and it works.

Now I want to rename `Dockerfile` to `Dockerfile.staging` for consistent naming. So I do:

```bash
mv Dockerfile Dockerfile.staging
flyctl deploy --config fly.staging.toml --dockerfile Dockerfile.staging
```

But I get an error

```
==> Validating app configuration
--> done
   Services
      TCP 80/443 ⇢ 8080
Deploy source directory '/github/workspace'
Docker daemon available, performing local build...
Building Dockerfile
Using Dockerfile: ./Dockerfile.staging
Error Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
Creating build context... ⣾
```

Here's a repro on my CI: https://github.com/reacherhq/backend/pull/35/checks?check_run_id=639459103

**Comment by michaeldwan** [comment]
@amaurymartiny Thanks for the detailed issue! I found the issue and just released a fix in v0.0.118
