### ISSUE TITLE
Allocate public IPv4/v6 to new apps if a service is added

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#1196]
New machines apps don't get public IPs allocated. Until flyd (or something else) takes care of this, we can do it from flyctl as soon as a service is assigned.

It's worth noting that a machine can be launched with `fly machine run` with a service that doesn't get written to `fly.toml`.  Also, `fly machines launch` [does take care of allocating IPs](https://github.com/superfly/flyctl/blob/master/internal/command/machine/launch.go#L472).

**Comment by catflydotio** [comment]
This was done.
