### ISSUE TITLE
Fly launch should return app details

### ISSUE THREAD

**Issue by shortdiv** [superfly/flyctl#1215]
Current view:
<img width="727" alt="Screen Shot 2022-08-26 at 12 08 43 PM" src="https://user-images.githubusercontent.com/3229484/186956870-ec4feab4-9314-4655-b67c-5cce4671db36.png">

We'd probably want app information like app name, url and how to start interacting with the created app in the output

**Comment by tvdfly** [comment]
Fixed with https://github.com/superfly/flyctl/pull/1224
