### ISSUE TITLE
Flyctl x86 exe release not working

### ISSUE THREAD

**Issue by planyway** [superfly/flyctl#1218]
I received “Error loading config While parsing config: yaml: control characters are not allowed
flyctl is a command line interface to the Fly.io platform.” when I run any flyctl command, the way I setup is by unzipping the x86 release zip file, which includes flyctl.exe and wintun.dll. The problem did not occur at the beginning of using flyctl.exe, until a crash of my computer when deploying my site.
My operating system is Windows 64, my flyctl folder is extracted from is 0.0.381_Windows_x86_64.zip

fly.toml is exactly the auto generated one, no edits yet.
No any other setup made for my hello world version app.

**Comment by catflydotio** [comment]
Duplicate of #908.
