### ISSUE TITLE
Allow fly ssh console to have multiple or chained commands.

### ISSUE THREAD

**Issue by bufordtaylor** [superfly/flyctl#1220]
Every time I enter the ssh console, I have to cd into a directly and then open a rails console. It would be amazing if this was one line.

Works fine with one command
```
fly ssh console -C "ls"
Connecting to top1.nearest.of.app-name.internal... complete
app  boot  etc   lib    media  opt   root  sbin  sys  usr
bin  dev   home  lib64  mnt    proc  run   srv   tmp  var
```

But with two:

```
fly ssh console -C "ls && cd app"
Connecting to top1.nearest.of.app-name.internal... complete
ls: cannot access '&&': No such file or directory
ls: cannot access 'cd': No such file or directory
app:
Dockerfile    other_files
```

**Comment by bram-dingelstad** [comment]
I've been struggling with a similar problem for running more than one command. A workaround that might be useful to others finding this issue is the following:

```bash
echo "
# NOTE: example command, chance with your own
cd /app
/usr/bin/sqlite3 -noheader -list /app/database.db 'select * from users';
" | fly ssh console -C "/bin/sh"
```

You can also use other shells like shelling into `/usr/bin/sqlite3` directly or `/bin/bash` / `/usr/bin/python3`, etc

**Comment by thejager** [comment]
For people that always want to go into a certain directory when they `fly ssh console`: I added the following line to my Dockerfile:

`echo 'cd /var/www/html' >> /root/.bashrc`

Make sure to login using `-C /bin/bash` to log into bash.

**Comment by ndarilek** [comment]
The issue here is that commands run over `fly ssh console` aren't executed in the context of a full shell, and there doesn't appear to be an easy way to do this.
      
      This wouldn't fix your exact problem, but I wonder if adding a `--workdir` option might help? That would at least be in line with what similar tools like `docker exec` provide.

**Comment by ndarilek** [comment]
#1597 attempts to address at least this use case by adding a `--workdir` option to `fly ssh console`. Unfortunately due to limitations either in SSH or Go's SSH client, I can't set an initial working directory in which to start the shell. But it should at least help with the case of starting app scripts from a given directory.

Need to test more rigorously, which is why it's currently draft. In particular I've only checked the behavior with shells and not with one-off commands.

**Comment by benwaffle** [comment]
You can run multiple commands by running a shell: 
```
fly ssh console -C 'bash -c "ls && cd app"'
```

**Comment by redjonzaci** [comment]
@benwaffle would it be safe to close this?
