### ISSUE TITLE
fly ssh console timeout

### ISSUE THREAD

**Issue by bufordtaylor** [superfly/flyctl#1221]
I had a `shared-cpu-1x 256mb` machine and when I `fly ssh console`, it worked fine.

With no changes to the code, I updated to a `shared-cpu-1x 512mb` machine and `fly deploy -a app-name`. Now it times out.

```
fly ssh console
Connecting to top1.nearest.of.app-name.internal... complete
Error error connecting to SSH server: connect tcp: operation timed out
```

The app itself works fine and I can navigate to it on my browser.

**Comment by bufordtaylor** [comment]
Update: This works fine now. No changes. I guess I just had to wait 5 minutes after the deploy for ssh to work. I'll leave this here for the admins.

**Comment by thejager** [comment]
There seems to be a problem with the internal list of running VMs. `fly ssh console` connects to the first one in the list, but that list might contain the VM that was just replaced. This causes a timeout.

If you run again into this issue, try `fly ssh console -s`. This most likely will show 2 VMs, one of them being a dead VM. If the first one doesn't work, the second one probably will.

**Comment by tvdfly** [comment]
Our internal DNS, which `fly ssh console` uses to find instances, sometimes takes a little bit to sync up. We've made a lot of improvements to internal dns syncing since August. Are you still seeing this issue?
