### ISSUE TITLE
Update available on flyctl while it cannot be installed (yet?) on brew

### ISSUE THREAD

**Issue by jlengrand** [superfly/flyctl#1241]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

Just installed flyctl using `$ brew install flyctlz`

Couple minutes later, as I run a command, I get a message telling me the CLI is outdated. No worries

```
$ flyctl open
Update available 0.0.384 -> v0.0.385.
```

Except updating isn't actually registering the latest version of the CLI just yet so I can't actually update, using the flyctl command or brew directly. 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/921666/187789567-20655e0d-8543-4079-913b-1907fff87637.png">

Not a big bug, but a slight possible improvement on the DX side.

* Operating system
* `fly version`

`$ fly ctl`

Update available 0.0.384 -> v0.0.385.
Run "flyctl version update" to upgrade.
flyctl v0.0.384 darwin/arm64 Commit: 142e8bc5 BuildDate: 2022-08-31T13:05:20Z

**Comment by redjonzaci** [comment]
Hey @jlengrand! I see @jordanbertasso has merged a PR for this issue (thanks!).
Do you still have this issue?

**Comment by jlengrand** [comment]
Don't think so! I'll reopen the ticket if I see it again. Thanks for checking!
