### ISSUE TITLE
Stop / start apps

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#129]
People keep asking for this, it would be a useful thing for both troubleshooting and "suspending" apps that aren't in use anymore.

We'd just need to communicate that IPs are still in use and certs are still being renewed if an app is disabled.

**Comment by davidhodge** [comment]
FWIW I had started a service that wasn't able to boot due to another problem. It's now in a loop trying to start endlessly

**Comment by codepope** [comment]
Implemented in backend and now supported in flyctl as apps pause and resume
