### ISSUE TITLE
Incorrect flyctl scale show output for multi-process apps

### ISSUE THREAD

**Issue by ignoramous** [superfly/flyctl#1294]
Output by `flyctl` for multi-process apps is misleading.

The command output below should show vm-size and vm-memory per-group ([source](https://community.fly.io/t/6974/3)).

```text
❯ fly scale show
VM Resources for visualizer
        VM Size: shared-cpu-1x
      VM Memory: 256 MB
          Count: web=1 worker=1
 Max Per Region: web=0 worker=0

❯ flyctl scale memory 512 --group web
Scaled VM Memory size to 512 MB
      CPU Cores: 1
         Memory: 512 MB

❯ fly scale show
VM Resources for visualizer
        VM Size: shared-cpu-1x
      VM Memory: 256 MB
          Count: web=1 worker=1
 Max Per Region: web=0 worker=0
```

Sometimes, `flyctl` shows process-group that doesn't exist anymore ([like for this user](https://community.fly.io/t/7296/6) who had removed `webpacker` from their `fly.toml` and subsequently deployed the app):

```
❯ fly scale show
VM Resources for lem
        VM Size: shared-cpu-1x
      VM Memory: 256 MB
          Count: app=1 worker=1 
 Max Per Region: app=0 webpacker=0 worker=0 
```

**Comment by redjonzaci** [comment]
Hey @ignoramous! Do you happen to know if this issue still persists?

**Comment by ignoramous** [comment]
Apps v1 has been deprecated for better part of this year, so I haven't used it since. May be this bug report can be closed?

**Comment by redjonzaci** [comment]
@jsierles what do you think? (didn't know who to tag here)
