### ISSUE TITLE
Allow app name and org args for `apps create`

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#13]
The dynamic shell stuff is great, except I have like 100 orgs and usually know the name I want ahead of time. :D

**Comment by mrkurt** [comment]
Oh so `--name` and `--org` already work, I think I keep trying:

```
flyctl apps create {name}
```

And:

```
flyctl apps create -a {name}
```

**Comment by mrkurt** [comment]
FYI, more than one person has asked for `flyctl apps create {name}`. Probably worth doing.

**Comment by michaeldwan** [comment]
Fixed in #29
