### ISSUE TITLE
build error in hermetic environments: missing dependency on github.com/Khan/genqlient

### ISSUE THREAD

**Issue by tv42** [superfly/flyctl#1323]
I'm trying to build flyctl in Nix's hermetic build environment. It's basically the same as `go mod vendor`.

The code only imports `github.com/Khan/genqlient/graphql`, while `go generate` tries to `go run github.com/Khan/genqlient`.

If you run `go mod vendor`, it does not vendor the genqlient tool itself:

```
$ tree vendor/github.com/Khan/genqlient
vendor/github.com/Khan/genqlient
├── graphql
│   ├── client.go
│   └── util.go
└── LICENSE
```

So `go generate` fails:

```console
$ go generate main.go
package github.com/Khan/genqlient: no Go files in /blah/flyctl/vendor/github.com/Khan/genqlient
main.go:3: running "go": exit status 1
```

You can fix this by adding the usual `tools.go`:

```go
//go:build tools
// +build tools

package tools

import (
	_ "github.com/Khan/genqlient"
)
```

For more information, see https://github.com/golang/go/issues/29516#issuecomment-454159127

**Comment by jsierles** [comment]
Could you submit a PR for this?

**Comment by tv42** [comment]
Actually, it turns out there's no need to run `go generate` at build time, the repo contains the generated files like are normal. I have no idea why the code in nixpkgs (https://github.com/NixOS/nixpkgs/blob/41f7e338216fd7f5e57817c4f8e148d42fb88b24/pkgs/development/web/flyctl/default.nix#L28-L30) does this.

But `tools.go` files are still a good idea, to lock versions of tools. (In your case, I *think* you got that for free by importing a subpackage of the same module -- but working by accident isn't a great idea.)

Created https://github.com/superfly/flyctl/pull/1325
