### ISSUE TITLE
Question: using flyctl with CI

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#133]
Quick question:

I see that when using CI, where there is no option to login, there is a:
--access-token XXXXX
... flag. However ... that means the access token is then part of the build, as it is a string in the CI config file, which has to be added to git.

So: can the flyctl command read in that access token from an environment variable to authenticate itself? That seems to be the common approach with these kind of tools like serverless and wrangler, to have the token in an environment variable which can then be kept out of the code and stored elsewhere within the CI system (in this case CircleCI)?

Or how else do people use flyctl with CircleCI etc, not manually deploying? Thanks.

**Comment by michaeldwan** [comment]
It's not well documented in the cli but you can use `FLY_ACCESS_TOKEN` for that. Same with `FLY_APP` if you're generating the app name dynamically.

**Comment by gregmsanderson** [comment]
Ah, perfect!

Does that access token I found in the credentials file expire? Or do I just copy that one and forget about it?

**Comment by michaeldwan** [comment]
@gregmsanderson they have a very long expiration time and flyctl will automatically refresh if needed

**Comment by gregmsanderson** [comment]
Ok, thanks. I wondered if they were like 30 minutes or something, defeating this approach, but that's fine then :)
