### ISSUE TITLE
no listening 8080

### ISSUE THREAD

**Issue by a224327780** [superfly/flyctl#1331]
- fly.toml
```
# fly.toml file generated for api0001 on 2022-10-03T15:05:07Z

app = "xxxxx"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
```

- app.py
```
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=os.getenv('PORT', 8080))
```

- Dockerfile
```
CMD ["python", "app.py"]

- logs
```
2022-10-03T15:55:57.870 app[bc801bb7] sjc [info] Preparing to run: `python app.py` as root
2022-10-03T15:55:57.902 app[bc801bb7] sjc [info] 2022/10/03 23:55:57 listening on [fdaa:0:5ef:a7b:b389:bc80:1bb7:2]:22 (DNS: [fdaa::3]:53)
```
```

**Comment by jsierles** [comment]
The 'listening' you see in logs is the SSH server running on your VM.This repository is for posting issues about flyctl-specific behavior. Can you post this on the [community forum](https://community.fly.io/)? Thanks!
