### ISSUE TITLE
Ability to restart monitoring required (and option to go to monitoring automatically)

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#134]
flyctl deploy, secrets set and other commands start background processes which can be monitored and in the case of deploy are. But once detached it isn't possible to reattach to the monitoring process. Suggest flyctl monitor which recreates a monitoring state and where commands can monitor, offer the ability to do and detach or do and monitor.

**Comment by mrkurt** [comment]
#56 is a start!

**Comment by codepope** [comment]
Merged and working for most deployment events.
