### ISSUE TITLE
Question: using flyctl with node

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#135]
Hello,

I have now got a test app working based on the example, using the basic "node app.js" command in the Dockerfile to run it.

Is there any need for a supervisor/pm2/forever manager to restart node on an error? Or does your system handle that side, the restarting etc?

Thanks.

**Comment by codepope** [comment]
No, because the node process is running as process 1, so when it does die/error/cease to be, the fly platform restarts the entire VM.

**Comment by gregmsanderson** [comment]
Ah, ok, great :)
