### ISSUE TITLE
flyctl proxy fails on v0.0.410

### ISSUE THREAD

**Issue by oldsj** [superfly/flyctl#1367]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:
`flyctl proxy` is failing. It was last working on `v0.0.404`

* Operating system
macOS Monterey 12.6

*  fly version

```flyctl v0.0.410 darwin/arm64 Commit: 3c67527a BuildDate: 2022-10-11T17:53:03Z```

** Paste your `fly.toml`

n/a

** Command output: **

```text
flyctl proxy 5432 -a my-db
Oops, something went wrong! Could you try that again?
```

This is a 2 instance postgres setup. Interestingly using `--select` allows us to connect to a single instance.

**Comment by lubien** [comment]
Thanks for reaching out. We are aware of this:

https://community.fly.io/t/flyctl-proxy-fails/7818/4
