### ISSUE TITLE
fly machine run should show machines unavailable if app is on nomad

### ISSUE THREAD

**Issue by shortdiv** [superfly/flyctl#1379]
<img width="792" alt="Screen Shot 2022-10-13 at 3 26 39 PM" src="https://user-images.githubusercontent.com/3229484/195530135-a7a87494-11bf-46db-9826-2b01e79cc9cc.png">
<img width="590" alt="Screen Shot 2022-10-13 at 3 29 17 PM" src="https://user-images.githubusercontent.com/3229484/195530698-40fe4fb8-ca12-4721-8a4d-b775cc87003c.png">
<img width="1508" alt="nomad" src="https://user-images.githubusercontent.com/3229484/195530593-339bdb66-24f2-40c8-8f54-0732b63d1411.png">

**Comment by redjonzaci** [comment]
@shortdiv I see you merged a PR for this issue. Can we close this?
