### ISSUE TITLE
[request] Support for scoop (or Chocolatey) / Installation problems on Windows

### ISSUE THREAD

**Issue by fu-sen** [superfly/flyctl#139]
I'm using flyctl on Windows. flyctl supports Homebrew, so scoop will work as well:
https://scoop.sh/
Or maybe think of Chocolatey:
https://chocolatey.org/

The reason I'm putting this in is that in the Install flyctl Windows has the following command:
https://fly.io/docs/getting-started/installing-flyctl/ :
```
curl -LO https://getfly.fly.dev/windows-x86-64/flyctl.exe
```
But this cannot be done in PowerShell. (It's the main means of Windows 10)
This will fail because `curl` in PowerShell is an alias for `Invoke-WebRequest`.
Use Git Bash or use `curl.exe` as a workaround,

**Comment by codepope** [comment]
We have been redoing the Windows installation experience. If you wish to try the early preview, before roll-out, try

```
iwr https://fly.io/install.ps1 | iex
```

This will install the latest flyctl into $HOME/.fly/bin (and add that directory to your path).

For package managers, we are looking to the full release of winget and looking to support that.

**Comment by fu-sen** [comment]
I understand that, but as a general issue the close timing is incorrect. Please resolve and close!
