### ISSUE TITLE
error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by adahox** [superfly/flyctl#140]
Hello Guys.

I'm trying to Deploy my project and since the last update, I'm getting `error: No such file or directory (os error 2)`

I review my project and there's server.ts file. 
actually my project can be found on https://github.com/adahox/k-otize-api

**OS INFO:**
Nome do sistema operacional:               Microsoft Windows 10 Home Single Language
Versão do sistema operacional:             10.0.18363 N/A compilação 18363

**Flyctl version:** 
flyctl 0.0.127 88f01b2 2020-06-02 12:54:02.8683478 -0300 -03 m=+0.005996701
**Deno Version:** 
deno 1.0.2
v8 8.4.300
typescript 3.9.2

**Comment by codepope** [comment]
The buildpack pulls the most recent build of Deno. It appeared as a regression in Deno 1.0.3 and is still present in some form in Deno 1.0.4. As you are running 1.0.2 locally you won't see it. We are waiting on Deno 1.0.5 to see if the issue resolves, and if not, we will likely pin the buildpack to Deno 1.0.2. We are also considering a deno-fly config file to pull all the configuration into one trackable file and this may be an opportunity to let users pin the buildpack deno version.

**Comment by codepope** [comment]
And we've just updated the buildpacks for Deno. There's now a .config file which can take the following parameters:

```
permissions="..."
unstable=true
deno_version=v1.0.2
```

With those entries in the .config file, it will use Deno 1.0.2 to build and run. The permissions property replaces the .permissions file and the unstable=true setting replaces the .unstable file. 

If you build now without a .config file present, you will get an error which explains that your need .config.

Any entry can be omitted to get the defaults - no permissions, no unstable, latest deno version

Hopefully, setting deno_version=v1.0.2 - (**the v is important**) - will get you building again.

**Comment by adahox** [comment]
> And we've just updated the buildpacks for Deno. There's now a .config file which can take the following parameters:
> 
> ```
> permissions="..."
> unstable=true
> deno_version=v1.0.2
> ```
> 
> With those entries in the .config file, it will use Deno 1.0.2 to build and run. The permissions property replaces the .permissions file and the unstable=true setting replaces the .unstable file.
> 
> If you build now without a .config file present, you will get an error which explains that your need .config.
> 
> Any entry can be omitted to get the defaults - no permissions, no unstable, latest deno version
> 
> Hopefully, setting deno_version=v1.0.2 - (**the v is important**) - will get you building again.

when will be available this update?

**Comment by codepope** [comment]
Should be live right now.

**Comment by codepope** [comment]
Can you post a copy of your .config file? I'll have a look at whats going on there.

**Comment by adahox** [comment]
> @adahox Can you post a copy of your .config file? I'll have a look at whats going on there.

I don't know if it is a OS issues but basically whats happening is
if I use .config file like :
`permissions="--allow-net --allow-env" unstable=false deno_version=v1.0.2`

The deploy runs ok. without warning or error message. otherwise, if I use .config like (using new like foreach variable:

```
permissions="--allow-net --allow-env"
unstable=false 
deno_version=v1.0.2
```
In this case, the build runs smoothly.

I guess it should be because, on the windows, .config file is setup as plain text. 

[here ](https://github.com/adahox/k-otize-api/blob/master/.config)you can find my actual (working) file.

**Comment by codepope** [comment]
Fixed original issue. Now documented.
