### ISSUE TITLE
Unable to install flyctl on Windows

### ISSUE THREAD

**Issue by blazmrak** [superfly/flyctl#1412]
**Describe the bug**
The command in the docs `iwr https://fly.io/install.ps1 -useb | iex` doesn't work for me. I have no idea what goes wrong and why, because I never use powershell, but even `iwr https://fly.io/install.ps1` fails. However I got it working by passing -Uri option -> `iwr -Uri https://fly.io/install.ps1 -useb | iex`. Maybe `iwr` api changed?

* Windows 11
* `v0.0.420`

**Command output:**

```text
iwr : The underlying connection was closed: An unexpected error occurred on a receive.
At line:1 char:1
+ iwr https://fly.io/install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo            : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by rahul3v** [comment]
First open your powershell as Administrator then try run the installation script

**Comment by blazmrak** [comment]
I swear I did at the time and it was still broken, but I was also having issues with the CLI graphQL endpoint randomly failing... Also running `iwr https://fly.io/install.ps1` without privileges now succeeds, so I doubt it had anything to do with privileges. I guess the -Uri didn't have much to do with it, I might have just gotten lucky :D Anyway, I am closing this issue as it seems to be working now.
