### ISSUE TITLE
unable to pull docker image

### ISSUE THREAD

**Issue by davidhodge** [superfly/flyctl#142]
Tried pulling a docker image and was unable to do so. Also tried some obvious seeming tags and was also unsuccessful. Kurt suggested I file an issue, so here I am. Thank you

% docker image pull registry.fly.io/nikola-proxy
Using default tag: latest
Error response from daemon: Get https://registry.fly.io/v2/nikola-proxy/manifests/latest: no basic auth credentials

**Comment by michaeldwan** [comment]
@davidhodge a release went out yesterday that might fix this. After updating, run `flyctl auth docker` to save credentials to the docker cli and try again.

**Comment by davidhodge** [comment]
Thank you!

**Comment by davidhodge** [comment]
Got the following. Am I doing something wrong here? Thank you.

% docker image pull registry.fly.io/nikola-proxy
Using default tag: latest
Error response from daemon: manifest for registry.fly.io/nikola-proxy:latest not found: manifest unknown: manifest unknown

**Comment by michaeldwan** [comment]
That looks like there wasn’t a `latest` label in your repo. Our deploys use an immutable `deployment-{timestamp}` label to ensure a tag doesn’t change after being deployed.

**Comment by pinkiebell** [comment]
I have no problems to pull or push, but on deployment:
```
+ flyctl deploy -i registry.fly.io/APP_NAME:APP_TAG
Deploying APP_NAME
==> Validating App Configuration
--> Validating App Configuration done
Services
TCP 443 ⇢ 8080 

Deploying image: registry.fly.io/APP_NAME:APP_TAG

Error Unable to access image registry.fly.io/APP_NAME:APP_TAG: 401 Unauthorized
```

flyctl version: `0.0.137`
