### ISSUE TITLE
Can't use quotes in build secrets

### ISSUE THREAD

**Issue by mca10** [superfly/flyctl#1437]
`fly deploy` command fails when including a build secret containing quotation marks. No amount of escaping seems to get around the issue.

* Operating system: macOS Monterey Version 12.6
* `fly version`: `fly v0.0.420 darwin/amd64 Commit: 977028ba BuildDate: 2022-10-25T14:30:02Z`

The issue happens with or without an existing `fly.toml` file

Command:
`fly deploy --build-secret my_secret='"'`

Output:
```text
Error: invalid argument "my_secret=\"" for "--build-secret" flag: parse error on line 1, column 11: bare " in non-quoted-field
Usage:
  flyctl deploy [WORKING_DIRECTORY] [flags]

Flags:
  -a, --app string             Application name
      --auto-confirm           Will automatically confirm changes without an interactive prompt.
      --build-arg strings      Set of build time variables in the form of NAME=VALUE pairs. Can be specified multiple times.
      --build-only             Build but do not deploy
      --build-secret strings   Set of build secrets of NAME=VALUE pairs. Can be specified multiple times. See https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information
      --build-target string    Set the target build stage to build if the Dockerfile has more than one stage
  -c, --config string          Path to application configuration file
      --detach                 Return immediately instead of monitoring deployment progress
      --dockerfile string      Path to a Dockerfile. Defaults to the Dockerfile in the working directory.
  -e, --env strings            Set of environment variables in the form of NAME=VALUE pairs. Can be specified multiple times.
  -h, --help                   help for deploy
  -i, --image string           The image tag or ID to deploy
      --image-label string     Image label to use when tagging and pushing to the fly registry. Defaults to "deployment-{timestamp}".
      --local-only             Only perform builds locally using the local docker daemon
      --nixpacks               Deploy using nixpacks to generate the image
      --no-cache               Do not use the build cache when building the image
      --now                    Deploy now without confirmation
      --push                   Push image to registry after build is complete
  -r, --region string          The region to operate on
      --remote-only            Perform builds on a remote builder instance instead of using the local docker daemon
      --strategy string        The strategy for replacing running instances. Options are canary, rolling, bluegreen, or immediate. Default is canary, or rolling when max-per-region is set.

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
      --verbose               verbose output

Error invalid argument "my_secret=\"" for "--build-secret" flag: parse error on line 1, column 11: bare " in non-quoted-field
```

**Comment by mca10** [comment]
After a lot of digging I tracked down the issue all the way to: https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/string_slice.go#L22-L29, adding a `csvReader.LazyQuotes = true` between lines 27 and 28 fixes the issue, and from the looks of it, it affects any flags that allow for the `--flag value1=something,value2=somethingelse` format. I intended to open a PR but the module seems quite abandoned -- over a year since its last update with 61 unresolved PRs...

Alternatively, this lazyquotes fix can get ignored altogether with a little bit of a hack, per [the golang encoding/csv module documentation](https://pkg.go.dev/encoding/csv), the comma-separated values need to be considered a single-value, and it needs to be enclosed in double-quotes, then, double-quotes can be represented by double double-quotes, i.e. `fly deploy --build-secret "\"my_secret=\"\"\""` will achieve a `my_secret="` build secret.

My interest in this was being able to send a json value as a secret. This needs an additional but very straightforward escaping of the commas, in the current version, dumping the contents of a json file into a build-secret can be achieved like this:

```
flyctl deploy --build-secret "\"my_secret=$(cat secrets_path/secret_file.json | sed "s:\":\"\":g" | sed "s:,:\,:g")\""
```

At this point, I'm not sure if I should just close this bug with this workaround, or open a PR in that pflag fork and hope it gets merged, then wait for it to be pulled into the "cobra" module so we can then update the dependency in here, or if an update in the flyctl documentation should be made to reflect this quirk with double-quotes.

**Comment by giuscri** [comment]
@mca10 An alternative would be to _quote_ the flag as required in flyctl itself.

**Comment by redjonzaci** [comment]
Hey @mca10, I see @benrogmans merged a PR related to this issue.
Do you need additional help with this?

**Comment by mca10** [comment]
@redjonzaci That PR indeed fixes the issue, thanks!
