### ISSUE TITLE
Question: custom healthcheck path?

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#145]
Hello

I assume the current healthcheck restarts the app/instance if it fails?

In which case is it possible to have a custom healthcheck path, like an ELB-style one?

Only what I'm thinking is that if the docker used multiple services, like connecting to an external database, a custom _/my/health/check_ path could be used to check not only nodejs etc was running, but could check the app was able to connect to an external database etc too. And if it failed, your system could automatically give it a kick and restart it or start a new instance.

**Comment by gregmsanderson** [comment]
Ah ... answered my own question digging through the docs.

It _is_ supported. Is it new? I don't recall seeing that option before :)

As it says that http_checks does not appear in the default toml so that explains why I'd only seen the tcp_checks: https://fly.io/docs/configuration/#services-http_checks

So, what happens if that healthcheck fails? Does it restart the docker instance?

**Comment by mrkurt** [comment]
Yep!

We have seen peoples' deploys break with this kind of health check, though. It makes things a little more brittle and tends to be pretty bad with Postgres in particular (since it has small connection limits). I'd definitely test and make sure it works like you want in normal times!

**Comment by gregmsanderson** [comment]
Nice!

Well what I was thinking was that one way to get connected to a database without knowing the IPs of the fly.io instances (to whitelist) would be to use a SQL proxy. Solves the problem. But reading some of the issues with Google's proxy, it appears it may lose the connection. Like: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/379

So since that issue appears unresolved, my thinking was perhaps monitor that with a healthcheck, and if it fails, have the docker restarted, and presumably that would in turn restart the proxy, and regain the connection. Maybe that could be the answer. But like you say, it could add other problems.
