### ISSUE TITLE
timeout panic on building for too long

### ISSUE THREAD

**Issue by gocs** [superfly/flyctl#1454]
https://github.com/superfly/flyctl/blob/ec22d8354484fe0fb5a3bc4529405333eaefb8c1/internal/build/imgsrc/resolver.go#L490

![image](https://user-images.githubusercontent.com/27877342/201466047-9c096d09-53e5-4e23-a134-615dd45b77bb.png)

the build finally panics after 2hrs of waiting to finish. i don't know where i miss build and everything i've done so far is building using the app based on the docs given which is the basic one

**Comment by tmpfs** [comment]
I have the same issue here, unable to deploy using `flyctl deploy`. This is my first time trying `fly.io` so not a great first impression.

```
panic: close of closed channel

goroutine 118 [running]:
github.com/superfly/flyctl/internal/build/imgsrc.(*Resolver).StartHeartbeat.func2()
        github.com/superfly/flyctl/internal/build/imgsrc/resolver.go:490 +0x26c
created by github.com/superfly/flyctl/internal/build/imgsrc.(*Resolver).StartHeartbeat
        github.com/superfly/flyctl/internal/build/imgsrc/resolver.go:484 +0x578
```

**Comment by gocs** [comment]
I figured out that deployment is possible using the `--local-only` flag, as long as you have docker locally installed

```
fly deploy --local-only
```
