### ISSUE TITLE
running deploy with LOG_LEVEL=debug creates empty build.log file

### ISSUE THREAD

**Issue by alxndrsn** [superfly/flyctl#1502]
Running `LOG_LEVEL=debug flyctl deploy` creates empty `build.log` file.

I'm not a go dev, but it looks like `build.log` is created at https://github.com/superfly/flyctl/blob/1acf701f06e3608b7ff52d604fa8a8b22c9105d3/internal/build/imgsrc/dockerfile_builder.go#L404-L415, and never made available outside that code block.

**Comment by ndarilek** [comment]
Hello.

Did your PR resolve this? If not, I'm happy to look into it next week.

**Comment by alxndrsn** [comment]
Looks like https://github.com/superfly/flyctl/pull/1503 fixed it :slightly_smiling_face:
