### ISSUE TITLE
Using "django" in lowercase causes you not to find the app when it sets to "Django" 

### ISSUE THREAD

**Issue by victoraugusto6** [superfly/flyctl#1524]
Hello, i noticed that when we use `pip-tools`, is inserted "django" instead of "Django" in `requirements.txt`.

With this, in this line makes the project not identified as a django project.

https://github.com/superfly/flyctl/blob/7a9ec7bea9011e24a7e1be53566988044745c144/scanner/django.go#L9

Please consider using "django" also in this condition.

**Comment by victoraugusto6** [comment]
@walison

Fixed this problem: https://github.com/superfly/flyctl/pull/1525

**Comment by michaeldwan** [comment]
Fixed in #1525
