### ISSUE TITLE
Create Postgres output connection string missing

### ISSUE THREAD

**Issue by craigpastro** [superfly/flyctl#1536]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

Hello 👋  I just ran `fly postgres create` and at the end the output included:

```
...
  Connection string: <connStr>

...

Connect to postgres
Any app within the ... organization can connect to this Postgres using the following connection string:
```

But at the end of that last sentence, there was no connection string. I suppose https://github.com/superfly/flyctl/blob/4d09d94de834115e72ec4f02c46618956a33a939/flypg/launcher.go#L183
needs to be reworded, or the `connStr` added to the output. I'm happy to make a PR if you would like.

* Operating system: macOS Montery
* `fly version`: fly v0.0.441 darwin/amd64 Commit: 7a9ec7be BuildDate: 2022-12-16T17:47:35Z

Thank you!

**Comment by catflydotio** [comment]
Fixed in https://github.com/superfly/flyctl/pull/1505 I believe.
