### ISSUE TITLE
Apps v2: fly status

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#1564]
Apps v2: We're pushing to migrate the Fly Apps platform to machines instead of nomad to improve developer experience. The first big step will be making new apps use the machines platform instead of nomad. There's a bunch of small steps to get there, and this is one of them...

`fly status` indicates which machines are part of the app vs. ones that were started and should be managed separately.

It should also show the process group each machine is assigned.

If https://github.com/superfly/flyctl/pull/1551 is still in progress, update that PR with these changes.

**Comment by mrkurt** [comment]
I just put these notes internally, but I want to include them here too. `fly status` exists to help people troubleshoot apps that they use `fly deploy` to update. For apps v2, here's what makes the most sense

* `fly status` shows _only_ machines that `fly deploy` updates
* If there are others, put a message telling people to run `fly machines list` for machines that aren't updated as part of `fly deploy`
* Find a way to show a deploy version on each. `fly deploy` should show you when machines don't match

Right now, we tell people to use `fly status` and `fly status --all` to see issues with their app. Normally they're looking for machines that have crashed or recently failed health checks. The most valuable thing `fly status` can do is show a user which machine caused an error.

The current `fly status` shows a restart count next to machines. We should continue to show this.
