### ISSUE TITLE
experimental.enable_consul ignored for Machines

### ISSUE THREAD

**Issue by ignoramous** [superfly/flyctl#1593]
> I created a small project to test it on Fly, but it looks like $FLY_CONSUL_URL is not set on machines ([`enable_consul`](https://fly.io/docs/litefs/example/#set-up-your-fly-io-config) is ignored?). Does it only work on apps?

> I was able to manually obtain a Consul URL by using the GraphQL API (see enablePostgresConsul, it returns a consulUrl).

From: https://community.fly.io/t/10146/3

cc: @tvdfly

**Comment by tjheeta** [comment]
Considering v2 is being used more and more, is there any ETA on this?

**Comment by matttpt** [comment]
`flyctl` v0.0.537 [introduced](https://community.fly.io/t/new-commands-fly-consul-attach-and-fly-consul-detach/12418) `fly consul attach` and `fly consul detach`, which replace this field for Apps v2.
