### ISSUE TITLE
Intuitively handle `fly launch` failures

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#1601]
When fly launch fails or is re-run, the fact that a new app is created each time is sometimes surprising to the developer. They can end up with multiple apps unintentionally.

There are also situations where they are quickly iterating on a fly.toml to get launch to work, and it would be nice if fly launch did not change the formatting each time it is run. This is a little trickier, but might be feasible in some cases.

If launch fails, we could ask them if they want to delete the app. Or we could do something more magical and just transparently retry with the same app name.

Another place this comes up regularly is with pg. When we create pg and launch fails, we’ll often see the app get deleted and the pg app stays. We can update fly launch to automatically clear those or prompt the developer asking if we should delete those.

**Comment by gwuah** [comment]
This has been addressed in 2 PRs. Closing for now.
https://github.com/superfly/flyctl/pull/1908 and https://github.com/superfly/flyctl/pull/1738
