### ISSUE TITLE
Apps v2: fly machines list update

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#1603]
Apps v2: We're pushing to migrate the Fly Apps platform to machines instead of nomad to improve developer experience. The first big step will be making new apps use the machines platform instead of nomad. There's a bunch of small steps to get there, and this is one of them...

`fly machines list` indicates which machines are part of the app platform, as well as well what process group they are assigned. These could be two new colums like `Apps Platform` with a true/false or check/no check, and `Process Group`.

If https://github.com/superfly/flyctl/pull/1551 is still in progress, update that PR with these changes.

**Comment by billyb2** [comment]
Gonna close this just, done in acedfab7ce74aa25679064a0d5e115035de9faca and 00bfe3ca27b3aa8ce91983cbe80f7ae3c55fbcd9
