### ISSUE TITLE
Show the region(s) which are unhealthy

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#161]
I tried a deployment to an app with four regions, distributed around the world, which failed with the following ...

```
...
4 desired, 4 placed, 3 healthy, 0 unhealthy [health checks: 3 total, 3 passing]
4 desired, 4 placed, 3 healthy, 1 unhealthy [health checks: 3 total, 3 passing]
v25 failed - Failed due to unhealthy allocations - rolling back to job version 24
```

So I _assume_ given that 3 worked that the app is not the issue, but a particular region is. If the app was the issue I'd assume it would be 0/4. The message does not indicate which region was the issue..

Feature request: say which failed. That way the regions could be updated manually to remove the current unhealthy ones.

And/or

Show the status of individual regions as a heads-up not to deploy to them, perhaps on a status page, if that is not already done?

**Comment by mrkurt** [comment]
@gregmsanderson when a deployment fails, you _should_ see status + logs for the exact instance that died. That region is probably not unhealthy, it's more likely the allocation crashed for some reason. The deploy process _should_ continue when that happens but we haven't made it less brittle just yet.

**Comment by gregmsanderson** [comment]
@mrkurt Ok, no problem.
