### ISSUE TITLE
Error failed to fetch an image or build from source: Could not find image "docker.io/***/my-api:latest"

### ISSUE THREAD

**Issue by mubarak-bunza** [superfly/flyctl#1611]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:
My CI/CD pipeline (using Github Actions) has been working for sometime until last week when it started failing saying could not fetch an image or build from source. The image is being build in the pipeline using docker buildx action and pushed to private dockerhub registry, Also, i can pull the image on my laptop, but not sure why it keeps failing in the pipeline.

* Operating system Ubuntu 22.04.1 LTS
* `fly version` 0.0.450

** Paste your `fly.toml`

```toml
# paste your config file here
app = "my-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "docker.io/mubarakbunza/my-api:latest"
```

** Command output: **

```text
# paste command output here
flyctl deploy --image docker.io/***/my-api:latest
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'docker.io/***/my-api:latest' locally...
Searching for image 'docker.io/***/my-api:latest' remotely...
Error failed to fetch an image or build from source: Could not find image "docker.io/***/my-api:latest"
```

**Comment by MrSucik** [comment]
I also started facing this issue. Last successful deploy happened on 2023-01-19T15:44:40+00:00 and since then my deploy action is unable to find/fetch docker image from registry.fly.io/xxx:xxx

Output:
`Searching for image 'registry.fly.io/xxx' remotely...
Error failed to fetch an image or build from source: Could not find image "registry.fly.io/xxx"
 `

**Comment by catflydotio** [comment]
This appears to be due to a silent change in GitHub actions; have a look here for more info and a possible workaround:

https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171

Closing as not a flyctl bug.
