### ISSUE TITLE
flyctl secrets being truncated when referenced from node server process.env

### ISSUE THREAD

**Issue by Paul-Browne** [superfly/flyctl#1614]
When referencing a secret that I set like so...

```bash
# no longer in use :)
flyctl secrets set APIKEY=$2b$10$JJRJC6866SgNkHR/PznVT.D5anjjbsWv6inTqEWjlBlF4If1H81ii
```
I got the following output when logging from my node server...

```js
console.log(process.env.APIKEY); //->    b/PznVT.D5anjjbsWv6inTqEWjlBlF4If1H81ii
```

For some reason it was truncating the string...
Is there some work-around? or something I'm doing wrong when setting/retrieving these secrets?

**Comment by Paul-Browne** [comment]
I "fixed" this by escaping the '$' characters, so to set the above secret I would do...

```bash
flyctl secrets set APIKEY=\$2b\$10\$JJRJC6866SgNkHR/PznVT.D5anjjbsWv6inTqEWjlBlF4If1H81ii
```

**Comment by ndarilek** [comment]
Yeah, this seems like your shell getting in the way. Glad you were able to get it fixed.

Closing for now. Please re-open this if it turns out something is messing up secrets server-side.
