### ISSUE TITLE
Apps v2: prerelease enforcing types in `fly.toml` where current release does not

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1619]
flyctl v0.0.451-pre-4 is enforcing types that the current release v0.0.450 doesn't. 

This includes at least `services.concurrency` which apparently used to accept this in `fly.toml`:

```
[[services]]
  concurrency = "100,150"
```
and port numbers as strings--which the current release allows, and which is in our docs!

`incompatible types: TOML value has type string; destination has type integer`

Looking back, it seems newly generated configs have had port numbers as integers for ages.

What I plan to do about this: 

* change the strings to ints in the docs!
* change fly.toml in whatever demo apps we use in docs, where needed. I may miss some, and certainly won't go through the fly-apps repo fixing them all. 

The error message is nice and clear, so if people run into this, they'll see how to fix it. However, I guess it'll break CI for someone out there.

Incidentally, I discovered both of these while running non-launch commands (`fly status -a` and `fly m run -a`) against different apps while I happened to be sitting in a directory that had a `fly.toml` in it. It was surprising to me that `flyctl` was validating a `fly.toml` in either case.

**Comment by jsierles** [comment]
This, for example, happens on our own `web` app currently.

**Comment by tvdfly** [comment]
related/dupe maybe: https://github.com/superfly/flyctl/issues/1673

**Comment by billyb2** [comment]
code fixed in #1729, with a part of this being addressed in #1739. The issue of docs being updated hasn't been addressed yet, though (as far as I'm aware)

**Comment by gwuah** [comment]
marking as closed since both pr's have been merged.
