### ISSUE TITLE
Ensure errors validating app config return a non-zero status

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#162]
A GitHub Action hit an error validating the app config but the step succeeded, which seems like a zero status was returned. Make sure we're exiting correctly on errors for the deploy command

https://github.com/replicatedhq/kots-lint/runs/800594299?check_suite_focus=true#step:4:11

**Comment by codepope** [comment]
This affects all errors that are handed up the chain. They end up in main.go where there's a defer function which attempts to recover (for some reason, unclear). Anyway, this function tries to recover, print out a recovered error and then... does nothing. So execution can continue. Have drafted in an os.Exit(1) to ensure an errored exit, but code needs review - see the JSONSnagging PR.

**Comment by codepope** [comment]
Fix to os.exit post recovery.
