### ISSUE TITLE
Apps v2 - (pre-4) `fly launch --internal-port` doesn't affect `internal_port`?

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1624]
I'm still on prerelease 4.

The story is: I accidentally `fly launched` a nginx image onto my running Flask app with

```
20:48:45 *[main][~/FlyTests/Jan25/hello-gunicorn-flask]$ fly launch --image nginx --internal-port 80
```
That part's covered in #1623.

But the `--internal-port` flag doesn't seem to have done anything at all

Repeated logs:
```
2023-01-26T01:50:50Z proxy[e286065f969386] iad [info]waiting for machine to listen on 0.0.0.0:4999 (waited 36.385103387s so far)
```

`fly.toml` had `internal_port = 4999` in it at this point and the app was previously deployed using that, but I used the `--internal-port` flag, so that should override it.

Checking what port I get if I save the config:

```
20:54:36 *[main][~/FlyTests/Jan25/hello-gunicorn-flask]$ fly config save
***An existing configuration file has been found.
? Overwrite file '/Users/chris/FlyTests/Jan25/hello-gunicorn-flask/fly.toml' Yes
Wrote config file fly.toml
```

In the new `fly.toml`, `internal_port` has reverted to the default 8080.

```toml
[[services]]
  http_checks = []
  internal_port = 8080
```

**Comment by gwuah** [comment]
I'm unable to reproduce this, scanning through the [code](https://github.com/superfly/flyctl/blob/0f706051ece0688fff86205b8b2a7a1f731aa963/internal/command/launch/launch.go#L318), this seems to be fixed.
