### ISSUE TITLE
Confusing error when configuring machine memory

### ISSUE THREAD

**Issue by Plecra** [superfly/flyctl#1636]
**Describe the bug**
Briefly, describe what broke and provide the following details:

`flyctl machines update <id> --memory 4096`

Afraid I didn't capture the details when I had this environment, but I can give it a go if you can't reproduce. I had started a Code Server instance, and tried to reconfigure it to use more memory using this command. It errored saying that "max config.guest.memory_mb: 2048", and I needed to add `--cpus 2` to enable the higher memory capacity.

Seems to me like it should explain the real conflict, and suggest using a higher CPU tier 🙂

* Operating system
flyctl.exe v0.0.450 windows/amd64 Commit: 51325e4a BuildDate: 2023-01-13T21:57:29Z

**Comment by billyb2** [comment]
Hi @Plecra , thank you for the report! I think I fixed this in #1762 , by adding some better error messages. Could you confirm the error has been fixed for you! To test, try running:
`flyctl machines update 3d8d371c226228 --cpus 1 --memory 4096` 

This should generate a similar error to the one you encountered.

**Comment by Plecra** [comment]
I don't have an environment to test it in right now, but those changes look like they'll do the trick nicely! It's targeted the misconfiguration I was talking about here :)
