### ISSUE TITLE
Apps v2 - `fly launch` doesn't deploy first Machine in selected region

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1640]
For instance, I can select any region, and my app's first VM is always in `iad`.

**Comment by billyb2** [comment]
When i create a machine with fly launch, the VM is always in whichever region I put.

**Comment by tvdfly** [comment]
I suspect we need to wire through the selected primary region from launch to the deploy code. deploy knows how to use primary region, but only knows how to find it in app config right now. we can probably have launch set that on the appv2.Config().
