### ISSUE TITLE
Apps V2: Remix launcher requires the 'exec' option in the experimental section

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#1644]
Since Flaps supports `exec` [directly](https://github.com/superfly/flyctl/blob/master/api/types.go#L257-L258), we could move it out of the experimental section without a lot of work.

**Comment by catflydotio** [comment]
I see cmd and entrypoint in there but not sure about exec?

https://github.com/superfly/flyctl/blob/master/scanner/remix.go#L21

**Comment by dangra** [comment]
@jsierles is this issue valid? I don't see a `exec` for Remix stack either. Kurt mentioned about an important demo that uses exec but I couldn't find it while looking for it at https://flyio.discourse.team/t/apps-v2-and-experimental-config-features/2000/6?u=daniel

**Comment by jsierles** [comment]
Not sure now where I got this, but it looks like remix is using [DockerCommand](https://github.com/superfly/flyctl/blob/4cc5e9abd3e32f6a97941fcce24d6568f31399bb/scanner/remix.go#L20). So we can close.
