### ISSUE TITLE
Windows arrow keys print key escape codes

### ISSUE THREAD

**Issue by Legorooj** [superfly/flyctl#1657]
**Describe the bug**
Arrow keys (and possibly others) don't work on windows, instead just printing their escape codes.

* Operating system: Windows 11
* `fly version`: `fly.exe v0.0.451 windows/amd64 Commit: 5a5b5b1f BuildDate: 2023-01-29T21:49:28Z`

**Command output:**

```text
$ fly launch
Creating app in C:\Users\legor
Scanning source code
Could not find a Dockerfile, nor detect a runtime or framework from source code. Continuing with a blank app.
? Choose an app name (leave blank to generate one): [D[A[C[B
```

**Comment by ndarilek** [comment]
Where are you running this? I get a lot of these types of issues running in cmd, but the Terminal app seems to help with lots of them.

**Comment by Legorooj** [comment]
I'm running it through Windows terminal.

**Comment by ndarilek** [comment]
Aha, looks like 32aeb8103ec44e0d694ca20929918065aaacf1ce causes this. I suspected that was too much magic at the time. Commenting out the `init` function that sets up stdout/stderr gets this working but of course breaks SSH consoles.

I'm going to see if I can conditionally compile/run the code in console_windows.go only when the `ssh console` command runs.
