### ISSUE TITLE
Apps v2 fly.toml no longer supports ports as strings

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#1673]
In the prerelease, ports in fly.toml are required to be integers. in the main distribution, they can be strings or ints. For example, the below config is valid in the main flyctl release today and invalid in the prerelease. We don't want to break everyone's fly.toml :-) 

```toml
[[services.ports]]
handlers = ["tls", "http"]
port = "443"
```

This is the error message flyctl produces with the prerelease:

```output
incompatible types: TOML value has type string; destination has type integer
```

To fix, update flyctl to allow processing the toml as string or integer and then parse the integer in flyctl if it was provided as a string.

**Comment by tvdfly** [comment]
related/dupe maybe: https://github.com/superfly/flyctl/issues/1619

**Comment by gwuah** [comment]
This has been fixed, there's a remnant which billy is addressing here https://github.com/superfly/flyctl/pull/1739

**Comment by billyb2** [comment]
Should be all good now
