### ISSUE TITLE
If an app fails to deploy first time, flyctl will block deployment

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#169]
A first time app deploy fail will leave the v0 app at dead in current HEAD version.

Initial fix will be to ignore the blocking code if version is 0.

Longer term fix? Create a real paused state?

**Comment by michaeldwan** [comment]
Paused is a real state, you can check it at `app.state`. I think the server should ensure apps are deployable though. We can make that change and throw an error if deployment should be rejected.

**Comment by codepope** [comment]
So far, not seen anything go to paused. It's either running, pending or dead.

**Comment by michaeldwan** [comment]
state can be `pending`, `deployed`, or `suspended`
status can be `pending`, `running`, `dead`, or `suspended` (though the `suspended` status should really be `pending`)

**Comment by codepope** [comment]
Switched to block for suspended status, new apps are appearing as pending so should always work.
