### ISSUE TITLE
Some errors not printed to console when running `fly m run`

### ISSUE THREAD

**Issue by ndarilek** [superfly/flyctl#1691]
**Describe the bug**
Running `fly m run` with an app name that's already taken silently fails.

* Operating system: Windows 10
* `fly version`: master

To reproduce:
1. Check out https://github.com/fly-apps/hello-rust.
2. `cd hello-rust`
3. `LOG_LEVEL=debug fly m run . -p 443:8080/tcp:tls:http -p 80:8080/tcp:http -a mytestapp`.
4. Assuming someone hasn't destroyed mytestapp, note that GraphQL calls run and error, but those errors aren't displayed to the console. Leaving off `LOG_LEVEL=debug` provides no indication that the command fails.

**Comment by billyb2** [comment]
Thanks for the report! Should be fixed in #1696
