### ISSUE TITLE
`fly secrets import` doesn't allow spaces in values

### ISSUE THREAD

**Issue by grantnorwood** [superfly/flyctl#1710]
## Describe the bug

When using `fly secrets import`, secret values containing spaces cause the command to fail.  This seems highly related to https://github.com/superfly/flyctl/issues/589.

_Questions:_
- Does the `fly secrets import` simply not support spaces in values?
- Should we loop through the [`secretsArray`](https://github.com/superfly/flyctl/blob/master/internal/command/secrets/import.go#L55) and be more flexible about properly handling spaces & double quotes?
- _**Do you need a volunteer to fix this?**_  I'm not a go developer, but I'm happy to try!

* Operating system: mac, linux
* `fly version`: `v0.0.456 darwin/amd64`

** Paste your `fly.toml`

```toml
# paste your config file here
```

## Command output

I attempted several ways to use spaces in values when importing secrets, with various newlines & quotes, and they all failed in similar ways.  The example below of munged secret values includes the output from a GitHub Action.

### Yaml

```yaml
secrets: |-
  MY_ENVIRONMENT="${{ env.MY_ENVIRONMENT }}" # = staging
  TEST_VAR_1="${{ env.TEST_VAR_1 }}" # = test value 1
```

### GitHub Action shell script

```shell
# input passed from yaml `secrets`
if [ -n "$INPUT_SECRETS" ]; then
  echo $INPUT_SECRETS | flyctl secrets import --app "$app"
fi
```

### `flyctl` output
```shell
+ flyctl secrets import --app some-app
+ echo 'MY_ENVIRONMENT="staging"' 'TEST_VAR_1="test' value '1"'
```

The way that the current cli version works by attempting to automatically surround values in quotes is not working particularly well for me, and seems unable to support spaces in values.

I am, however, able to successfully import secrets if I don't use any spaces or double quotes at all.  But that is specifically breaking a very common use case.

Am I simply using this incorrectly?  I forked the repo to try and spin up the cli, but I'm not 💯 sure what I'm doing 🙂  If there are some helpful developer docs for getting started, I'd love some links.  The `building.md` didn't seem to have what I'm looking for, and I wasn't sure if I needed to run the `install.sh` before building the docker image, do I need to rebuild and restart after each change, etc ... 

Thanks, y'all!

**Comment by tvdfly** [comment]
Thanks for reporting this issue! This looks like the same issue as #589.

We might be able to use [`shlex.Split()`](https://pkg.go.dev/github.com/google/shlex)  or [`go-envparse`](https://pkg.go.dev/github.com/hashicorp/go-envparse) in the secrets import code you linked. I think either of those would handle spaces and quoting and whatnot more robustly than the parse code we have today. If you're up for that, we'd appreciate the contribution! We'll get to it as soon as we're able otherwise.

> I forked the repo to try and spin up the cli, but I'm not 💯 sure what I'm doing 🙂 If there are some helpful developer docs for getting started, I'd love some links. The building.md didn't seem to have what I'm looking for, and I wasn't sure if I needed to run the install.sh before building the docker image, do I need to rebuild and restart after each change, etc ...

Make sure you have a modern version of go, then `make` or `winbuild.ps1` will build a local copy of the flyctl binary and place it in `bin/flyctl`. Then that binary can be used to test changes.

**Comment by grantnorwood** [comment]
@tvdfly Thanks for the fast reply and helpful instructions!  I’ll see what I can do about fixing this 🙂

**Comment by morelmiles** [comment]
Hi @tvdfly, 
I'd like to fix this. 
I need some help. 
I have the binary but how do I log in for commands that require it?
