### ISSUE TITLE
`fly services list` failing on Machines apps

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1716]
fly v0.0.457 darwin/arm64 Commit: f58a2e68 BuildDate: 2023-02-15T01:31:03Z

```
$ fly services list -a appname         
Oops, something went wrong! Could you try that again?
```

Error from @lillianberryfly's local build from master:
```
panic: interface conversion: interface {} is nil, not *flaps.Client
```

**Comment by tvdfly** [comment]
oh... i didn't know about this command... maybe it should go under `fly apps services ...` since it's specifically an app thing?  fyi @billyb2 

with apps v2 is can grab the app config from the latest release and find the services there. we can probably ignore the bug with machines until we merge apps v2.

**Comment by catflydotio** [comment]
The idea for this command came about here: https://github.com/superfly/flyctl/issues/78 And I brought it up again here: https://github.com/superfly/flyctl/issues/1631

I can see the argument for this being an `apps` subcommand.  Counterpoint? `fly launch`, `fly deploy`, `fly status`, `fly ips list` are all app things too, up to this point; and `fly apps services list` is a lot of subcommands. This is a somewhat myopic counterpoint that doesn't take into account the whole map of the commands and any grand plan for harmonizing their structures.

**Comment by billyb2** [comment]
I'd personally agree that while it would make sense as an apps subcommand, that there is currently precedent for it just being a regular subcommand. 

Also @catflydotio , do you still get this error on the latest commit? I get the same error on the commit specified, but on 65202b46fd341c2b769119ecc706a8dd331c30d7 it works well for me.

**Comment by billyb2** [comment]
Oh great. Would you mind explaining the port number issue a bit, so i could get started on a fix?

**Comment by catflydotio** [comment]
I'm not on top of flyctl code and I don't want to throw you a red herring, but I'm wondering if flyctl is getting something funny back, or not in the format it expects, for `port.Port` in `ShowMachineServiceInfo()`: https://github.com/superfly/flyctl/blob/46cac31460c7e9a20693b65ae26f432b777a7a79/internal/command/services/machines.go#L50

I should really just say "All I really know is that I get something that makes sense for Nomad apps and not for Machines apps."

Here's a Nomad app.

```
$ fly services list -a totes-annotes
Services
PROTOCOL        PORTS                   
TCP             80 => 8080 [HTTP]      
                443 => 8080 [TLS, HTTP]
```

**Comment by billyb2** [comment]
@catflydotio i was printing the memory addresses... i'll fix up a PR in a second.
