### ISSUE TITLE
`fly machine list -q` should really be quiet

### ISSUE THREAD

**Issue by matthewadams** [superfly/flyctl#1746]
**Describe the bug**
When I issue the command `fly machine list -a my-app -q`, when there are zero machines it should write nothing to `stdout`.   Currently, it writes `No machines are available on this app my-app` to `stdout`.  If you're going to write that message, it should be to `stderr`, but really, since I said in the invocation to be quiet via `-q`, nothing should be written.

* Operating system
* `fly version`
fly v0.0.462 darwin/arm64 Commit: 2090b107 BuildDate: 2023-02-17T09:37:58Z

** Paste your `fly.toml`
I'm not using a `fly.toml`.

** Command output: **

```text
$ fly m list -q -a poolminder
No machines are available on this app poolminder
```

**Comment by matthewadams** [comment]
Also, if there are machines present, the `-q` should only return their ids, but it returns
```
1 machines have been retrieved from app poolminder.
View them in the UI here

poolminder
ID
...
```
and I have to use `tail` to skip all lines up to the actual ids.

**Comment by billyb2** [comment]
Hi @matthewadams , thanks for the report! I made a PR to fix the issue.

**Comment by matthewadams** [comment]
You might want to check all of the commands that support quiet/silent to make sure they're behaving similarly.
