### ISSUE TITLE
fly machine run with a schedule seems to hang

### ISSUE THREAD

**Issue by alichay** [superfly/flyctl#1760]
### **Describe the bug**

Calling `fly machine run` and passing the machine a schedule causes flyctl to wait a seemingly indefinite time.
It _might_ be waiting for the scheduled event to pass? Regardless, this can't be right...

To reproduce, just run `fly m run . -a [app name] --schedule hourly`

For what it's worth, I'm running these commands in a directory with [these files](https://gist.github.com/alichay/f3d4e102c66d8ea6ad3e0bff9e1d27cf).

### **Command output:**

```text
--> Pushing image done
Image: registry.fly.io/[app name]:deployment-[deployment id]
Image size: 41 MB

Success! A machine has been successfully launched in app [app name], waiting for it to be started
 Machine ID: [machine id]
 Instance ID: [instance id]
 State: created
```
but then it just hangs.

With `LOG_LEVEL=debug`, it says
```
Success! A machine has been successfully launched in app [app name], waiting for it to be started
 Machine ID: [machine id]
 Instance ID: [instance id]
DEBUG --> GET http://[fdaa:1:3c2e::3]:4280/v1/apps/test-appsv2/machines/[machine id]/wait?instance_id=[instance id]&state=started&timeout=60

DEBUG <-- 408 http://[fdaa:1:3c2e::3]:4280/v1/apps/test-appsv2/machines/[machine id]/wait?instance_id=[instance id]&state=started&timeout=60 (56.95s)

{
  "error": "machine failed to reach desired state, started, currently stopped"
}

DEBUG --> GET http://[fdaa:1:3c2e::3]:4280/v1/apps/test-appsv2/machines/[machine id]/wait?instance_id=[instance id]&state=started&timeout=60
```

This might be related to #1751

**Comment by matttpt** [comment]
Scheduled machines have been updated to start immediately (whereas previously they waited for the full schedule period before starting the first time). This is what `flyctl` currently [expects](https://github.com/superfly/flyctl/blob/bec833f4ab258f18c29f1ff5d5e301801ec6bea0/internal/command/machine/run.go#L277), so I'm thinking that that change has resolved this?
