### ISSUE TITLE
No ipv4 or ipv6 ip addresses allocated to app lab-database

### ISSUE THREAD

**Issue by desumer** [superfly/flyctl#1771]
**Describe the bug**
Trying to run fly proxy 5432 -a lab-database it doesn't do anything. Then I tried fly doctor -a lab-database and get Please file a bug with this message. 
Ip address fdaa:1:68ca:0:1::7 has unexpected type 'private_v6'. 

* Operating system
Ventura 13.2.1 on M1 Mac Studio
 
* `fly version`
fly v0.0.464 darwin/arm64 Commit: f9840dd8 BuildDate: 2023-02-22T09:34:00Z

** Paste your `fly.toml`
app = "geneversity"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

**Comment by tvdfly** [comment]
Hi @desumer , please post this in our https://community.fly.io/ forum and someone can help there. Thanks!
