### ISSUE TITLE
flyctl domains should be deprecated

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1791]
We recently had a forum user [wondering](https://community.fly.io/t/domain-registration-is-not-enabled-on-this-organization/11031) why `flyctl domains` wouldn't work for them. The reason is that it doesn't work for anybody but the people who tested the feature as a preview.

`fly domains` is removed from docs and hidden in flyctl's list of commands we don't hate, but it's still not deprecated. I can get a couple of steps into trying to register a domain without any indication that it's not an available feature.

**Comment by billyb2** [comment]
Should any command in flyctl domains just return a deprecation warning and not even bother trying to run further?

**Comment by catflydotio** [comment]
I think `register` should stop; but it would be nice if `fly domains -h` also indicated it's deprecated. If anyone happens to still have domains they created with this, they should be able to run `domains list` or `domains show`, I think.
