### ISSUE TITLE
Apps V2 - Region mistmatch between app region pool and first machine

### ISSUE THREAD

**Issue by PierBover** [superfly/flyctl#1798]
So @catflydotio [mentioned in the forum](https://community.fly.io/t/fly-apps-on-machine-prerelease/10219/25?u=pier) that UX confusions are fair game for Github issues.

When creating a new v2 app with `fly launch --force-machines` the app region selection is still shown but then the machine itself is not created in that region.

I created a v2 app in QRO but the initial machine was created in DFW which is confusing.

@catflydotio clarified that machines don't use the region pool. Makes sense but as a user I don't understand why the first machine was created in DFW. Not only I actually live in QRO but I selected QRO as the region for my app.

What I think would make more sense is that the user should have the option to decide where the first machine will be created. 

The first machine could be deployed in the same region that was selected in the app region selection (even though machines ignore the region pool). Or maybe there should be a new menu afterwards just for that first machine?

Also, when using `fly launch --force-machines` what's the point of having an app region pool at all if all VMs will be running with machines?

**Comment by catflydotio** [comment]
Since I'm responsible for bringing this here:

Thanks for the report. :)

Right now it's a bug if you're selecting a region during launch and the first machine doesn't get put there.

There isn't a point to having the region pool for a V2 app, and it'll get deprecated when creating a Nomad app does.

**Comment by gwuah** [comment]
The issue of machines not being deployed in the right region was fixed [here](https://github.com/superfly/flyctl/pull/1769). 
What version of the CLI are you on @PierBover?

**Comment by PierBover** [comment]
Just updated today.

```
fly v0.0.473 darwin/amd64 Commit: f721dccf
```

As you can see I selected QRO when launching:
```
Region Pool:
qro
```
But the machine is running in DFW:
```
32874403b56285	icy-sunset-7219	started	dfw
```
<img width="703" alt="image" src="https://user-images.githubusercontent.com/226483/222231694-5878dee4-0478-43d0-8115-8b99755832b7.png">

**Comment by PierBover** [comment]
BTW I didn't deploy when doing `fly launch` because I needed to add some secrets first.

**Comment by catflydotio** [comment]
I've reproduced this with v0.0.474 I think. Steps:

1. `fly launch --force-machines` and specify a region when asked, but say no to deploy now
2. `fly deploy --force-machines` and don't use a `--region` flag

The machine will be launched in your default region (for me just now, `iad`).

When I said yes to deploy during launch, it deployed the machine in my chosen region ✔️ 

So people can work around this by using the `--region` flag on the first deploy. But it has to be the first deploy--or specifically, there have to be zero machines on the app. If there's a machine running, `fly deploy --region` will update the running machine in whatever region it's already running. It won't launch one in a different region.

**Comment by tvdfly** [comment]
https://github.com/superfly/flyctl/pull/1795 is in progress to address this
