### ISSUE TITLE
Apps V2 - `fly launch --image` doesn't fill in `[build]` section in `fly.toml`

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1820]
`flyctl v0.0.0-1677791596+dev darwin/arm64 Commit: 3c041ba5dcb5b8966fb2e8b5c62287991f648097 (master) BuildDate: 2023-03-02T21:13:16Z`

This prevents `fly deploy`.

To reproduce:

`$ ~/flyctl/bin/flyctl launch --image nginx --force-machines` 

`fly.toml` will be generated but without any `[build]` section.

Optional step: try to deploy

`$ ~/flyctl/bin/flyctl deploy --force-machines`

Get error `Error failed to fetch an image or build from source: app does not have a Dockerfile or buildpacks configured. See https://fly.io/docs/reference/configuration/#the-build-section`

**Comment by dangra** [comment]
Fixed by #1830 (https://github.com/superfly/flyctl/pull/1830#discussion_r1128076350)
