### ISSUE TITLE
Unify `fly machines <command> <mid>` commands

### ISSUE THREAD

**Issue by alichay** [superfly/flyctl#1849]
Some of the `fly m <command> <mid>` commands, like restart, work by looking up the first machine ID's app, and then using that app for the rest of the machines. This makes it easier to work with individual machines, where specifying the app each time can just feel like a hassle.

E.g. doing `fly m restart 0123 4567 8910` would look up the App associated with `0123`, and then act as if that app was passed in via `-a`.

Some commands, like the `fly m lease` family, don't work the same way. It'd be nice to make these all consistent.

At the same time, some of these commands feel like they *should* require an explicit app. Off the top of my head, `clone` actually adds a machine to the app. Conceptually, this feels like it should require an explicit app because it's not just affecting that single machine anymore.

(born out of conversation in #1834)

**Comment by matttpt** [comment]
Done in #1899.
