### ISSUE TITLE
fly auth login panic

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#1877]
https://flyio.sentry.io/issues/3987680462/events/00e2218a28e4497bbac321a2d4d5a2b4/?project=4492967

Seems like something funky with the way access token is set. I wasn't able to repro, though.

**Comment by kzys** [comment]
@dangra - Is it fixed?

**Comment by dangra** [comment]
Yes, it is. https://github.com/superfly/flyctl/pull/1929 fixed it.
