### ISSUE TITLE
internal_port in fly.toml should be removed

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#19]
As it currently stands, the setting invites users to change it. But, changing it just breaks the deployment process by making the health checks fail. Removing health checks has no effect in the toml, so am assuming that they are hard wired in place to port 8080.

So, until we have a changable internal_port, we should remove the generation of said port number and replace with explicit direction to use port 8080 in the enclosed application.

**Comment by michaeldwan** [comment]
fixed

**Comment by a-h** [comment]
I found the confusing thing here was that the default builder doesn't look at the `fly.toml` file to work out the `internal_port` port, so the automatically generated Dockerfile doesn't expose the port. This led to my deployment failing.
