### ISSUE TITLE
Apps v2 - `fly launch` overwriting `fly.toml` even when asked to use existing config

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1900]
(App is a Dockerfile app and flyctl is v0.0.487)

To reproduce:

1. Start with a custom `fly.toml` in the working directory. Say internal port is 8043 instead of 8080.

2.:
```
$ fly launch
An existing fly.toml file was found for app garbage
? Would you like to copy its configuration to the new app? Yes
etc
```

3. Check fly.toml before deploy: `internal_port` has reverted to 8080.

**Comment by ndarilek** [comment]
I think #1904 should fix this. At least, it seems to leave fly.toml intact if I make a change, answer "y", and don't deploy.

**Comment by dangra** [comment]
not sure where to discuss what is expected from this ticket, but I went for @ndarilek open issue https://github.com/superfly/flyctl/pull/1904#issuecomment-1470763901

**Comment by catflydotio** [comment]
Possibly @gwuah has picked this up, but the issue arose from a change in the Dockerfile scanner to now get the internal port for `[services]` from any EXPOSE statement in the Dockerfile. The problem is that this new logic forces port 8080 if there's no EXPOSE in the Dockerfile, which there often isn't.
