### ISSUE TITLE
Apps v2 - `fly scale vm` without `--group` applies to the process with the lexicographically earlier name

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#1991]
Before:

```
$ fly scale show
VM Resources for app: floo

Groups
NAME    COUNT   KIND    CPUS    MEMORY  REGIONS 
proc2   1       shared  1       256 MB  yyz    
web     1       shared  1       256 MB  yyz 
```

Scale it:

```
$ fly scale vm performance-1x 
Updating machine e2865522b9e986
  Waiting for e2865522b9e986 to become healthy (started, 1/1)
Machine e2865522b9e986 updated successfully!
Scaled VM Type to 'performance-1x'
      CPU Cores: 1
         Memory: 2048 MB
```
Only one machine updated?

Check:

```
$ fly scale show
VM Resources for app: floo

Groups
NAME    COUNT   KIND            CPUS    MEMORY  REGIONS 
proc2   1       performance     1       2048 MB yyz    
web     1       shared          1       256 MB  yyz
```

`proc2` is the first process listed in `fly.toml`.

**Comment by matttpt** [comment]
Unless a progress group is supplied with `--group`, it uses the default process group. In this case, since there's no group called `app`, it picks `proc2` as the default because it's the first lexicographically. ([source](https://github.com/superfly/flyctl/blob/603f2b76a8d4bc54be5da12d2556d55827cc0fad/internal/command/scale/machines.go#L26))

Does this differ from `scale` for Nomad apps?

**Comment by catflydotio** [comment]
> Does this differ from scale for Nomad apps?

hahaha we don't want to emulate what Nomad does with process groups.

But seriously, what UX do we actually want? That's what we should do.

**Comment by catflydotio** [comment]
(it can be as simple as a message saying which process group it's applying to)

**Comment by mrkurt** [comment]
If there's no default process group, this should probably just error. Scaling multiple process groups at a time sounds like it'll create a bunch of suprises.

**Comment by catflydotio** [comment]
This is kind of hilarious. I see that `fly launch` rewrites my process list in alphabetical (or lexicographical) order, too. I'm just going to document that you need to use `--group` if you have multiple processes.
