### ISSUE TITLE
Launching internal only services

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#2084]
I deployed an app today that I only wanted available internally, in this case via flycast. It would have been a security issue if it was public.

The app has the standard http services (port 80 http, 443 tls+http), so `fly deploy` helpfully automatically provisions public ips on the first deploy. That concerned me.

I didn't know (and didn't check, I was in a hurry!) if I provisioned a flycast ip with `fly ips allocate-v6 --private` before the first deploy if `fly deploy` would still provision public ips.

I ended up running `fly launch` and skipped the deployment. I commented out all the services config in fly.toml, and ran then ran `fly deploy`. After that I provisioned the flycast ip, uncommented the services config, then deployed. That worked, yay!

I think we could improve this experience for developers. Some ideas:

* Add a `--no-public-ips-on-first-deploy` flag to `fly deploy` (we can probably come up with a better name for the flag if we do this 😄 )
* Add something to the services config that indicates it should only be accessible via flycast, e.g., something like:

```toml
[[services]]
  flycast_only = true
```

For reference, I was using this version of flyctl:
```
% fly version
fly v0.0.521 darwin/arm64 Commit: 4523084f BuildDate: 2023-04-14T15:35:03Z
```

**Comment by jsierles** [comment]
Agreed here, but I run some internal apps that just use DNS and don't need flycast. In a previous experiment with `launch`, it asked if your app runs a public HTTP service or not.

**Comment by gbraad** [comment]
I also seen `flyctl deploy` specifically ask now for a

`Would you like to allocate a dedicated ipv4 address now?`

It does however not indicate what the alternative is or what the 'no' chosen results in.
