### ISSUE TITLE
Unknown error during deploy

### ISSUE THREAD

**Issue by hengestone** [superfly/flyctl#21]
Using `flyctl 0.7.x`, doing `flyctl create` or `flyctl deploy` with either the `go-example` or `csharp-example` I eventually get:
`Error An unknown error occured.`

Any ideas? I can send a copy of the `strace` output if that helps :)

Thanks!

**Comment by mrkurt** [comment]
I'm seeing a few bugs, it looks like `create` might've failed because the app name was taken. Can you give that one another try and see how it works? That error should definitely be more graceful, I made #22 for that. Do you remember what app name you specified on create?

**Comment by mrkurt** [comment]
@hengestone #22 is fixed now, which should make `flyctl create` behave. Will you see if `flyctl deploy` still has issues?

**Comment by hengestone** [comment]
Confirmed, `flyctl create` and `flyctl deploy` works now. Thanks!
