### ISSUE TITLE
`flyctl regions list` lost `--json` support

### ISSUE THREAD

**Issue by salim-b** [superfly/flyctl#2119]
**Describe the bug**

Since recently, `flyctl regions list --json` doesn't work anymore ("Error: unknown flag: --json"). I need to parse the output of that command in a script, thus I'd like to have JSON output back.

* Operating system: Linux (Ubuntu 22.04)
* `fly version`: v0.0.526

**Comment by matttpt** [comment]
Thanks for the report! We recently converted `--json` from a global flag to a command-specific flag, and it looks like `regions` and a few other commands were overlooked. A fix has been merged and should be in the next release of `flyctl`.
