### ISSUE TITLE
`fly scale count` with `-a` flag causes unexpected Frankenstein scaling

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#2164]
I think `fly scale count` is checking for current scale, and at least some part of config, from the local `fly.toml` and the app named in it, but applying changes to the app named using the `-a` flag.

Context: I'd listed my apps and was destroying some of them. There was one I decided just to scale to 0 Machines instead of destroying the app. I don't think I still have a `fly.toml` with that app name in it anywhere, and anyway, scaling to 0 should be fine from any directory.

But `fly scale count` told me it was already at 0 (which was the correct answer for the app whose name is in the local `fly.toml`).

```
$ fly scale count 0 -a c-appsv2-preview
App already scaled to desired state. No need for changes
```

`fly scale show` gets the right scale: 

```
$ fly scale show -a c-appsv2-preview
VM Resources for app: c-appsv2-preview

Groups
NAME    COUNT   KIND    CPUS    MEMORY  REGIONS 
app     1       shared  1       256 MB  yyz   
```

As a test, I tried scaling up instead of down. The changes look like they come from `fly.toml`

```
$ fly scale count 2 -a c-appsv2-preview
App 'c-appsv2-preview' is going to be scaled according to this plan:
  +2 machines for group 'web' on region 'yyz' with size 'shared-cpu-1x'
  ...
```

Since `fly scale count` doesn't seem to be aware of the existing `app` machine, it leaves that one alone. In the end, interestingly, the new Machines don't have services, although they belong to the process group that has services in `fly.toml`, and so does the one existing Machine on the app.

```
$ fly status -a c-appsv2-preview    
App
  Name     = c-appsv2-preview                                        
  Owner    = personal                                                
  Hostname = c-appsv2-preview.fly.dev                                
  Image    = c-appsv2-preview:deployment-01GVEB7QHNCRJP2K4PNGP8C4J9  
  Platform = machines                                                

Machines
PROCESS ID              VERSION REGION  STATE   CHECKS                  LAST UPDATED         
app     6e82dd00f74687  2       yyz     started 1 total, 1 passing      2023-03-13T21:34:43Z
web     148ed596f01389  2       yyz     started                         2023-04-23T20:02:13Z
web     9080e699a39e87  2       yyz     started                         2023-04-23T20:02:24Z
```

Here's the `fly.toml` from the cwd:

```
# fly.toml app configuration file generated for floof on 2023-04-22T18:31:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "floof"
primary_region = "yyz"

[build]
  image = "nginx"

[processes]
  web = ""
  worker = "tail -F /dev/null"

[http_service]
  processes = ["web"]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    processes = ["web"]
    type = "tcp"
    interval = "3s"
    timeout = "2s"
    grace_period = "5s"
```

**Comment by matttpt** [comment]
Good catch! `fly scale count <n>` was reading the local `fly.toml` to find the default process group to use. With #2210 and #2219 merged, this shouldn't happen again.
