### ISSUE TITLE
Dockerfile should be allowed to be .dockerignore'd

### ISSUE THREAD

**Issue by gabrielalmeida** [superfly/flyctl#2245]
Fly requires Dockerfile to be part of its context when running `fly deploy` and will fail if `Dockerfile` is part of `.dockerignore`:

> Error: failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /data/docker/tmp/buildkit-mount150277830/apps/dashboard/Dockerfile: no such file or directory

This alone is unexpected and differs from how Docker works.

[.dockerignore reference](https://docs.docker.com/engine/reference/builder/#dockerignore-file): 
> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. **These files are still sent to the daemon because it needs them to do its job**. But the ADD and COPY instructions do not copy them to the image.

Thus, Dockerfile will always be part of the "internal docker build" context and causes a `COPY . .` cache to be invalidated leading to expensive unnecessary rebuilds.

For instance, due to this limitation, a single change on Dockerfile in an unrelated layer may cause all dependencies to be installed again and a new build to run, going from a fully cached build to an expensive 10min+.

As put by @jacobgreenleaf on a [comment](https://github.com/superfly/flyctl/pull/1213/files#diff-7dd2551e6b56af8196ece355e6635fd2d69ded0dc977c10e4276f3a43b6fb9c2R76-R79) on PR https://github.com/superfly/flyctl/pull/1213:

> // When a user writes a dockerignore file, they might include a rule for "Dockerfile", or ".dockerignore".
// Those files must still be sent to the Docker daemon via this archive, however the user's intent of having
// the file excluded from the image that gets built is still preserved because their dockerignore file
// is transmitted in the archive as-is before these exclusions are added.

The PR was closed without comments so I've created this issue.

**Comment by matttpt** [comment]
#2260 should fix this in the next `flyctl` release. Feel free to re-open this if not.

Thanks @gabrielalmeida for the detailed issue and @jacobgreenleaf for the first look at this in #1213 (#2260 turned out to be pretty similar)!
