### ISSUE TITLE
Deploying container fails due to unhealthy allocations

### ISSUE THREAD

**Issue by hengestone** [superfly/flyctl#23]
Hi,
I'm trying to deploy an example docker app from `erlang/docker-erlang-example` using `flyctl deploy`.

The container runs using regular docker locally, builds fine when doing `flyctl deploy`, but eventually fails with
`Failed due to unhealthy allocations - no stable job version to auto revert to`
See attached output of `flyctl deploy --verbose`:

[docker_deploy_error.txt](https://github.com/superfly/flyctl/files/4017871/docker_deploy_error.txt)

**Comment by michaeldwan** [comment]
@hengestone that usually happens when the app fails to start or isn't listening on `internal_port` in fly.toml. The logs (`flyctl logs`) are full of messages saying a cookie isn't found, could that be causing the app to crash? Send an email to support@fly.io or hop on gitter and we can help get this fixed.

**Comment by hengestone** [comment]
Will do, thanks.

Just to add the info while I have it in front of me:
- The cookie warning is normal, it just means the erlang node is not part of a cluster.
- Starting the container on the command line gives the same warning, but runs fine:

```
$> docker run -ti --init dff3c5d13d36 
No cookie is set or found. This limits the scripts functionality, installing, upgrading, rpc and getting a list of versions will not work.
Exec: /dockerwatch/erts-10.6.1/bin/erlexec -noshell -noinput +Bd -boot /dockerwatch/releases/1.0.0/dockerwatch -mode embedded -boot_var ERTS_LIB_DIR /dockerwatch/lib -config /dockerwatch/releases/1.0.0/sys.config -args_file /dockerwatch/releases/1.0.0/vm.args -- foreground
Root: /dockerwatch
/dockerwatch
```
with `netstat -ln` (app is configured to listen on post 8080 in `fly.toml`)
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:41605           0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      
tcp        0      0 :::4369                 :::*                    LISTEN      
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
```

**Comment by mrkurt** [comment]
@hengestone it seems like the process is actually hanging after the cookie message, so it's not really a config problem ... the image just isn't running right in our Firecracker environment. We're digging into it to figure out hwy.

**Comment by hengestone** [comment]
Thanks, much appreciated!

FWIW, I think in general for you guys it might be useful to document how to run Firecracker locally to reduce your support burden :pray:

**Comment by jeromegn** [comment]
@hengestone that's a good idea. I have a _somewhat_ working program that does just that. It needs a lot more work to _actually_ work though.

**Comment by jeromegn** [comment]
@hengestone this might be fixed now.

Our init program didn't set the loopback interface UP. Apparently erlang programs sometimes (always?) run a thing called `epmd` which bind to the loopback device.

I started your app and it looks healthy now.

**Comment by hengestone** [comment]
Ah, yes, that makes sense - epmd is a coordinator for Erlang nodes in a cluster: http://erlang.org/doc/man/epmd.html
Thanks again for looking at this!
