### ISSUE TITLE
Add a --local-only flag to the flyctl deploy command

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#237]
... or something along those lines. Inspired by --remote-only :)

Why?

Well, I've been trying a deploy from CircleCI. And getting some odd random build issues. Not sure if it is their service, but it is a standard Linux base so it should work ok. In their terminal, what seems to happen (without using the --remote-only flag) is that it installs flyctl, sees that it can't do a local build, and so tries a remote one. Which you'd normally want it to, I guess:

```
 ...
Saving to: ‘flyctl_0.0.137_Linux_x86_64.tar.gz’
flyctl_0.0.137_Linu 100%[===================>]  13.06M  --.-KB/s    in 0.1s    
2020-07-14 20:03:54 (131 MB/s) - ‘flyctl_0.0.137_Linux_x86_64.tar.gz’ saved [13696695/13696695]
flyctl
Deploying name
==> Validating App Configuration
--> Validating App Configuration done
Services
TCP 443 ⇢ 8080 
Deploy source directory '/home/circleci/build_dev'
Docker daemon unavailable, performing remote build...
 
Creating build context... ⣾Creating build context... ⣽Creating build conte ...
```

... and so on for loads and load of 'building messages'.

BUT after a while, _this_ shows up:
```
Flyctl was installed successfully to /usr/local/bin/flyctl
 
Run 'flyctl --help' to get started
 
0.0.137
 
printenv
 
Deploying name
 
==> Validating App Configuration
 
Building ⢿Building ⡿Building ⣟Building ⣯Building ⣷Building ⣾Building ⣽Building ⣻Building ⢿Building ⡿Building ⣟--> Validating App Configuration done
 
Services
 
TCP 443 ⇢ 8080 

Deploy source directory '/src'
 
Docker daemon available, performing local build...
 
==> Building with Dockerfile
 
Using Dockerfile: /src/Dockerfile
...
 ```

Sooo ... it says "Docker daemon available, performing local build...". Hmm. So CircleCI _does_ provide docker.

And so not sure what is happening behind the scenes at this point, as there seems to be a battle in the console between 'Building;' messages (by the hundred) which are presumably all from the remote build, in the background, and then all the normal local messages you get when running docker locally, like

```
--> Building with Dockerfile done
... etc ...
==> Creating Release
Release v13 created
Monitoring Deployment
 ```

And then once it deploys, CircleCI ends. But in the background, is that remote build still happening? So a deploy (n+1) is happening after CircleCI ends? Not clear. Or is the remote build abandoned once it sees the local build worked?

So I wondered if a _--local-only_ flag could avoid this weirdness by stopping flyctl even starting a remote build (despite the fact it thinks it needs to). Just a thought.

**Comment by mrkurt** [comment]
CircleCI is a bit of a pain, a `--local-only` flag would make a ton of sense for CI too. Good idea.

**Comment by michaeldwan** [comment]
We've encountered this with a few other people using CircleCI. Are your CircleCI builds running inside a docker container? Are you using the `setup_remote_docker` step described here https://circleci.com/docs/2.0/building-docker-images/?

And yeah, some type of flag to prevent remote builds is a good idea, cc @codepope.

**Comment by gregmsanderson** [comment]
Not sure if they run inside docker internally. I'm not doing anything command-wise or in its yml to _specify_ using docker. So I assume not.

I did see that setup_remote_docker step but I am not using it since I saw the console output saying docker was available already. So figured i didn't need a remote one. But I may not have understood its usage.

**Comment by mrkurt** [comment]
We need to test this, but there's a chance you're seeing console output from the _remote build_. All a remote build does is runs `flyctl deploy` in a VM with docker available, so it has the exact same output (we just filter it to make it nicer).

**Comment by gregmsanderson** [comment]
Ah ... well that would explain it too. I figured it was a local one but that would make sense if the 'docker daemon available' text was actually coming from the remote one, as of course it _would_ be available on that :) In which case, no need for a --local-only as that's actually not what I thought was happening.

And that would point to yes, needing some flag, like setup_remote_docker, to get a local one working on the CircleCI end.

I don't mind where the build happens, wherever is faster. It was more to avoid the five hundred 'Building' messages. If it was a local build it would give more visibility, maybe. As local ones always seem faster to build, but then take longer to upload (from local). Hence looking at CircleCI doing it.

**Comment by codepope** [comment]
@gregmsanderson you may want to try the --json flag on flyctl which also tries to suppress the spinners (where all the building messages come from). I'm working on evolving it to enable more tracked automation (for a VSCode extension) but that may be useful for your CI case.

**Comment by gregmsanderson** [comment]
@codepope Ok, thanks. I know you can detach from it, but I _want_ to see the output to know if it worked or not. I guess if it supresses then CircleCI might abandon it after X minutes, thinking there's no output. Have to see.

**Comment by codepope** [comment]
You still get output but its in JSON format and the spinner is surpassed but not the other output.

Dj

**Comment by gregmsanderson** [comment]
Further to this, I did try adding the --json flag, and sure enough, get JSON back.

But even with that I still get pages and pages of 'Building', over and over.

And it seems to take forever to complete. Not sure if it is a temporary fault with CircleCI, github and/or fly, but one build of a tiny project took half an hour and printed so many 'Building' lines the browser crashed :) Had to cancel it. See below.

I tried adding the
```
- setup_remote_docker
```

... and using docker it does indeed allocate one, and that step works:
```
"Allocating a remote Docker Engine"
(etc)
```

But then the subsequent step, using flyctl doesn't spot it:
```
...
{"Source":"flyctl","Status":"info","Message":"Docker daemon unavailable, performing remote build..."}
...
```

And proceeds to, again, not complete. Hmm. I mean for now I can try again locally, it's just a pain uploading big docker-made files on a slow connection. CircleCI takes forever/never to build, but uploads quickly.

![building](https://user-images.githubusercontent.com/10390169/87583520-fe981400-c6d3-11ea-8e11-539d8357f57e.png)

**Comment by gregmsanderson** [comment]
_Finally_ got it to work.

Seems like remote builds are the issue. May be a project thing, may be a CircleCI thing, but whatever it is, remote builds take forever and seem to not complete at all. At least I give up after 10 minutes+. No way they should take that long.

After many (many) attempts, got it to work using a local build to get the elusive 'success'.

So I think having a --local-only type flag would be of some use, as that would stop it doing a remote build and so fail immediately if docker was not available.

![Screenshot 2020-07-15 at 21 15 05](https://user-images.githubusercontent.com/10390169/87591729-a74c7080-c6e0-11ea-812b-c489f5414149.png)
