### ISSUE TITLE
`flyctl launch` misdetects Remix apps as NodeFramework apps

### ISSUE THREAD

**Issue by m5r** [superfly/flyctl#2388]
**Describe the bug**
Running `npx create-remix@latest` followed by `flyctl launch` in the newly created app's folder does not detect it as a Remix app anymore:

```text
$ flyctl launch
Creating app in /home/mokhtar/app/ddd
Scanning source code
Detected a NodeJS app
? Choose an app name (leave blank to generate one):
```

If I remove `configureNodeFramework` from the [list of scanners on line 93](https://github.com/superfly/flyctl/blob/master/scanner/scanner.go#L93), I get the correct behavior:

```text
$ ../flyctl/out launch
Creating app in /home/mokhtar/app/ddd
Scanning source code
Detected a Remix app
```

I'm running:
* Manjaro 22
* flyctl v0.1.23 linux/amd64 Commit: 4aa1bbf64fc3d6696450dec51ccd0bfd5782454c BuildDate: 2023-05-30T15:32:31Z

**Comment by jaaneh** [comment]
Also seeing this when trying to deploy a Next.js app. Happened so far on both flyctl `v0.1.23` and `v0.1.24`.
```
❯ fly launch    
Creating app in /home/jan/dev/myapp
Scanning source code
Detected a NodeJS app
? Choose an app name (leave blank to generate one): 
```

**Comment by Adbib** [comment]
You can copy Dockerfile, fly.toml, start.sh files from an old project and try to deploy it again.
 It worked for me

**Comment by hawkcookie** [comment]
I have the same problem. cli version is `v0.1.38`.

**Comment by redjonzaci** [comment]
`flyctl` correctly detected a Remix app after running `fly launch` inside the folder created by `npx create-remix@latest`.
@m5r can you confirm it works for you too?

**Comment by m5r** [comment]
Kind of late response but yes, it works for me too. Thanks @dobecad for fixing it!
I'm closing the issue
