### ISSUE TITLE
Running the mutation AddCertificate twice doesn't throw an error

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#241]
Running the mutation AddCertificate twice doesn't throw an error. The second time, it just returns an empty structure.

**Comment by mrkurt** [comment]
I think the intent for that one was to make it idempotent, so it should return the cert with that name. Do you think an error is better?

**Comment by codepope** [comment]
An error is better when there is no cert with that name. The client can't tell what its getting back. showCerts could be called to get the current cert.

**Comment by mrkurt** [comment]
We have at least one customer that runs those over and over so throwing an error wouldn't be awesome for them. We can attach errors and possibly return the existing cert though, that might work.

**Comment by codepope** [comment]
I think working and returning an error is even worse. As long as we can bake in and the empty returns means a change was dropped because the cert existed, then we should be good. Closing this ticket for now.
