### ISSUE TITLE
[error]could not make HTTP request to instance: connection error: timed out

### ISSUE THREAD

**Issue by Joseamica** [superfly/flyctl#2480]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

2023-06-26T15:14:48Z proxy[080eed5f661048] dfw [error]could not make HTTP request to instance: connection error: timed out

Im using sse events on my application, and once this error appears, the app then it doesnt sincronize with other users.

fly supports Long-Lived Connections?

`
app = "av"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true
enable_consul = true
allowed_public_ports = []

[deploy]
release_command = "bash ./scripts/migrate.sh"

[mounts]
source = "av"
destination = "/data"

[env]
FLY_REGION = "dfw"
METRICS_PORT = "8081"
PORT = "8080"
PRIMARY_REGION = "dfw"

[[services]]
# http_checks = []
script_checks = []
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "4s"
grace_period = "15s"
restart_limit = 0

[[services.http_checks]]
interval = "10s"
timeout = "4s"
grace_period = "5s"
method = "get"
path = "/healthcheck"
protocol = "http"
tls_skip_verify = false
headers = {}
# [services.http_checks.headers]

[metrics]
port = 8081
path = "/metrics"
`

**Comment by michaeldwan** [comment]
This looks like an issue with a deployed app, and issues in this repo are for flyctl itself. There's a lot more people who can help at community.fly.io -- can you please ask over there?
