### ISSUE TITLE
Flyctl y/N prompt are not visible in light theme

### ISSUE THREAD

**Issue by tshu-w** [superfly/flyctl#2543]
**Describe the bug**
In the light theme, the y/N prompt in Flyctl is not visible, making it difficult to interact with the prompt. This issue can cause confusion and hinder the user experience, especially for users who prefer the light theme. It would be helpful to address this and ensure that the y/N prompt is properly visible in both light and dark themes.

* Operating system: macOS 13.4.1
* `fly version`: fly v0.1.52 darwin/arm64 Commit: 9928dce858ee7d597f7af9068fca6e72893f3c56-dirty BuildDate: 2023-07-07T23:13:50Z

** Paste your `fly.toml`

```toml
Default
```

** Command output: **
<img width="396" alt="Screenshot 2023-07-09 at 15 38 36" src="https://github.com/superfly/flyctl/assets/13161779/6d3d2e6b-d77c-4188-af21-a083ca6c7de6">

**Comment by usrme** [comment]
First, I'm not affiliated with Fly in any way, but this mimics the behavior of the dependency that they use, `go-survey/survey`:

![image](https://github.com/superfly/flyctl/assets/5902545/557de86c-bb52-4115-9b6b-52751a2448ec)

Which itself uses the ANSI color code `white` for confirmation prompts: https://github.com/go-survey/survey/blob/fa37277e6394c29db7bcc94062cb30cd7785a126/confirm.go#L33. This obviously breaks down in light themes. 

Unfortunately `go-survey/survey` only provides a way to [change the format and color of the icons](https://github.com/go-survey/survey#changing-the-icons) preceding the messages and it seems that the project isn't _that_ actively maintained. Just changing the aforementioned `white` to `default`, to match whatever the terminal emulator theme's default color is, would fix this though:

![image](https://github.com/superfly/flyctl/assets/5902545/33a80f37-ddd4-4a4b-a070-b7dbb2f6b303)

I'm not sure what the best mechanism would be to fix this within `flyctl` though. I would normally recommend using the `NO_COLOR` environment variable to alleviate such issues, but support for this was only [added in v2.3.7](https://github.com/go-survey/survey/releases/tag/v2.3.7) of `go-survey/survey` and `flyctl` doesn't [yet use that version](https://github.com/superfly/flyctl/blob/77e72de33a991c0a3b1f6e091f8a678d58437ac3/go.mod#L6C35-L6C41). There is a pull request that is awaiting merging to update this though: https://github.com/superfly/flyctl/pull/2585.

**Comment by tshu-w** [comment]
Thank you for your detailed response!

**Comment by dangra** [comment]
FYI https://github.com/superfly/flyctl/pull/2585 is merged

**Comment by usrme** [comment]
For the sake of tying things together, here is an earlier related issue on the matter: https://github.com/superfly/flyctl/issues/1831.

I've also found a potential way to resolve this directly in `flyctl` without having to turn off all colors nor waiting for an update to `go-survey/survey`.

**Comment by dangra** [comment]
Closed by #2691. kudos to @usrme
