### ISSUE TITLE
No ipv4 or ipv6 ip addresses allocated to app

### ISSUE THREAD

**Issue by ooddaa** [superfly/flyctl#2559]
**Describe the bug**
0. created a new postgres app with `flyctl postgres create`
1. all went well
2. `fly doctor -a my-db-app` gave me a warning (although every check is marked PASSED). 

```
fly doctor -a my-db-app                                                                                                
Testing authentication token... PASSED
Testing flyctl agent... PASSED
Testing local Docker instance... PASSED
Pinging WireGuard gateway (give us a sec)... PASSED

App specific checks for my-db-app:
Checking that app has ip addresses allocated... PASSED
Ip address fdaa:0:dd63:0:1::2 has unexpected type 'private_v6'. Please file a bug with this message at https://github.com/superfly/flyctl/issues/new?assignees=&labels=bug&template=flyctl-bug-report.md&title=No ipv4 or ipv6 ip addresses allocated to app my-db-app
Build checks for my-db-app:
Checking docker context size (this may take little bit)... PASSED (4.4 MB)
Checking for .dockerignore... PASSED
```

* MacOS Ventura 13.4.1 (22F82)
* fly v0.1.56 darwin/amd64 Commit: 7981f99ff550f66def5bbd9374db3d413310954f-dirty BuildDate: 2023-07-12T20:27:19Z

**Comment by matttpt** [comment]
Thanks for the report! It looks like `fly doctor` is confused because it hasn't been updated to recognize `private_v6` (i.e., [Flycast](https://fly.io/docs/reference/private-networking/#flycast-private-load-balancing)) addresses.
