### ISSUE TITLE
flyctl not responding to SIGINT 

### ISSUE THREAD

**Issue by paularah** [superfly/flyctl#2589]
**Describe the bug**
Briefly, describe what broke and provide the following details:

To reproduce this exact scenario, I deployed a misconfigured app with incorrect health checks, I  noticed the misconfiguration and made another deployment. While flyctl is waiting for the previous deployment to be healthy, flyctl stops reponsding to signals and essentially stays stuck.  

![image](https://github.com/superfly/flyctl/assets/37967706/35e7f040-1116-4029-b951-14f7b3fd16c7)

* Operating system 
* `fly version`:  flyctl v0.1.58 linux/amd64 Commit: 82ebecb2bf83647d20c0e11e51272418f40a9b2c BuildDate: 2023-07-14T18:46:46Z

**Comment by alichay** [comment]
this is one of those things where you get so used to it working like that that you forget it's wrong haha
thanks for reporting this! it's fixed in `v0.1.65` (not yet released) :)
