### ISSUE TITLE
Logs not working ...

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#261]
Hello,

Just wondered if anyone else was having the issue of logs not working e.g.

`flyctl --app [name] logs`

... does nothing. Normally it would tail the log. Or has the command changed?

Thanks.

**Comment by mrkurt** [comment]
Working on it! The logging API is a currently taking forever to respond, should be fixed shortly.

**Comment by gregmsanderson** [comment]
@mrkurt No problem, just wondered if it was at my end

**Comment by mrkurt** [comment]
All fixed!
