### ISSUE TITLE
Prompt for service port on flyctl init

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#265]
We have a fair amount of people run into health check errors because their app listens on not-8080. I think we might solve a lot of problems if we prompt for the app port at app init time.

**Comment by codepope** [comment]
The problem with prompting is that it would have to contextualise the question. Fundamentally, this is a question that users don't know exists. It could be phrased as...

"What port does your application use for incoming connections?"

But this would need to be caveated with "we will make ports 80/443 traffic go to that port when the app is deployed"

Which is getting quite long. 

As an aside...

I am wondering if when a health check fails, we could scan the apps ports and if there is an open port that doesn't match the internal port setting, warn the user that they may not have set the internal port correctly?

**Comment by codepope** [comment]
In 0.0.138 beta 8
