### ISSUE TITLE
Can't create app with existing fly.toml

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#267]
I tried to create a "staging" version of my app today, and couldn't do it with the fly.toml in place. `flyctl init` just bailed when I told it not to overwrite my config file.

If a config exists, I think it's safe to assume the builder/port are set and not ask those questions, but still create the app on Fly.

**Comment by codepope** [comment]
The problem there is subtle in that you could well be "forgetting" the existing app name doing that. That could in turn generate a soft buildup of forgotten apps.

Options:

"Do you want to destroy <current app> and import its settings into a new app?"

"Do you want to destroy <current app>?"

"Backing up fly.toml to appname.fly.toml"
+
"Importing from appname.fly.toml"
