### ISSUE TITLE
Usage: "flyctl logs" is wrong

### ISSUE THREAD

**Issue by hut8** [superfly/flyctl#2696]
**Describe the bug**

The CLI gives inaccurate advice.

`fly logs --help`:

```
View application logs as generated by the application running on
the Fly platform.

Logs can be filtered to a specific instance using the --instance/-i flag or
to all instances running in a specific region using the --region/-r flag.

Usage:
  flyctl logs [flags]
  flyctl logs [command]

Available Commands:
  dashboard   View and analyze logs in a web browser
  ship        Ship application logs to Logtail
  unship      Stop shipping application logs to Logtail

Flags:
  -a, --app string        Application name
  -c, --config string     Path to application configuration file
  -h, --help              help for logs
  -i, --instance string   Filter by instance ID
  -j, --json              JSON output
  -r, --region string     The target region (see 'flyctl platform regions')

Global Flags:
  -t, --access-token string   Fly API Access Token
      --verbose               Verbose output

Use "flyctl logs [command] --help" for more information about a command.
```

I want to open it in the browser, so this look right: `dashboard   View and analyze logs in a web browser`

Then I run: `fly logs --app [app-name] dashboard`

Then I get: `You haven't added a logging integration for the [org-name] organization. Set one up with 'flyctl logs shipper setup [org-name]'.`

That's fine. I'll just add one by following the instructions (`flyctl logs shipper setup [org-name]`):

```                                                                                                             
Usage:
  flyctl logs [flags]
  flyctl logs [command]

Available Commands:
  dashboard   View and analyze logs in a web browser
  ship        Ship application logs to Logtail
  unship      Stop shipping application logs to Logtail

Flags:
  -a, --app string        Application name
  -c, --config string     Path to application configuration file
  -h, --help              help for logs
  -i, --instance string   Filter by instance ID
  -j, --json              JSON output
  -r, --region string     The target region (see 'flyctl platform regions')

Global Flags:
  -t, --access-token string   Fly API Access Token
      --verbose               Verbose output

Use "flyctl logs [command] --help" for more information about a command.

Error: unknown command "shipper" for "flyctl logs"
```

* Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64 arm
* fly v0.1.77 darwin/arm64 Commit: c9880372b6bc9b3b4d3a0d0e1392c36f9b995dd9 BuildDate: 2023-08-11T19:00:31Z

** Paste your `fly.toml`

```toml
# I can perhaps post this upon request, but I'm working on a client project and most of it would need redaction for a public forum. It shouldn't be relevant.
```

** Command output: **

See above

**Comment by redjonzaci** [comment]
From what I understand, we should fix the error for the shipper command?

**Comment by redjonzaci** [comment]
5 months ago `fly logs` was updated, but the error wasn't.
With what I can see from the code, the `fly logs ship` command replaces `fly logs shipper setup [org-name]`
as it sets up Logtail logs.
What error did you have for `fly logs ship`?

Keep in mind I am not a Fly employee, but trying to help.

**Comment by redjonzaci** [comment]
Since this is a more generic error, hope a Fly employee gets to this soon. Sorry we couldn't get any closer to the solution.

**Comment by michaeldwan** [comment]
Sorry for the confusion! @jsierles are we still going forward with log shippers living under the `fly logs` command? Should these go under `fly ext` now?

**Comment by jsierles** [comment]
Right now we don't have a plan for shippers, so we should remove these commands from view until the project is revived.
