### ISSUE TITLE
[31mError[0m (Terminal coloring issues)

### ISSUE THREAD

**Issue by JeremyJaydan** [superfly/flyctl#27]
Seems there's some coloring issues with flyctl, not a big deal, worth noting.

I'm running `flyctl_0.0.74_Windows_x86_64.tar.gz`

![flyctl coloring issue](https://jcdn.io/fly-ctl-coloring-issue.png)

Something to do with the fmt go package, not sure. :)

**Comment by michaeldwan** [comment]
Looks like Windows 10 supports ANSI control characters but for whatever reason disables them by default. So `cmd.exe` is telling `flyctl` to send them but doesn't do anything with them. Here's an SO post with more info: https://superuser.com/a/1300251.

Good news is the new [Windows Terminal app](https://github.com/microsoft/terminal) correctly handles these codes and is overall pleasant to use :) 

Here's Terminal rendering the right output for Powershell, cmd, and wsl, so not much we can do for cmd.exe.
![Annotation 2020-01-23 161949](https://user-images.githubusercontent.com/5628/73031906-15376f80-3e03-11ea-9533-c6eecd85689f.png)
![Annotation 2020-01-23 1619492](https://user-images.githubusercontent.com/5628/73031920-241e2200-3e03-11ea-95f8-8fc2e13e0169.png)
![Annotation 2020-01-23 16194923](https://user-images.githubusercontent.com/5628/73031932-2e402080-3e03-11ea-9267-ef6d10398ce0.png)
