### ISSUE TITLE
Docker's 'optimizing image' stage taking ages. 45 mins+

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#271]
Hello,

Is this an issue with fly, or with docker?

Only the 'building fs ...' part of optimizing image has taken about 45 minutes?! It has been stuck for me on remote systems, like CI, and also when I do a deploy locally, so is the issue at fly's end with builds?

--> Done Pushing Image
==> Optimizing Image
--> Done Optimizing Image
==> Creating Release

It's just completed one, just now. So maybe it was an issue for the past couple of hours that has since been fixed? Just wondered if anybody else was having issues.

Thanks.

**Comment by gregmsanderson** [comment]
![Screenshot 2020-08-20 at 21 55 04](https://user-images.githubusercontent.com/10390169/90829212-3fb8bf00-e337-11ea-8cf6-57f3c30c1799.png)

... stuck on that 'building fs ...' line for a looong time ...

**Comment by codepope** [comment]
This appears to have been a transient issue in the backend. Closing.
