### ISSUE TITLE
failed to fetch an image or build from source: error building: failed to solve: rpc error: code = Canceled desc = grpc: the client connection is closing

### ISSUE THREAD

**Issue by alimurtaza026** [superfly/flyctl#2717]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
failed to fetch an image or build from source: error building: failed to solve: rpc error: code = Canceled desc = grpc: the client connection is closing

This issue is on MAC AIR M2 

* `fly version`
0.1.80
** Paste your `fly.toml`
# fly.toml app configuration file generated for youtubeapi on 2023-08-21T00:04:49+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtubeapi"
primary_region = "lhr"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

** Command output: **

failed to fetch an image or build from source: error building: failed to solve: rpc error: code = Canceled desc = grpc: the client connection is closing

**Comment by dangra** [comment]
@alimurtaza026 please report it to the community forum. There is a similar thread at https://community.fly.io/t/flyctl-deploy-not-working/14347/14

**Comment by Kevin-free** [comment]
@dangra  @alimurtaza026 I had this problem too, and the forum didn't actually address it.
It is recommended to downgrade on the fly, but will automatically upgrade.

```shell
> fly version
fly v0.1.84 darwin/arm64 Commit: 5735a8b979ebc938c74832c3edd52c509abaa7eb-dirty BuildDate: 2023-08-23T16:47:02Z
>
> fly settings autoupdate disable
Automatic updating: disabled
>
> curl -L https://fly.io/install.sh | sh -s -- v0.1.58
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
100 1735 0 1735 0 0 2225 0 --:--:-- --:--:-- --:--:-- 2250
#################################################### ######################## 100.0%
Automatically updating 0.1.58 -> 0.1.84.
Running automatic upgrade [curl -L "https://fly.io/install.sh" | sh]
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
100 1735 0 1735 0 0 1925 0 --:--:-- --:--:-- --:--:-- 1936
################### 25.2%
```

**Comment by alimurtaza026** [comment]
I use github action to deploy with ease

**Comment by Kevin-free** [comment]
> I use github action to deploy with ease

How do you do it? Can you provide a tutorial or a GitHub link

**Comment by alimurtaza026** [comment]
I will share tutorial with you on Monday
