### ISSUE TITLE
FLY_ORG is not respected by org-level commands

### ISSUE THREAD

**Issue by indirect** [superfly/flyctl#2757]
**Describe the bug**
Briefly, describe what broke and provide the following details:

Setting the FLY_ORG env var does not replace `-o` in org-level commands. According to @michaeldwan, this is a bug: https://community.fly.io/t/flyctl-feature-request-fly-org-env-var/15099/4.

* Operating system
* `fly version`
```
fly v0.1.83 darwin/arm64 Commit: 64d1ddb772751c502a038458af4f93fcc9d6a199-dirty BuildDate: 2023-08-22T21:14:46Z
```

** Command output: **

```text
❯ fly apps list -o personal
NAME            OWNER           STATUS          PLATFORM        LATEST DEPLOY        
twumblr         personal        deployed        machines        2023-05-26T01:47:41Z

❯ FLY_ORG=personal fly apps list
NAME                            OWNER           STATUS          PLATFORM        LATEST DEPLOY        
twumblr                         personal        deployed        machines        2023-05-26T01:47:41Z
feedyouremail                   feedyouremail   deployed        machines        2023-08-21T23:55:15Z
```

Expected results are for both commands to produce the same results, an org-filtered list of apps.

**Comment by redjonzaci** [comment]
@indirect do you only need it to work for `fly apps list`?

**Comment by indirect** [comment]
No. I want to use it with every single fly command that accepts a `-o / --organization` flag.

**Comment by redjonzaci** [comment]
I understand, thank you!

**Comment by redjonzaci** [comment]
I will try to make an initial implementation for `fly apps list` in the morning where the FLY_ORG env var takes priority.

I identified the following commands that use `org` argument or `--org` flag currently:
- `fly apps list`
- `fly dig`
- `fly ips allocate-v6`
- `fly machine api-proxy`
- `fly proxy`
- `fly ssh issue`
- `fly ssh log`
- `fly litefs-cloud`

**Comment by redjonzaci** [comment]
I did an initial implementation as fast as I could,
now we wait for a Fly employee to look at that or provide a better implementation. ☺️

**Comment by redjonzaci** [comment]
@indirect The solution for this is part of [v0.1.85-pre-1](https://github.com/superfly/flyctl/releases/tag/v0.1.85-pre-1) pre-release.
You can try it by [running the command for "the latest pre-release version"](https://github.com/superfly/flyctl/tree/v0.1.85-pre-1#macos-linux-wsl) (there doesn't seem to be an option for Windows?):
```
curl -L https://fly.io/install.sh | sh -s pre
```

I don't know how it makes it from a pre-release to a release, but thought to let you know!

**Comment by dangra** [comment]
thanks @indirect for the report and @redjonzaci for a well rounded fix!
