### ISSUE TITLE
Accept human-friendly memory & storage sizes

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#2769]
`fly scale memory` and friends accept input as a number in megabytes. The number needs to be divisible by 1024 if greater than 1GB, and 256 if less. This is only told to users through error messages. 

`fly volume create` and friends accept input as a number in gigabytes. I don't think it has similar restrictions. 

Instead of forcing users to do conversions, flyctl should accept human friendly sizes as strings. For example:

```
fly scale memory 512mb
fly scale memory 2gb
fly volume extend --size 20gb (or
```

It's out of scope, but that last one would be rad if it accepted `--size +10gb` as well ;)

**Comment by redjonzaci** [comment]
In the code block, did you finish your thought? "(or"

**Comment by redjonzaci** [comment]
I started looking into this, but if you are working on this yourself, I will skip it when I wake up.

**Comment by redjonzaci** [comment]
I added an initial implementation for the examples you mention.
Should I check for other commands that should behave this way?

**Comment by redjonzaci** [comment]
@michaeldwan we just merged my PR for this issue!
