### ISSUE TITLE
Cross-app cache purge

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#280]
Question about the redis cache:

Does the redis URL ever change, or is it assigned when the app is created?

Why I'm asking is I'd like an app 1 to be able to delete _another_ app 2's cache. App 1 can know the URL to app 2's redis (as I can extract it when it is created) and so armed with that, it could delete a key from it. I assume.

However of course that _wouldn't_ work if the assigned redis URL/user/password changed for app 2. As then the one app 1 had would be wrong.

**Comment by mrkurt** [comment]
The only time it'll change is if you delete the app or we destroy the credentials, which we'd only do at your request. You should be good to use it between apps.

Also, would you mind posting questions like this on https://community.fly.io? We're still getting organized, but the plan is to use these issues primarily for bug tracking.

**Comment by gregmsanderson** [comment]
Ok, great.

No problem. I wasn't sure about the best place. Makes sense.
