### ISSUE TITLE
certs check --json does not return valid json

### ISSUE THREAD

**Issue by amo13** [superfly/flyctl#2809]
`flyctl certs check host.tld --json` does not return valid json. The result starts with

```
The certificate for host.tld has been issued.

{
```

I guess the culprit is here:
https://github.com/superfly/flyctl/blob/64a31bf73c6e1509567cc6be0b2a19340e80e810/internal/command/certificates/root.go#L164
and should be wrapped in a check for the `--json` flag.

**Comment by redjonzaci** [comment]
Do you mean not to print that message, but just the JSON?
Would you like / do you have the time to submit a PR for that?

Note that I am not a Fly.io team member.

**Comment by amo13** [comment]
Yes, that is what I mean.
Unfortunately no, I don't really have the time to find my way around the flyctl code and create a PR... sorry

**Comment by redjonzaci** [comment]
Don't worry @amo13, I can do that for you now.

**Comment by redjonzaci** [comment]
Now we wait for a Fly.io team member.
