### ISSUE TITLE
Redis issues?

### ISSUE THREAD

**Issue by gregmsanderson** [superfly/flyctl#284]
Hello,

I've noticed a lot of these:

`cdg [info] 2020-09-02 20:03:13  error     Redis client error: Ready check failed: Redis connection lost and command aborted. It might have been processed. AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.`

For cdg and ams. It's from the Nodejs Redis client connection error handler.

The logs have stopped coming in so not sure if one or both are having issues? Last line was about 45 minutes ago.

**Comment by mrkurt** [comment]
That can happen when we deploy our proxy. It's best to enable retries for Redis (and disable that ready check). I'm guessing a deploy broke your connections right around then.

The service is actually fine, though, Node's Redis driver is not very robust and takes some tuning.

**Comment by gregmsanderson** [comment]
Ok, thanks.
