### ISSUE TITLE
Need a simple AlwaysHTTPS switch to redirect traffic to a https connection

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#291]
As I understand it, this would have to be a per certificate switch which when turned on, would redirect HTTP traffic for that certs domain to the HTTPS version.

"Can't you do it in the app?" - There may not be an app - for example, static sites use a server with no knowledge of how to do the redirection because they can't see the incoming headers. (Yes we could rewrite them but that gets more complex).

**Comment by mrkurt** [comment]
This probably can't be per certificate, but a global https redirect makes sense. Someone who wants specialized behavior can just shut it off.

**Comment by codepope** [comment]
Fixes for this issue so far - a now upstream flag for go-static web server which auto-promotes to https and associated article - https://fly.io/blog/always-be-connecting-with-https/
