### ISSUE TITLE
Feature request: Runtime environment variables

### ISSUE THREAD

**Issue by a-h** [superfly/flyctl#293]
I was trying out Fly today for the first time, and I couldn't see any way to set environment variables on the runtime application so that my Docker container could pick them up.

I read the docs here: https://fly.io/docs/reference/runtime-environment/

I worked around it with a custom Dockerfile that runs a `start.sh`, but it seems like a bit of a hack. Have I missed something?

```Dockerfile
FROM golang:1.14 as builder
WORKDIR /go/src/app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -v -o app
FROM alpine:latest  
COPY --from=builder /go/src/app/app /goapp/app
WORKDIR /goapp
COPY . /throwaway
RUN cp -r /throwaway/resources ./resources || echo "No resources to copy"
RUN rm -rf /throwaway
RUN apk --no-cache add ca-certificates
EXPOSE 1965
COPY start.sh /goapp/start.sh
CMD [ "sh", "/goapp/start.sh"]
```

The `start.sh` then looks like this:

```
HOST_NAME=xxxxxxxxx.fly.dev /goapp/app
```

It's that's not great, for running non-production accounts etc. because it's sort-of hard coded into the Dockerfile. 

`FLY_HOSTNAME` might also be a useful environment name to pass to all containers.

**Comment by mrkurt** [comment]
You can use `flyctl secrets` for this. The values are encrypted and only your VMs will be able to read them, but it works just fine. We'll likely add plaintext environment variables as well.

You can also just do `ENV HOST_NAME xxxxx.fly.dev` in your Dockerfile.

**Comment by codepope** [comment]
Currently, environment variables are best set through setting secrets on the application. See flyctl secrets. Each secret is exposed as an environment variable in the runtime.

**Comment by a-h** [comment]
Ah, great. I didn't expect that based on the name. If the `secrets` command was aliased as `environment` I would have found it easily.

`flyctl secrets set HOST_NAME=xxxxx.fly.dev` did the trick.

Thanks! Great tool.
