### ISSUE TITLE
Batch secret assignment from a file

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#3]

**Comment by juliaqiuxy** [comment]
`flyctl secrets set $(cat .env)` works just fine.

**Comment by juliaqiuxy** [comment]
> `flyctl secrets set $(cat .env)` works just fine.

I spoke too soon. That doesn't work e.g. when I put comments in .env file. DX-wise, would be best if the `flyctl` processed the .env file directly.

**Comment by michaeldwan** [comment]
Oh yeah good catch. It should be handled directly in flyctl

**Comment by mrkurt** [comment]
@juliaqiuxy This might work!

`cat .env | tr '\n' ' ' | xargs flyctl secrets set # set secrets`

We're working on env vars in config, using secrets for generic env vars is not great. :)

**Comment by juliaqiuxy** [comment]
@mrkurt Yeah, that's a good workaround. Thanks!

By config, do you mean `fly.toml`? It'd be great if there was a unified way of configuring all env variables including the secrets themselves. I understand there's overhead induced by encryption/decryption on your end but from DX point of view, storing all my env vars in secrets make it a much cleaner experience. 

Perhaps, something like:

```
$ flyctl env set SOME_VAR=my_var
$ flyctl env set SECRET_VAR=my_secret --secret
$ flyctl env list
  NAME                DIGEST           VALUE                    
  SOME_VAR            7dd0fdf1c9d      my_var                               
  SECRET_VAR          b3ac9394f47      🔒                                 
```

**Comment by codepope** [comment]
fly secrets import is now implemented for batch import through stdin. Format as name=value pairs, with """ (python style) quoting on values allowed for multiline values.
