### ISSUE TITLE
How to add Deno permissions (for example --allow-read) using the builtin Deno builder?

### ISSUE THREAD

**Issue by shybyte** [superfly/flyctl#300]
I have a Deno app which tries to serves static files and therefore needs the --allow-read.
By default the app seems only to get the --allow-net permission using the builtin Deno builder.
How can I configure more permissions?

**Comment by codepope** [comment]
I have a version in internal test which gives a range of argument settings, no date for release yet on that as there's some other external components which have to be updated to properly support the changes.

Until then, you can always save the Dockerfile from `fly builtins show deno` and adjust the permissions in the final CMD line, then remove the build section from `fly.toml` and fly deploy will use that Dockerfile.

**Comment by shybyte** [comment]
@codepope  Thank you for this hint. 
Meanwhile I had figured out on my own how to write a Dockerfile for Deno with the required permissions. Knowing about `fly builtins show deno` would have helped me a lot. 
Maybe it would be good to mention this "trick" on https://fly.io/docs/getting-started/deno/.
Or link directly to the docker file.

**Comment by codepope** [comment]
In prerelease now is a version of flyctl with "settings" - the Deno builder has a perms permission which can take an array of command line flags for the Deno command line, specifically so you can pass appropriate permissions flags. You can read about that in the Fly community site - https://community.fly.io/t/the-fly-beta-shop/113/22 and the prerelease is available to download now.

**Comment by codepope** [comment]
Closing as a solution is available.
