### ISSUE TITLE
Setup instructions for wildcard certs are missing _acme-validation step

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#308]
Wildcard certs need an `_acme-validation` DNS entry or we can't issue them. This is separate from actually pointing traffic at Fly. `flyctl` doesn't show those instructions when you create a new wildcard.

**Comment by mrkurt** [comment]
Incidentally, the UI does show these instructions. Perhaps we should move DNS/cert instructions to the API and just display them from there.

**Comment by codepope** [comment]
@kurt what are you doing to create a new wildcard with flyctl?

**Comment by mrkurt** [comment]
`flyctl certs create '*.example.com'`

**Comment by codepope** [comment]
I'll add in support.

**Comment by mrkurt** [comment]
Do you want the instructions in the API? This is what's in the UI, it would be pretty easy to keep those tweaks all in one place:
![image](https://user-images.githubusercontent.com/7724/94291019-a32ea180-ff20-11ea-845a-b48820436b8a.png)

**Comment by codepope** [comment]
If we can get instructions from the API for the next steps needed, that would simplify the code no end.

**Comment by codepope** [comment]
@mrkurt @michaeldwan any update on when the API will have this supported?

**Comment by michaeldwan** [comment]
@codepope I can add this today

**Comment by codepope** [comment]
Should be resolved in 145 prerel/release.
