### ISSUE TITLE
Org slugs for new users are huge

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#315]
Testing onboarding for new users for new flyctl commands I found that the new user had a long org slug...

❯ fly list orgs
      Short Name Full Name
dj-walker-morgan-5fe5eb96-f463-4e4e-8573-02304714be69 Dj Walker-Morgan

❯ fly orgs list
Name                 Slug                 Type
----                 ----                 ----
Dj Walker-Morgan     dj-walker-morgan-5fe5eb96-f463-4e4e-8573-02304714be69 PERSONAL

This is a slug that has been salted and a bit.

Now, the PERSONAL orgs will never be invited to so they should never be used in the command line, but the formatting of orgs lists does get messed up.

Options:
* Shorter unique personal slugs
* Never show personal slugs in listings (and use a "personal" entry for where slugs are used for filtering (eg fly apps list --org ....) so that it just defaults to the user's personal org slug.

**Comment by michaeldwan** [comment]
I think that only happens when there's a conflict, but a uuid is pretty dang gross. We do use personal org slugs on the command line for domains now, but I like your idea of making `"personal"` a special identifier. I'll wire that up this morning!

eg `flyctl domains register personal example.com`

**Comment by michaeldwan** [comment]
Personal orgs all have the slug "personal" now so this should be fixed.

**Comment by codepope** [comment]
Looks good and testing seems to show no obvious fires to address.
