### ISSUE TITLE
Support Go1.21.6

### ISSUE THREAD

**Issue by mboyea** [superfly/flyctl#3248]
**Describe the bug**
Right now, I failed to run the HEAD build with Go1.21.6 while trying to build flyctl on Arch Linux; the error is shown below:
```
package github.com/superfly/flyctl
	imports github.com/superfly/flyctl/internal/cli
	imports github.com/superfly/flyctl/internal/command/root
	imports github.com/superfly/flyctl/internal/command
	imports github.com/superfly/flyctl/internal/appconfig
	imports github.com/superfly/flyctl/flaps
	imports github.com/superfly/flyctl/agent
	imports github.com/superfly/flyctl/internal/wireguard
	imports github.com/superfly/flyctl/wg
	imports golang.zx2c4.com/wireguard/tun/netstack
	imports gvisor.dev/gvisor/pkg/bufferv2
	imports gvisor.dev/gvisor/pkg/atomicbitops
	imports gvisor.dev/gvisor/pkg/state
	imports gvisor.dev/gvisor/pkg/state/wire
	imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/mboyea/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/gohacks
make: *** [Makefile:12: build] Error 1
```
**Screenshot**
![image](https://github.com/termux/termux-packages/assets/68197922/d4973046-91a8-4b2a-acda-8c68b1702606)

**Relevant Issues**
https://github.com/superfly/flyctl/issues/2688

**Next Steps**
If someone can point me to an upstream issue (like those outlined in [this issue](https://github.com/termux/termux-packages/issues/17603)), I would be happy to take a look at fixing it, but I have not used Go packages before, so I do not know where to start at this time..

In the meantime I will try to compile with Go1.20 or wait for [Go1.22](https://lwn.net/Articles/961196/)

**Comment by dangra** [comment]
the AUR package is outdated, it is pointing to flyctl v0.1.27 which is extremely old. Consider installing https://aur.archlinux.org/packages/flyctl-bin which is kept up to date.

**Comment by mboyea** [comment]
@dangra Thank you for the help, apologies for my negligence.
