### ISSUE TITLE
Parallelize deletion of old machines in bluegreen deployments

### ISSUE THREAD

**Issue by gwuah** [superfly/flyctl#3328]
During bluegreen deployments, we delete the old machines (blue machines) sequentially. This adds up on large deployments with tons of machines.

We can massively reduce the deployment time by performing the delete operations in parallel. Originally flagged in this [internal](https://flyio.discourse.team/t/can-parallelized-machine-destroys-be-added-to-flyctl-for-bluegreen-deployments/4917) issue.

For anyone interested in picking this up, all the work has to be done [here](https://github.com/superfly/flyctl/blob/5a7fbba81e6f807841f9fe7056fcd863f600fe76/internal/command/deploy/strategy_bluegreen.go#L506)

**Comment by benbjohnson** [comment]
Fixed via https://github.com/superfly/flyctl/pull/3335
