### ISSUE TITLE
Generated Dockerfile for nuxtjs application point to a wrong entry point file by default

### ISSUE THREAD

**Issue by ElvisAns** [superfly/flyctl#3404]
**Describe the bug**
In a nuxtjs application, the entry point file is not `index.js` but `.output/server/index.mjs` . With 0 change to configurations, by running `fly launch`; the generated Dockerfile has `CMD [ "node", "index.js" ]` instead of  `CMD [ "node", ".output/server/index.mjs" ]` which craches the deployment

* Operating system : windows 11
* `fly version` :  0.2.25

**Comment by benbjohnson** [comment]
Thanks for the bug report. We have a scanner in the code that tries to detect the framework you're using and it looks like that scanner's [Dockerfile template](https://github.com/superfly/flyctl/blob/8185d9f62aa58d0b92140fa83ebb5e1af0602d6f/scanner/templates/nuxtjs/Dockerfile#L26) is correct so I wonder if it's not detecting that your app is Nuxt.js.

Do you have a `nuxt.config.ts` file in your project's root?

**Comment by benbjohnson** [comment]
@ElvisAns I'm closing this bug report and moving it to https://github.com/fly-apps/dockerfile-node/issues/54
