### ISSUE TITLE
Cannot use `fly secrets set` to override existing secret

### ISSUE THREAD

**Issue by bombillazo** [superfly/flyctl#3468]
**Describe the bug**

We use the Fly CLI during our CI/CD process to deploy and have the latest changes automatically updated. This include env variables, but with the CLI, using `secrets set` only sets values that do not exist and does not update existing values.

* Mac OS
* fly v0.2.38 darwin/arm64 Commit: 9e93899bc325070973a8b68d1924206c62a07d97-dirty BuildDate: 2024-04-18T16:20:06Z

**Comment by benbjohnson** [comment]
Thanks for reporting the issue, @bombillazo. I just tried this on one of my apps and I was able to update existing secrets:

```
$ fly secrets set FOO=bar
$ fly ssh console
9080560fd4e018:/# env | grep FOO
FOO=bar
```

then I disconnected and tried again:

```
$ fly secrets set FOO=baz
$ fly ssh console
9080560fd4e018:/# env | grep FOO
FOO=baz
```

Just to confirm, are you using the `--stage` flag on `fly secrets set`? What's the app name you're updating?

**Comment by bombillazo** [comment]
Is there a limit to how many variables we can set at once? we create the CLI command programmatically based on the env vars we need to update and pass them all at once.

**Comment by bombillazo** [comment]
Hmmm nevermind, you're right, I think what confused me was that the created date did not change when using the set command, but that makes sense since the CLI seems to know if the new value is the same as the old value and will simply ignore the update, but it is working after testing it with different values from the existing one.

I think this can be closed :)
