### ISSUE TITLE
Confusing docker error while running flyctl deploy

### ISSUE THREAD

**Issue by sosedoff** [superfly/flyctl#347]
Hi, im trying to build and deploy an example go app. Basically following your tutorial.

Run `fly init` then `fly deploy` and this is what im seeing:

```
Deploying winter-glade-5022
==> Validating App Configuration
--> Validating App Configuration done
Services
TCP 80/443 ⇢ 8080

Deploy source directory '/Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app'
Docker daemon available, performing local build...
==> Building with Dockerfile
Using Dockerfile Builder: /Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app/Dockerfile
[+] Building 0.2s (2/4)
 => [internal] load remote build context                                                                                         0.0s
 => copy /context /                                                                                                              0.1s
 => [internal] load metadata for docker.io/library/alpine:3.10                                                                   0.0s
 => [internal] load metadata for docker.io/library/golang:1.15                                                                   0.0s
Error failed to solve with frontend dockerfile.v0: failed to create LLB definition: no active sessions
```

I did add my own `Dockerfile` that i've successfully built locally.
Not sure what am i missing here.

**Comment by mrkurt** [comment]
That's interesting. Which version of docker are you running? And are you using a remote Docker daemon? 

As a workaround you can deploy an image you built with docker: `flyctl deploy -i <tagname>`

**Comment by sosedoff** [comment]
Oh yea sorry i forgot to include that info.

docker: `Docker version 20.10.0, build 7287ab3`
os: BigSur 11.1

So first i did not have docker running and `flyio` started to build the image remotely, which was hanging. I killed the command then deleted the app, created the app again and tried to build using local docker.

**Comment by sosedoff** [comment]
I removed the `build` section from the config since the docs say it will detect the dockerfile automatically.

**Comment by codepope** [comment]
Could you post your Dockerfile? The messaging from the build process looks a little odd. Thanks.

**Comment by sosedoff** [comment]
```
# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.15 AS build

WORKDIR /go/src/github.com/sosedoff/x/fly-test-app

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY . .

RUN \
  GOOS=linux \
  GOARCH=amd64 \
  go build -o app

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS release

WORKDIR /app

COPY --from=build \
  /go/src/github.com/sosedoff/x/fly-test-app/app \
  /app

EXPOSE 8080
```

**Comment by mrkurt** [comment]
Since the remote build also hung, I think there's something weird going on with our context bundling and that GOPATH. Do you have any symlinks in the directory you're working from by chance?

I haven't been able to replicate this yet, though. If you have more time to spend will you run `LOG_LEVEL=debug flyctl deploy` and show us what you see? You can try with `--remote-only` too.

**Comment by codepope** [comment]
> I removed the `build` section from the config since the docs say it will detect the dockerfile automatically.

Ah, yes, you'd be running a buildpack called Dockerfile (or whatever reference you had as the builder reference) and it would go on its own quest to identify the directory and run a build appropriate to what it found. If you still have your old fly.toml file and the [build] section, I'd like to have a look at it.

Anyway, I've recreated your setup here with the hellofly app and, first up, your Dockerfile lacks a CMD so it would exit straight away (running locally would drop you into a shell). Secondly, the app may not be runnable dues to a quick of Go and Alpine, so  that you need to add CGO_ENABLED=0 to your Go Build line to make a working binary for alpine.

If you could give us the latest output from fly deploy, that would help move this along.

**Comment by sosedoff** [comment]
Yeah i realized my docker file was not working as expected due to CGO stuff you've pointed out, i copied it over from another project. And the missing CMD was a copy-paste artifact :) 

The updated docker file that works:

```dockerfile
# ------------------------------------------------------------------------------
# Builder Image
# ------------------------------------------------------------------------------
FROM golang:1.15 AS build

WORKDIR /go/src/github.com/sosedoff/x/fly-test-app

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY . .

RUN \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64 \
  go build -o app

# ------------------------------------------------------------------------------
# Target Image
# ------------------------------------------------------------------------------
FROM alpine:3.10 AS release

COPY --from=build \
  /go/src/github.com/sosedoff/x/fly-test-app/app \
  /app

EXPOSE 8080

CMD ["/app"]
```

I removed the config again, and ran the same steps you outline in the example repo, with debug level:

```
~/go/src/github.com/sosedoff/x/fly-test-app$ LOG_LEVEL=debug flyctl deploy
DEBUG Loaded flyctl config from/Users/sosedoff/.fly/config.yml
DEBUG Loading app config from/Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app/fly.toml
DEBUG Working Directory: /Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app
DEBUG App Config File: /Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app/fly.toml
Deploying snowy-snowflake-2412
==> Validating App Configuration
DEBUG --> POST https://api.fly.io/graphql {{"query":"query($appName: String!, $definition: JSON!) { app(name: $appName) { parseConfig(definition: $definition) { definition valid errors services { description } } } }","variables":{"appName":"snowy-snowflake-2412","definition":{"services":[{"concurrency":{"hard_limit":25,"soft_limit":20},"internal_port":8080,"ports":[{"handlers":["http"],"port":"80"},{"handlers":["tls","http"],"port":"443"}],"protocol":"tcp","tcp_checks":[{"interval":10000,"timeout":2000}]}]}}}
}
DEBUG <-- 200 https://api.fly.io/graphql (265ms)
--> Validating App Configuration done
Services
TCP 80/443 ⇢ 8080

Deploy source directory '/Users/sosedoff/go/src/github.com/sosedoff/x/fly-test-app'
Docker daemon available, performing local build...
==> Building with Builtin
Using Builtin Builder: go
[+] Building 0.2s (2/4)
 => [internal] load remote build context                                                                                                                                                                0.0s
 => copy /context /                                                                                                                                                                                     0.1s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                                        0.1s
 => [internal] load metadata for docker.io/library/golang:1.14                                                                                                                                          0.1s
Error failed to solve with frontend dockerfile.v0: failed to create LLB definition: no active sessions
```

Afaik i dont have any special setup on my machine, so no symlinks or anything. Im using standard a GOPATH too.

**Comment by codepope** [comment]
Ok, one thing I just want to check is your current flyctl because that output you are showing seems to be saying you are using the builtin go builder (which would ignore your Dockerfile).

**Comment by michaeldwan** [comment]
@sosedoff this is likely related to buildkit changes in a recent docker upgrade. Try running this to see if it works:

```bash
DOCKER_BUILDKIT=0 flyctl deploy
```

**Comment by sosedoff** [comment]
That was it, its running fine now. 
I did upgrade docker a few days ago so had no chance to test out any other projects.

**Comment by michaeldwan** [comment]
Glad to hear. Seems like we need a fix on our end.

**Comment by michaeldwan** [comment]
Looks like Docker Desktop 3.0.3 fixes this on macOS
