### ISSUE TITLE
flyctl deploy fails with `operation not permitted: /tmp/<number>/.cache` on WSL

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#350]
`docker build .` works fine, though, and so does `flyctl deploy -i <tag>`.

**Comment by jassmith** [comment]
WSL 2, fully up to date. My soul is dead and my day is ruined.

**Comment by codepope** [comment]
Could I ask, which distro is running under WSL2?

**Comment by jassmith** [comment]
Ubuntu

**Comment by jassmith** [comment]
Builds still fail, sorry for delay

**Comment by mrkurt** [comment]
I'm 99% sure this is fixed. If it's not, will you reopen this?

**Comment by jassmith** [comment]
Yes fixed :)
