### ISSUE TITLE
fly deploy -r changes primary region

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#3509]
We have an app running machines in three regions: iad, sea, syd. The primary region is iad. We ran `fly deploy -r sea` today, and the release included `primary_region = "sea"`.

It only updated the machine in sea before failing, and that meant that some machines thought iad was the primary region while the one that got updated thought sea was the primary region. That caused issues for our services, and was a surprising side effect of using `-r`.

Maybe we change `-r` to be an alias for `--only-regions` to make it less confusing?

**Comment by tvdfly** [comment]
We had a similar issue ~9months ago, and I added the `--only-regions` flag at that time. https://github.com/superfly/flyctl/commit/1bdedefef34dfe45da88a706fd22f42597586411

**Comment by benbjohnson** [comment]
@tvdfly I think my preference would be to remove the shorthand `-r` flag entirely. I also think we should rename `--region` to `--set-region`.

Another option would be to alias `-r` and `--region` to `--only-regions` and change the existing `--region` to something more explicit like `--set-region`.

**Comment by tvdfly** [comment]
@benbjohnson any of those sound good to me! I think changing primary region based on a flag is surprising behavior, and that's the main issue we've run into.
