### ISSUE TITLE
App size

### ISSUE THREAD

**Issue by capriciousduck** [superfly/flyctl#355]
How do I deploy a 1GB VM by default? It normally deploys a 512Mb RAM instance, but how do I deploy a 1GB VM instead?

**Comment by codepope** [comment]
Hi, you can set the vmsize before first deployment, after you've init'd the applications. just use `fly scale vm ...` to set the size of cpu and memory you want. The setting is retained by the app.

**Comment by capriciousduck** [comment]
How do I set the vm to 1GB?

What command do I use?

`fly scale vm 1GB`?

**Comment by codepope** [comment]
There's two parts to the scale command, the type of machine you want and the amount of memory. So the get a "shared-cpu-1x" machine (see `show platform vm-sizes` for the machine types) with 1GB of RAM, you would run:

```
fly scale vm shared-cpu-1x --memory 1024
❯ fly scale vm shared-cpu-1x --memory 1024
Scaled VM size to shared-cpu-1x
      CPU Cores: 1
         Memory: 1 GB
```

And then you are ready to deploy.
