### ISSUE TITLE
How to perform sign-in using flycli on a headless server?

### ISSUE THREAD

**Issue by HouzuoGuo** [superfly/flyctl#359]
Hello! I'd like to give fly.io a try, first I installed flycli on a headless server but got stuck at sign-in. I think the CLI tool would like to open up a browser window, which of course doesn't work on a headless server.

Is there a way to perform sign-in on a headless server? Thanks.

![image](https://user-images.githubusercontent.com/563872/105636712-3f869780-5e72-11eb-91d9-e36f4fbcda1d.png)

**Comment by HouzuoGuo** [comment]
nevermind, found it just now:
![image](https://user-images.githubusercontent.com/563872/105636762-76f54400-5e72-11eb-8bbe-32a60dc21bf2.png)

**Comment by mrkurt** [comment]
You can also do this with an auto token. If you run `flyctl auth token` it will output a token you can use on headless setups by setting an environment variable: https://fly.io/docs/flyctl/integrating/#environment-variables

**Comment by codepope** [comment]
Interesting - this should fail if there's no browser available (xdg-open would return an error) - and when it fails it emits a URL that can be used on another system to autorise the client. What's the headless system running as I'd like to track that down. 

 I can see you have found the other ways of logging in your client too.

**Comment by jleedev** [comment]
On a machine with w3m installed, xdg-open will silently succeed, and this would be indistinguishable from opening a page in a GUI browser and then returning.

```
¶ xdg-open https://example.com >&- 
¶ echo $?
0
```

I can trick it into failing by setting BROWSER appropriately:

```
¶ BROWSER=false xdg-open https://example.com 
xdg-open: no method available for opening 'https://example.com'
¶ echo $?
3
```

and then flyctl says "Error opening browser." and shows me the URL.
