### ISSUE TITLE
flyctl command line fails to deploy application due to an authentication error with image registry

### ISSUE THREAD

**Issue by HouzuoGuo** [superfly/flyctl#362]
Hey! Yesterday I was able to deploy this app without any problem, but then this started to happen since about an hour ago:

<pre>
root@ip-10-12-2-77 /hg (master)# fly auth whoami
Current user: guohouzuo@gmail.com
root@ip-10-12-2-77 /hg (master)# fly --app laitos deploy .
Deploying laitos
==> Validating App Configuration
--> Validating App Configuration done
Services
TCP 80/443 ⇢ 80

Deploy source directory '/hg'
==> Building with Dockerfile
Using Dockerfile Builder: /hg/Dockerfile
Step 1/9 : FROM ubuntu:20.04
 ---> f63181f19b2f
Step 2/9 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 05a2c3dd84cc
Step 3/9 : WORKDIR /
 ---> Using cache
 ---> eca430a5b0e7
Step 4/9 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> d3b31a3bd6e4
Step 5/9 : RUN apt update && apt upgrade -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite && apt install -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite bind9-dnsutils busybox ca-certificates curl iputils-ping lftp net-tools netcat-openbsd socat wget
 ---> Using cache
 ---> d423f61f698a
Step 6/9 : COPY ./bin/laitos.linux /laitos.linux
 ---> Using cache
 ---> 821a98827e3a
Step 7/9 : COPY ./data /laitos-data
 ---> Using cache
 ---> 3fcb78b3441f
Step 8/9 : WORKDIR /laitos-data
 ---> Using cache
 ---> 5cda1157135c
Step 9/9 : CMD /laitos.linux -awsinteg -disableconflicts -gomaxprocs 8 -config config.json -daemons autounlock,dnsd,httpd,insecurehttpd,maintenance,phonehome,plainsocket,simpleipsvcd,smtpd,snmpd,sockd,telegram -pwdserver -pwdserverport 80 -pwdserverurl /whoisthecoolestkid
 ---> Using cache
 ---> 5ded06ba39dd
Successfully built 5ded06ba39dd
Successfully tagged registry.fly.io/laitos:deployment-1612429698
--> Building with Dockerfile done
Image: registry.fly.io/laitos:deployment-1612429698
Image size: 289 MB
==> Pushing Image
The push refers to repository [registry.fly.io/laitos]
8402e5013945: Preparing
2dcba8328469: Preparing
44dfc4f98fff: Preparing
02473afd360b: Preparing
dbf2c0f42a39: Preparing
9f32931c9d28: Waiting
Error unauthorized: not allowed
root@ip-10-12-2-77 /hg (master) [1]#
</pre>

This is the content of `fly.toml`:

<pre>
# fly.toml file generated for laitos on 2021-01-24T16:35:35Z

app = "laitos"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
</pre>

**Comment by backflip** [comment]
I'm experiencing the same error when attempting to upload a local image I was successfully deploying yesterday.

**Comment by backflip** [comment]
Corresponding topic on Discourse: https://community.fly.io/t/registry-unauthorized-errors/693

**Comment by HouzuoGuo** [comment]
looks all good now :) thanks Jerome for the fix!

**Comment by jeromegn** [comment]
Postmortem: https://status.flyio.net/incidents/ljdhdp2q43hw

**Comment by HouzuoGuo** [comment]
@jeromegn  heh.. did fly.io just go down?
