### ISSUE TITLE
Hugo version is fixed

### ISSUE THREAD

**Issue by fu-sen** [superfly/flyctl#363]
[flyctl/builtinsupport/defaultbuiltins.go](https://github.com/superfly/flyctl/blob/master/builtinsupport/defaultbuiltins.go) :
```
CMD ["-port","8080"{{if .httpsonly}},"-https-promote"{{ end }}{{if .log}},"-enable-logging"{{end}}]
	`, Settings: []Setting{{"httpsonly", false, "Enable http to https promotion"}, {"log", false, "Enable basic logging"}}},
	{Name: "hugo-static"
		Description: "Hugo static build with web server builtin",
		Details:     `Hugo static build, then all public files are copied to the image and served, except files with executable permission set. Uses and exposes port 8080 internally.`,
		Template: `FROM klakegg/hugo:0.74.0-onbuild AS hugo
FROM pierrezemb/gostatic
COPY --from=hugo /target /srv/http/
```

Why is it fixed at **Hugo 0.74.0** ? [Hugo](https://github.com/gohugoio/hugo) is currently [**Hugo 0.80.0**](https://github.com/gohugoio/hugo/releases) at the time of issuing this issue.
It's getting older and can cause future build failures.

**Comment by fu-sen** [comment]
The Hugo version was already fixed in this article:
https://fly.io/blog/hugo-s-there-flying-with-hugo-and-caddy/

As a workaround: **Dockerfile** when using the latest Hugo:
```
FROM klakegg/hugo:onbuild AS hugo
FROM caddy:alpine
COPY --from=hugo /target/ /usr/share/caddy/
```
This port number starts at **80**

**Comment by mrkurt** [comment]
We are deprecating these builtins, this Dockerfile is a good way to do hugo! We plan to have a static site buildpack to make all this magical someday, but we haven't started on it yet.

**Comment by fu-sen** [comment]
If it is deprecated, it should be removed from the list. That means aggravation of flyctl and Fly. And you guys have left it for a while.
