### ISSUE TITLE
Auth token inconsistent syntax

### ISSUE THREAD

**Issue by Haarolean** [superfly/flyctl#3666]
To create a token I have to do this:
`flyctl tokens create org --org <orgname>`

But with the same syntax can't list them, as `--org` is not supported here for some reason:
```
$ fly tokens list org --org zoopets
Error: unknown flag: --org
```

To list them I have to use another obscure flag `-s`:
```
fly tokens list -s org
```

Then, `-s` is not supported for `fly tokens revoke`:
```
$ fly tokens revoke -s org

Error: unknown shorthand flag: 's' in -s
```

Also, `fly tokens revoke` is missing an interactive token selector, so one has to copy-paste the id.

**Comment by Haarolean** [comment]
Also, `fly logs` accepts machine id via `-i` or `--instance`, but in other places it's `-m` or `--machine`.

`fly ssh console -h`:
`      --machine string         Run the console in the existing machine with the specified ID`

`fly logs -h`:
`  -i, --instance string   Filter by instance ID`

**Comment by KTanAug21** [comment]
Hello @Haarolean! Thank you for reporting the inconsistencies you found above.

Let me address the three topics I can identify above:
**1. Inconsistent flags used for `flyctl tokens list` and `flyctl tokens create`, for identifying the organization name:**
- Changes has been made to provide a flag that can be consistently used across the two commands: `--org`, [see PR here](https://github.com/superfly/flyctl/pull/3799). So, you can now use the `--org` flag across both commands: 
   - `flyctl tokens create org --org <org_name>` is still available
   - `flyctl tokens list --org <org_name>` is now possible

**2. Unavailability of `--scope` flag for `flyctl tokens revoke`:**
- For context, the `--scope` flag is used as a filtering mechanism for listing tokens by `flyctl tokens list`, identifying whether tokens are filtered for an app, or an organization. 
- On the other hand, `flyctl tokens revoke` does not have the functionality of listing tokens, nor does it have an interactive way of selecting tokens, thus was not given the ability of reading the `--scope` flag.

**3. Inconsistent flag used for identifying a machine ID**
- We will treat the `--machine` flag as the primary flag for identifying a machine id, but assign `--instance` as an alias to it, to provide backwards compatibility with any existing usage of the `--instance`.
- [A PR](https://github.com/superfly/flyctl/pull/3820) has been created to address this!

**Comment by Haarolean** [comment]
@KTanAug21 thanks much!

fyi #3665 might be related to org selection, and #3664 related to having an interactive selector for nuking multiple instance of a resource

**Comment by KTanAug21** [comment]
The PR's [1( --org inconsistency )](https://github.com/superfly/flyctl/pull/3799), and [2( --instance vs --machine )](https://github.com/superfly/flyctl/pull/3820), has been merged! The changes should be available in the next available release for `flyctl`.
