### ISSUE TITLE
Node builtin looking for app/server.js

### ISSUE THREAD

**Issue by PierBover** [superfly/flyctl#367]
I followed [the tutorial here](https://fly.io/docs/getting-started/node/) and assumed `npm run start` would be used to start the server but I get this error when deploying to Fly:

`Error: Cannot find module '/app/server.js'`

Is this hardcoded somehow?

I looked at configuring that on the `fly.toml` but I don't see any options to do that.

**Comment by michaeldwan** [comment]
@PierBover the latest version of flyctl (0.0.178, released a few minutes ago) has a new `launch` command we're testing out which walks you through deploying a new app. It'll soon replace the `init` command and use buildpacks instead of builtins. Could you upgrade and try again with this:

```
flyctl launch --path hellonode-builtin/or/whatever
```

**Comment by PierBover** [comment]
Woah that was fast :)

I've tried `launch` a couple of times but it seems to get stuck at multiple points.

Here's the latest log: https://gist.github.com/PierBover/e07c6f1943cd15121ccecb77122fc251

**Comment by michaeldwan** [comment]
@PierBover remote builds are taking a _long_ time with this, I think we might need to use larger VMs for them. I also found a race condition when creating a new app and kicking off the remote build, I'll let you know when it's fixed.

**Comment by mrkurt** [comment]
I think the buildpack is working better these days, if you run into issues with the buildpack will you open this issue (or another issue)?

We are deprecating the builtins, they are not as powerful as buildpacks and we intend to speed buildpacks up quite a bit.

**Comment by PierBover** [comment]
>  if you run into issues with the buildpack will you open this issue (or another issue)?

Will do!
