### ISSUE TITLE
Version 0.2.73 is missing binaries

### ISSUE THREAD

**Issue by nicholasdille** [superfly/flyctl#3681]
**Describe the bug**
Contrary to previous releases, version 0.2.73 does not offer any release binaries.

**Comment by ricardbejarano** [comment]
I think it has to do with #3657?

**Comment by dangra** [comment]
Hopefully that was fixed by @billyb2, at least 0.2.80 has the binaries now https://github.com/superfly/flyctl/releases/tag/v0.2.80
