### ISSUE TITLE
`-q/--quiet` flag for `fly apps list`

### ISSUE THREAD

**Issue by fliepeltje** [superfly/flyctl#3683]
From a UX perspective, it'd make sense to have the `-q` flag available when listing apps to allow for easier destruction of short-lived apps.  

Basically the equivalent of `fly m list -q` for apps :)

**Comment by yfenes** [comment]
Hey @fliepeltje, 

I've applied to Fly via email. And proactively created the PR #3712 for visibility. 
Could you please let me know who I should contact regarding my application?

(just wanted to reach out here in a closed issue to avoid interrupting any ongoing discussions.)
