### ISSUE TITLE
Set secrets without deploy

### ISSUE THREAD

**Issue by natew** [superfly/flyctl#371]
A small helper for CI, being able to flyctl secrets set --skip-deploy would give a bit more control to scripts.

**Comment by mrkurt** [comment]
The plumbing for this is partially there. We're going to eventually let you stage a deploy, so you can set secrets, config, and image. Then "commit" it when you're ready.

**Comment by jsierles** [comment]
Staging secrets for the machines platform was done in #1126. The machines platform will become the default platform, so this behavior will likely not be backported.
