### ISSUE TITLE
`fly version upgrade` not working

### ISSUE THREAD

**Issue by fliepeltje** [superfly/flyctl#3716]
**Describe the bug**
I try to upgrade `flyctl` using `fly version upgrade` and the upgrade claims to be at the latest version when it is in fact not.
The same happens for `brew upgrade`

* Operating system: PopOS
* `fly version`: v0.2.72

**Command output:**

```sh
ᐅ fly version upgrade
Already running latest flyctl v0.2.72
```

**Comment by claytongentry** [comment]
@fliepeltje I was able to work around this this with brew uninstall <> brew reinstall.

**Comment by fliepeltje** [comment]
in the end it seems this is a brew issue; closing this!
