### ISSUE TITLE
Unable to install via Powershell

### ISSUE THREAD

**Issue by therinz** [superfly/flyctl#372]
I tried installing fly.io using PowerShell with the command specified on the website, but unfortunately it throws me an error. Just in case I also tried with `-useBasicParsing` and I'm running the ISE with admin privileges. Is there any other way to install, or can I amend the command to get it working through PS?
``` 
PS C:\Users\***\.fly\bin> iwr https://fly.io/install.ps1 | iex
https://github.com/superfly/flyctl/releases/download/v0.0.186/flyctl_0.0.186_Windows_x86_64.tar.gz
tar : x flyctl.exe
At line:94 char:1
+ tar -xvzf $FlyZip
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (x flyctl.exe:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by fu-sen** [comment]
I guess from this folder you were working fine before reporting this issue:

> PS C:\Users\***\.fly\bin> iwr https://fly.io/install.ps1 | iex

Release has a Windows executable:
https://github.com/superfly/flyctl/releases

Change this .exe file to `flyctl.exe` and put it in the` bin` folder. You can expect it to work.
But I've been having deployment issues for a few days. Also try older releases of `flyctl.exe`.

**Comment by mrkurt** [comment]
We should probably switch the windows build to a zip so we don't need to call another executable.

**Comment by michaeldwan** [comment]
This should be fixed now.

**Comment by therinz** [comment]
The `iwr https://fly.io/install.ps1 | iex` script now worked.
