### ISSUE TITLE
Flyctl is not working on Windows (v0.0.185+)

### ISSUE THREAD

**Issue by fu-sen** [superfly/flyctl#376]
`flyctl.exe` is not working on Windows in recent releases (v0.0.185+).:

```
PS C:\Users\balloon> iwr https://fly.io/install.ps1 | iex                                                               https://github.com/superfly/flyctl/releases/download/v0.0.188/flyctl_0.0.188_Windows_x86_64.tar.gz
x flyctl.exe
Flyctl was installed successfully to C:\Users\balloon\.fly\bin\flyctl.exe
Run 'flyctl --help' to get started
PS C:\Users\balloon> flyctl --help
panic: Error loading wintun.dll DLL: Unable to load library: The specified module could not be found.

goroutine 1 [running]:
golang.zx2c4.com/wireguard/tun/wintun.(*lazyProc).Addr(...)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.20201118/tun/wintun/dll_windows.go:56
golang.zx2c4.com/wireguard/tun/wintun.init()
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.20201118/tun/wintun/session_windows.go:33 +0xad3
PS C:\Users\balloon> ▄
```

v0.0.182 is working.

**Comment by LeCodeCo** [comment]
I can also replicate this issue. I installed using a non-administrator PowerShell window.

Here's my Windows version:
> Edition	Windows 10 Home
> Version	20H2
> Installed on	‎13/‎03/‎2021
> OS build	19042.867
> Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by Faleij** [comment]
A fix to run the latest release is to download wintun.dll from [https://www.wintun.net/](https://www.wintun.net/) and place it in `%homepath%\.fly\bin`
The wintun dll should be added to the release archive.

**Comment by michaeldwan** [comment]
I was just about to paste that same link. We'll get this fixed asap.

**Comment by fu-sen** [comment]
I have confirmed that flyctl has been included in [Scoop](https://github.com/lukesampson/scoop) since 2020:

https://github.com/lukesampson/scoop-extras/tree/master/bucket
https://github.com/lukesampson/scoop-extras/blob/master/bucket/flyctl.json

Some people mentioned it in the [community](https://community.fly.io/t/do-you-use-fly-on-windows-10/258/11).

```
> scoop bucket add extras
> scoop install flyctl
> fly --help
```

Usually there is a `scoop` folder in the user folder. Therefore:

`~\scoop\apps\flyctl\VERSION `

There should be flyctl.exe in.

```
PS C:\Users\balloon> dir ~\scoop\apps\flyctl\0.0.189


    ディレクトリ: C:\Users\balloon\scoop\apps\flyctl\0.0.189


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2021/03/16      8:12       37146112 flyctl.exe
-a----        2021/03/18     10:04             60 install.json
-a----        2021/03/16      9:45            848 manifest.json
-a----        2021/02/25     12:49         564856 wintun.dll


PS C:\Users\balloon>▄
```
ディレクトリ = directory

Include `wintun.dll` here. This can be avoided even with Scoop.

**Comment by fu-sen** [comment]
Flyctl has released v0.0.190, but this issue continues. 😫
v0.0.191 has been unpublished and will be updated later.

**Comment by michaeldwan** [comment]
We're still working on this, I'm sorry for the trouble

**Comment by fu-sen** [comment]
If you are using Scoop and you get an error during installation:
```
> scoop install flyctl@0.0.190
```
In this case, install `wintun.dll` according to the above procedure, or
```
> scoop install flyctl@0.0.182
```

**Comment by fu-sen** [comment]
Thank you for the repair. 😄
I have seen improvements with Flyctl 0.0.193.

If you were using Scoop, this is an easy way to get the latest version:
```
> scoop uninstall flyctl
> scoop install flyctl
```
