### ISSUE TITLE
flyctl deploy fails when used with Apple Silicon version of Docker

### ISSUE THREAD

**Issue by tobi** [superfly/flyctl#378]
If you use the Apple Silicon build of Docker (which just hit rc) you end up sending ARM based layers to fly.io which doesn't work very well. Solution for now is to use `flyctl deploy --remote-only`

**Comment by michaeldwan** [comment]
Good catch. We set the platform to amd64 for docker v1 builds, but I missed a spot when using buildkit. We'll have a fix today or tomorrow. In the meantime, you can use `DOCKER_BUILDKIT=0 flyctl ...` if you want to build locally.

**Comment by michaeldwan** [comment]
Latest version has all the M1 issues fixed up.
