### ISSUE TITLE
Build without deploy

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#386]
I'd like to be able to build Fly apps without deploying them. This would be useful for buildpack dev, and _also_ let us promote this tool as a very-nice-way-to-convert-apps-to-docker-images.

**Comment by michaeldwan** [comment]
There's a hidden (for some reason) flag on deploy that does this. `flyctl deploy --build-only`. I want to unhide it, but I think a `flyctl build` command is better.

**Comment by mrkurt** [comment]
Oh nice! That's useful for now.

**Comment by jsierles** [comment]
Now `--build-only` is exposed, closing this. We can open a new ticket for `fly build` as needed.
