### ISSUE TITLE
"create ssh certificate: issue_certificate failed: no root key established" with flyctl ssh - didn't tell me what to do next

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#390]
I tried `flyctl ssh` for the first time and got:

> create ssh certificate: issue_certificate failed: no root key established

It looks like the fix was to first run `flyctl ssh establish` - but the error message didn't tell me to do that.

It would be great if the error message here could suggest the fix.

**Comment by tqbf** [comment]
Yep, 100%. Thanks, I'll fix that right now.
