### ISSUE TITLE
Push latest package (docker image) to Github

### ISSUE THREAD

**Issue by tmaier** [superfly/flyctl#3924]
Current release is v0.2.126.

However, at https://github.com/superfly/flyctl/pkgs/container/flyctl, I can just see [v0.2.72](https://github.com/orgs/superfly/packages/container/flyctl/231935994?tag=v0.2.72).
On https://hub.docker.com/r/flyio/flyctl/tags, I can see [v0.2.93](https://hub.docker.com/layers/flyio/flyctl/v0.2.93/images/sha256-75ab1436c391b17b69193bd039a85f4be3175044012351dda1e55d4f0e33c554?context=explore).

Both of them are out of date.
It would be great to get the latest version as docker image. It would be also great to have this automated on each release.

**Comment by dangra** [comment]
@tmaier thanks for the report. v0.3.22 should be live on both registries now, @clouvet took take of it 👏
