### ISSUE TITLE
Install by version number is broken

### ISSUE THREAD

**Issue by mtlynch** [superfly/flyctl#394]
**Describe the bug**

Commit b217e0c356eeed538a5bf1221c640c3fbfac53dd seems to have broken install by version functionality:

```bash
$ curl -L https://fly.io/install.sh | sh -s 0.0.200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1411    0  1411    0     0  29395      0 --:--:-- --:--:-- --:--:-- 29395
######################################################################## 100.0%

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The root cause is that the Fly API gives inconsistent results depending on the version specifier. When the version is `latest`, it includes the `.tar.gz` extension, but when it's a specific version number, it points to binaries:

```bash
curl -s https://api.fly.io/app/flyctl_releases/Linux/x86_64/latest
https://github.com/superfly/flyctl/releases/download/v0.0.204/flyctl_0.0.204_Linux_x86_64.tar.gz
```

```bash
curl -s https://api.fly.io/app/flyctl_releases/Linux/x86_64/0.0.200
https://github.com/superfly/flyctl/releases/download/v0.0.200/flyctl_0.0.200_Linux_x86_64
```

**Comment by michaeldwan** [comment]
This isn't an issue after v0.0.202 when we stopped shipping standalone binaries due to [this](https://github.com/superfly/flyctl/issues/376). Prior to that release binaries would sometimes get picked up depending on the order GitHub returned them. There's a fix being deployed to ignore binaries so this won't be an issue, but you shouldn't use versions too far behind latest anyway since our api is changing quickly.

**Comment by mtlynch** [comment]
How quickly do flyctl versions become obsolete?

In general, I prefer to pin all my dependencies to explicit versions. Otherwise, if something breaks, it's hard to tell if it was due to a change I made or if one of my dependencies changed out from under me.

**Comment by mrkurt** [comment]
Right now, very quickly. They're heavily coupled to our API/backend so pinning to a specific client version is only somewhat effective.

This should settle down in a few weeks. It's extra tweaky right now because we're refactoring a lot of our build/deploy process.

**Comment by mtlynch** [comment]
Okay, gotcha. I'll change my CI to always use the latest, but it'd be good if I could pin it to a version in the future.

**Comment by mrkurt** [comment]
@mtlynch one thing you can do now, if you run `flyctl deploy --local-only` with CircleCI it'll bypass a lot of the work we're doing. You can also get really extreme and do the docker build as a separate step, tag the image with `registry.fly.io/<app>:tag`, `flyctl docker auth` and then push directly to us. Then `flyctl deploy -i registry.fly.io/<app>:tag` will work.

If you get that setup going I'd be comfy with you using pinning a specific flyctl versions right now.
