### ISSUE TITLE
Commands that specify --app seem to now require a fly.toml be present in the working directory

### ISSUE THREAD

**Issue by asyrique** [superfly/flyctl#399]
**Describe the bug**
Previously when I would run commands like `flyctl --app=<some app name> logs` I could run them from any working directory, but in the latest flyctl build, it seems to now always check if there's a `fly.toml` in the current directory, and if there isn't, it will throw an error. If there is one, even if it's empty, command runs perfectly.

I believe it might be related to this code change here: https://github.com/superfly/flyctl/blob/1a44e99a98e6e745dfe6b38b5c4742a358a6f3bf/cmd/command.go#L367-L368

Imho, if I specify an app as a cli param, I would expect the command to work without requiring me to be in a directory with a `fly.toml`

** Add `fly.toml`
N/A

** Command output: **

```text
~> fly version
flyctl v0.0.209 linux/amd64 Commit: 1a44e99 BuildDate: 2021-04-13T00:18:47Z
~> fly --app=fooapp logs
Error config file './fly.toml' not found
~> touch fly.toml
~> fly --app=fooapp logs (this command works)
```

Thanks!

**Comment by michaeldwan** [comment]
@asyrique you're right that isn't working as expected, I'm reverting now and a release will be out in a few minutes. sorry about that

**Comment by asyrique** [comment]
Just installed v0.0.210 and it's working as expected 💪🏿  Thanks for the quick action!
