### ISSUE TITLE
allow fly ssh console <cmd>

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#409]
This would let people run `fly ssh console "rails c"`, for example.

**Comment by jsierles** [comment]
I noticed some work already got released for this, amazing!

Just noticed though that it doesn't seem to work. Adding the `-c` option then prompts you to explicitly set `-a`. If you do, the command isn't actually run.

```
$ fly ssh console
Connecting to ensayo.internal... complete
$ fly ssh console -c ls
Error No app specified. Specify an app or create an app with 'fly init'
$ fly ssh console -c ls -a ensayo
Connecting to ensayo.internal... complete
#
```

**Comment by tqbf** [comment]
Hey, Joshua! It's `-C` (uppercase C), and it'll want quotes around the command right now. 

This isn't great! I'm cleaning up the UX on it (we'll do `flyctl ssh run`) --- though we'll keep the `-C` on `console` (which is useful for getting a `bash` or `zsh` in your session when you log in).

**Comment by jsierles** [comment]
Oops, my mistake! Getting bash works and so does `bash -c`, but I'm not able to do something like `cd app && bin/rails c`. Is there a workaround for that? My Dockerfile has `/app` set as its workdir.

**Comment by mrkurt** [comment]
`fly ssh console -C "command"` works now.
