### ISSUE TITLE
Can't set a build-arg containing `=` from the command line

### ISSUE THREAD

**Issue by mexicat** [superfly/flyctl#410]
**Describe the bug**
I have a build arg I need to pass to `fly deploy` as part of a CI process. This build arg contains the equal symbol `=`. No matter how I escape it, flyctl refuses to accept it:

```
$ fly deploy --build-arg MY_ARG="some=value"
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
Error invalid build-arg: 'MY_ARG=some=value': must be in the format NAME=VALUE
```

```
$ fly deploy --build-arg MY_ARG="some\=value"
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
Error invalid build-arg: 'MY_ARG=some\=value': must be in the format NAME=VALUE
```

Putting the build arg in `fly.toml` makes it work, but I don't want to commit this build arg.

The cause seems to be these lines of validation in the source code, that naively check for the amount of `=`s: https://github.com/superfly/flyctl/blob/1d9b4626ad1637433bbcc68fed74b39499dc1a4b/internal/cmdutil/flags.go#L13-L16

Unfortunately I don't know enough Go to be able to submit a pull request.

**Comment by michaeldwan** [comment]
@mexicat this should be fixed now, sorry about that

**Comment by mexicat** [comment]
Whoa, that was quick! Thank you!
