### ISSUE TITLE
Test flake: testRetryBackoffContextTimeout

### ISSUE THREAD

**Issue by nairb774** [superfly/flyctl#4124]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

When upgrading flyctl to v0.3.50 via the Arch AUR package, the test run failed with the following:

```
--- FAIL: TestRetry (0.35s)
    --- FAIL: TestRetry/testRetryBackoffContextTimeout (0.20s)
        retry_test.go:135:
                Error Trace:    github.com/superfly/flyctl/retry/retry_test.go:135
                Error:          "199.99232ms" is not greater than or equal to "200ms"
                Test:           TestRetry/testRetryBackoffContextTimeout
                Messages:       elapsed time should be at least the timeout duration
        retry_test.go:137: RetryBackoff - Attempts made: 3, Elapsed time: 199.99232ms
FAIL
FAIL    github.com/superfly/flyctl/retry        0.355s
```

The package is running the tests using the following:
`go test ./... -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2024-12-16T18:44:07Z'" --run=`

Looks like this might be a flaky test given the comparison failed by just under 8ms? From a quick look, the `context.WithTimeout` is starting a 200ms timer before the startTime is captured. Then it is expected that the time delta between startTime and the `time.Since` is  going to be longer than the WithTimeout but there is an arbitrary amount of time that could pass between the WithTimeout and the call to startTime. There might be other possible situations which could result in the test failure for this code. This is a racy assertion.

* Operating system

Arch linux
```
$ uname -a
Linux name 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64 GNU/Linux
$ go version
go version go1.23.4 linux/amd64
```

**Comment by kzys** [comment]
> From a quick look, the context.WithTimeout is starting a 200ms timer before the startTime is captured. Then it is expected that the time delta between startTime and the time.Since is going to be longer than the WithTimeout but there is an arbitrary amount of time that could pass between the WithTimeout and the call to startTime.

Good catch! I'm going to update the test to capture startTime before context.WithTimeout.

**Comment by kzys** [comment]
Ah actually nobody is using RetryBackoff right now and we have `github.com/avast/retry-go/v4` and `github.com/jpillora/backoff` and `github.com/cenkalti/backoff`. Let me remove RetryBackoff instead.
