### ISSUE TITLE
Teach flyctl about app networks

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#417]
It's possible to specify isolated networks when you create apps and wireguard peers via our API, but flyctl doesn't know how to do this yet. We need it to. I believe we need to add a `--network` option to most of these commands:

- [ ] `fly wireguard create`
- [ ] `fly ssh establish / issue`
- [ ] `fly ssh console` - this one would need to detect the network ID for the selected app

https://community.fly.io/t/fly-ssh-with-a-custom-network-id/1620

**Comment by mvanlonden** [comment]
This issue was closed prematurely. While #563 adds the network flag for create and launch, it does not add the flag to the commands listed in the issue body.

**Comment by yroc92** [comment]
Any updates on using the wire guard commands with a specified network ID?

**Comment by vazexqi** [comment]
Two years late to this issue but we are also interested in this. 
We are maintaining a fleet of customer apps that we want to isolate so we create a new network id for each.
Though rare, sometimes we need to ssh into the machines to see what is wrong.
`fly ssh console`, as noted, doesn't understand network ids.

**Comment by kylemclaren** [comment]
Dropping in to say `fly ssh` (and other flyctl commands) can now handle custom networks, as of flyctl [v0.2.32]: https://github.com/superfly/flyctl/releases/tag/v0.2.32): https://community.fly.io/t/fly-ssh-with-custom-network/19296
