### ISSUE TITLE
Proxy Command

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#420]
This command opens a proxy from a local port to a vm port over WireGuard.

```
flyctl proxy <port[:port]>
```

Like other commands that operate on an app, this accepts an app name, either from `fly.toml` or the `--app` flag. Before connecting, the app should be fetched from the api to make sure the user has access and that it’s running. Once we know the app is accessible, use the app name to create the private network address, `app-name.internal`.

The command also requires the the local and remote ports as the first argument. Similar to Docker commands, you can specify port mapping in a long `5432:2345` or short `5432` format. In the short form, the same port is used on both ends. In the long form, the first port will be opened on the local host, the second will be the remote port.

You’ll open a WireGuard tunnel similar to what we do for [remote builders](https://github.com/superfly/flyctl/blob/master/internal/build/imgsrc/docker.go/#L188-L210). In that example, we verify the app, open a tunnel, then use the tunnel’s dial context to create an http client for the docker client.

**Comment by mrkurt** [comment]
The `fly ssh console` command works similarly to this. One important feature here is: we should make sure resolving `app-name.internal` works properly every time. @tqbf figured this out for the SSH commands.

**Comment by michaeldwan** [comment]
FYI, remote builders and `ssh console` are using the same connection code now, so resolution issues should be fixed.

**Comment by tqbf** [comment]
This is great. A quick note that I'm a ways down the road to moving WireGuard out-of-process and into an agent, which flyctl spawns; the agent can give you a Dialer for an arbitrary org that should plug into any network protocol, and can run multiple WireGuard connections alongside each other. This won't meaningfully change your code.
