### ISSUE TITLE
Internal DNS docs need update

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#422]
The internal DNS docs are out of date, wrong at least once, and don't cover peer addresses:

* DNS address is wrong
    * within a VM it's defaulted but you could specify `fdaa::3`
    * wireguard peers use a different DNS address, it's specified in the generated wireguard config
* `dig` examples (both from within the VM and over a wireguard peer) would be helpful

**Comment by tqbf** [comment]
Done.
