### ISSUE TITLE
SSH shell doesn't work

### ISSUE THREAD

**Issue by reisxd** [superfly/flyctl#425]
**Describe the bug**
When i try to use `flyctl ssh console -a appname` it connects to it successfully but SSH Shell gives me an error:
```
Connecting to turkey-mail.internal... complete
←[31mError←[0m SSH shell: İşleyici geçersiz.
```
I use Windows 10 Version 2004 (19041.985).

**Comment by tqbf** [comment]
Hey there! I checked out logs, and I see a single connection failure right after a failed attempt to resolve your SSH certificate in the DNS. Is it possible that you tried to log in within seconds of establishing an SSH certificate, and it just hadn't propagated yet? We can rule that out if you try to log in again and still get the same error. (I checked, and your organization now has an established certificate.)

**Comment by reisxd** [comment]
> Hey there! I checked out logs, and I see a single connection failure right after a failed attempt to resolve your SSH certificate in the DNS. Is it possible that you tried to log in within seconds of establishing an SSH certificate, and it just hadn't propagated yet? We can rule that out if you try to log in again and still get the same error. (I checked, and your organization now has an established certificate.)

![image](https://user-images.githubusercontent.com/29177546/121064561-6cf43200-c7d0-11eb-80f8-d8df58273787.png)
Still the same issue

**Comment by tqbf** [comment]
Huh, ok. You're Win10, are you using the built-in SSH client, or something else? I'll try to reproduce this with a similar app.

**Comment by reisxd** [comment]
> Huh, ok. You're Win10, are you using the built-in SSH client, or something else? I'll try to reproduce this with a similar app.

I just run `flyctl ssh console -a appname` and that happens.

**Comment by tqbf** [comment]
Oh oh oh, sorry, I'm punchy today. Trying to reproduce now.

**Comment by tqbf** [comment]
Good-news/bad-news: 

Good: I now have a working Windows desktop with a fresh build of Flyctl on it, and I can easily reproduce this issue.

Bad: It's a real issue! I'm digging in to it now.

**Comment by tqbf** [comment]
Figured it out; you can't use Unix terminal handling ioctls on stdin/stdout on Windows. 

In `pkg/ssh/terminal.go`, if you edit `attach` to add a `&& false` to the `term.IsTerminal` condition at the top of the function, SSH works (albeit with slightly jumbly terminal handling).

Obviously, I'll get non-jumbly terminal handling working and into mainline `flyctl` ASAP. :)

**Comment by reisxd** [comment]
This issue was fixed but i didn't notice so closing it now.
