### ISSUE TITLE
Golang getting started needs update

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#427]
It should use the `fly launch` workflow now. Additionally, it should work with Go templates:

https://community.fly.io/t/how-to-deploy-static-templates-with-go-golang/1339/6

**Comment by billgraziano** [comment]
I would suggest including an advanced section and linking to https://paketo.io/docs/buildpacks/language-family-buildpacks/go/.  I didn't realize just how much good stuff there was in there.  Really helps to see what's going on.

**Comment by billgraziano** [comment]
The new GO embed package really works well for moving templates up with the application.

**Comment by billgraziano** [comment]
I have started using the `embed` package for build information like GIT and build dates.  I have a `deploy` batch file that writes to a local TOML file.  It writes the GIT details, build date, and anything else I want.  That TOML file is embedded using the `embed` package.  It gets copied up and used the build the application by the build pack.  Much easier than messing with LDFLAG junk.  Locally I have a `run` batch file that does the same thing but with DEV information.  Something like that or explaining the LDFLAGs using the build packs would be helpful in an Advanced section.

**Comment by billgraziano** [comment]
I would also include this:  https://community.fly.io/t/multiple-commands-in-a-go-application/1677

Many GO applications will have multiple commands.

**Comment by michaeldwan** [comment]
The guide has been updated.
