### ISSUE TITLE
Stub Out Agent For Windows

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#434]
**Describe the bug**
The `wireguard-agent` branch of flyctl runs an agent process in the background to manage WireGuard connections. This works on macOS and Linux, but not on Windows, where background process management is different (flyctl works outside of WSL).

Since we'd like to merge the `wireguard-agent` branch,  we need to accommodate Windows.

**Suggested fix**

The current code in `pkg/agent/client.go` could be split out into `client_windows.go` and `client_unix.go` or something.

The `client_windows.go` code would export the same "agent" interface, but instead of passing commands to an agent over a Unix domain socket, it'd just run the agent in a goroutine, or emulate the agent's commands in the client interface directly.

**Comment by mrkurt** [comment]
We can get windows based testing for this going with CI, if there's a test mode to run with a pass/fail.

**Comment by rugwirobaker** [comment]
Shouldn't we close this already?
