### ISSUE TITLE
Error during auth (login and signup)

### ISSUE THREAD

**Issue by moyshik7** [superfly/flyctl#443]
**Describe the bug**
I'm having this error  
```bash
Error Post "https://api.fly.io/api/v1/cli_sessions": dial tcp: lookup api.fly.io on [::1]:53: read udp [::1]:56633->[::1]:53: read: connection refused
```
  
  
It says to put fly.toml but I couldn't find the file on my pc
The directory looks like this:
```tree
├── bin
│   ├── fly
│   └── flyctl
└── state.yml
```
I tried googling but didn't help.  
  
Thank you in advance  
  
I'm using version: 0.0.227

**Comment by michaeldwan** [comment]
That looks like an issue connecting to your DNS server to resolve api.fly.io. Is this still happening? Are you able to view fly.io in your browser?

**Comment by moyshik7** [comment]
Thanks for replying  
Yes I'm able to see fly.io from my browser
  
I tried to ping the site with `ping fly.io` and `ping api.fly.io` and both of them have average of around 150-200ms  
  
So then I tried using curl  
and ` curl api.fly.io` returns `404 page not found` error 
and `curl fly.io` dosen't return anything  
  
  
More to include:
I installed the app with  

```sh
curl -L https://fly.io/install.sh | sh
```
And then I set the env variables in bash rule file

**Comment by moyshik7** [comment]
Addition to the above message:  
  
Since It was refusing to connect to `https://api.fly.io/api/v1/cli_sessions` I wnt ahead and sent a dummy post request to that url with  
```sh
curl https://api.fly.io/api/v1/cli_sessions -d '{"name":"dum"}' 
```
and It accepted the connection and sent a url and ID  
```sh
{"id":"xxxxxe6edef4b75e4240ef2xxxxxxxx","auth_url":"https://fly.io/app/auth/cli/xxxxxe6edef4b75e4240ef28xxxxxxxx"}
```
  
I went ahead and signed up with that link but still can't use fly because The cli keeps rejecting for some reason.  
Thank you

**Comment by michaeldwan** [comment]
That's strange. What OS are you on? Do you have go installed? Is there any special DNS running on your local network, like a pihole? Are you on a VPN?

**Comment by moyshik7** [comment]
Firstly I used iton my pc (Windows) and saw the error.  
Then I thought it might be because of firewall or something (Windows have lot of them)  
So I thought switching to Linux might solve it. But since I didn't have any Linux I tried on my phone (termux) and saw the same error and then was pretty much sure it wasn't just my firewall.  
- I don't have Go installed (Should I install it ?)
- I also don't have docker installed either (WillI need it too ?)
- I have an RPi4. I can try on it and comment tomorrow (Since it's getting late in my timezone)  
- I am not on VPN  
- I contacted to a VPN and tried but nothing changed.
- Probably no server is hosted on my pc atm  
**After installing Go**
- I tried installing with `go install flyclt:latest` Dosen't work gives a weird error (dot in path ir something)
- Tried with `go get github.com/superfly/flyctl` It just froze. Like literally froze
- Tried to clone the repo and build from source but couldn't since no experience with go
  
  
### System info
  
PC:
- Windows 10
- Memory: 16 Gb
- CPU: 3 GHz
- GPU: GeForce RTX 2060 (GV-N2060OC-6GD) 6 Gig
  
Phone:
- Android 10
- Memory 4 Gb
- CPU: Unknown

RPi: (Not tested yet)
- Model: Raspberry pi 4
- Memory: 4 Gb
- OS: Raspbian (last updated on December 20)

**Comment by moyshik7** [comment]
Edit: I'll mark it as closed since it worked on my Raspberry pi.  
But somehow didn't still work on my pc
