### ISSUE TITLE
fly agent seems to hang after a few hours (or maybe after a suspend)

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#454]
Using the new `flyctl`, I'm having issues connecting to a builder (and connecting to SSH) after it's been running for a few hours. My laptop has gone to sleep at least once in the last few hours, so that might be the issue.

I haven't quite figured out how to replicate this, but if there's something particular I can try if it happens again put some notes here.

**Comment by azazeal** [comment]
@mrkurt can we close this?

**Comment by michaeldwan** [comment]
Yeah this has been fixed.
