### ISSUE TITLE
fly ssh console hangs when VM goes away

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#455]
When I'm connected to a VM with fly ssh console and then the VM vanishes, `flyctl` hangs it's not easily killable.

I think you can replicate this just by:

1. `fly ssh console` in one terminal
2. `fly vm stop <id-of-what-you're-connected-to>` in another
3. terminal one is now frozen

**Comment by rugwirobaker** [comment]
@mrkurt I'm testing this on the #496. The  `fly ssh console` does not freeze, and `exit` exists with `0`

**Comment by mrkurt** [comment]
This is still happening for me, specifically when I'm SSH'ed and running a Ruby shell. I think @tqbf might have had a guess about what's up.

**Comment by amalkh5** [comment]
@mrkurt @rugwirobaker is still happening to me also.

There workaround for it which is configuring `ServerAliveInterval` values on the `~/.ssh/config`

**Comment by jsierles** [comment]
Duplicate of #636
