### ISSUE TITLE
fly launch should support prebuilt Dockerfiles

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#462]
There are a number of node stacks that would benefit from a default skipping buildpacks and using a default `Dockerfile` when users run `fly launch`.

I'd like to be able to add scanner rules here that build with a Dockerfile so we can give these stacks special treatment (and actual fast builds): https://github.com/superfly/flyctl/blob/3eb204909fbecd5fd2b1ba4517cdbce2abd9f74a/internal/sourcecode/scan.go

**Comment by jsierles** [comment]
In #527, scanners get the power to write files from templates embedded in the CLI.

That PR also adds RedwoodJS support, which writes out an optimized Dockerfile.
