### ISSUE TITLE
flyctl ssh console -C "..." doesn't return response

### ISSUE THREAD

**Issue by davissp14** [superfly/flyctl#463]
**Describe the bug**

`flyctl ssh console -C "..."` does not return a response, however it seems to work on rare occasions.  

After some investigating, it looks like it's hitting an `EOF`.  The EOF exception is being swallowed by: https://github.com/superfly/flyctl/blob/master/pkg/ssh/terminal.go#L81

**flyctl version**
0.0.229

**Operating system**: 
macOS Big Sur v11.2.2

**Command output:**

```bash
~$ flyctl ssh console -C 'ls -ll' --app xxxx
Connecting to xxxx.internal... complete
~$
```

**Comment by davissp14** [comment]
Investigation update

  
**New SSH session is opened:**
https://github.com/superfly/flyctl/blob/master/pkg/ssh/client.go#L86

**Session run command is called** https://github.com/superfly/flyctl/blob/d9599b2ddfe6abf48ef931f3a2865c1e06633d27/pkg/ssh/terminal.go#L79

**Run function definition:**
https://github.com/golang/crypto/blob/master/ssh/session.go#L296-L309

**Our request being sent through the channel:**
https://github.com/golang/crypto/blob/master/ssh/session.go#L286

**SendRequest function definition**
https://github.com/golang/crypto/blob/master/ssh/channel.go#L569

**Noteworthy comment on SendRequest**
```
// SendRequest sends a channel request.  If wantReply is true,
// it will wait for a reply and return the result as a
// boolean, otherwise the return value will be false. Channel
// requests are out-of-band messages so they may be sent even
// if the data stream is closed or blocked by flow control.
// If the channel is closed before a reply is returned, io.EOF
// is returned.
```

I added a bunch of logs and was able to clearly see that the Channel is being signaled to close before we get a reply.  What I haven't figured out yet is what or why that signal sending that signal.

**Comment by davissp14** [comment]
Another update, just to make this issue even more weird. 

`flyctl ssh console -C "ls -ll"` will fail to return a response the majority of the time.

However, if I create a binary that does the same thing and call that, it works just fine.

E.G.
```bash
# ls-test.sh
#!/bin/bash

ls -ll
```

`flyctl ssh console -C "./ls-test.sh"`

**Comment by michaeldwan** [comment]
@davissp14 is this working for you now?

**Comment by davissp14** [comment]
@michaeldwan As of last night, I am still experiencing the issue.

**Comment by tqbf** [comment]
Just a quick note that I deployed the most recent hallpass code on all the workers today at 11:30AM.

**Comment by rugwirobaker** [comment]
This is still an issue. It only works 2 times out of 5.

**Comment by jsierles** [comment]
I haven't been able to reproduce this anymore.
