### ISSUE TITLE
The agent won't notice changes to ~/.fly/config

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#464]
If you change your WireGuard configuration, using `flyctl` or, god help you, by editing `~/.fly/config` directly, your agent will be out of sync with the config file. 

For instance, to help Shaun debug a problem, I had him rename his `personal` WireGuard state to get the agent to make a new one. But, of course, `flyctl agent` doesn't know about this, and keeps using the old one. Restarting the agent fixes this.

The agent should note the timestamp on the config file when it starts, and double-check the configuration hasn't updated before responding to a command. It's a cheap check, we might as well always do it.

**Comment by michaeldwan** [comment]
closed in #487
