### ISSUE TITLE
Deleting some WireGuard peers permanently confuses the agent

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#467]
If `flyctl` has created a WireGuard connection for SSH (or whatever), on the fly, that peer will show up in the `flyctl wireguard list` list. That's good.

But if a user deletes that WireGuard connection, we delete it serverside, but not from `~/.fly/config`. The agent will think the connection is still valid, even though it isn't. 

We should make `flyctl wireguard delete` also delete the matching entry from `~/.fly/config`. But this only addresses the most obvious version of this problem, because if you delete that peer from a different host, `flyctl` will never know. 

So the other thing `flyctl` should probably do is, when a WireGuard connection times out, pull the list of WireGuard peers from the API and make sure it's still valid.

**Comment by marcus-crane** [comment]
> So the other thing flyctl should probably do is, when a WireGuard connection times out, pull the list of WireGuard peers from the API and make sure it's still valid.

This PR I submitted a little while ago validates the peer exists prior to using it since I ran into this issue with https://github.com/superfly/flyctl/issues/446: PR https://github.com/superfly/flyctl/pull/447
