### ISSUE TITLE
fly ssh console w/selection sometimes connects to the wrong instance

### ISSUE THREAD

**Issue by davissp14** [superfly/flyctl#473]
I have three healthy VM's within the same region and when I run `fly ssh console -s`, it doesn't always put me on the correct instance.   

**Example**
```bash
$ fly ssh console -s
? Select instance: ord (fdaa:0:2e26:a7b:81:0:2d05:2)
Connecting to [fdaa:0:2e26:a7b:81:0:2d04:2]... complete
```

**flyctl version**
0.0.229

**Comment by tqbf** [comment]
Whoah, neat bug.

**Comment by davissp14** [comment]
A quick update on this bug. 

I added some logging and found that each of the Addresses in the reply were duplicates:
 https://github.com/superfly/flyctl/blob/master/pkg/agent/client.go#L160
 
 ```
 Reply: {"Labels":["sea (fdaa:0:2e26:a7b:ac4:0:2e7a:2)","sea (fdaa:0:2e26:a7b:ac4:0:2e77:2)","sea (fdaa:0:2e26:a7b:ac2:0:2e79:2)"],"Addresses":["fdaa:0:2e26:a7b:ac4:0:2e7a:2","fdaa:0:2e26:a7b:ac4:0:2e7a:2","fdaa:0:2e26:a7b:ac4:0:2e7a:2"]}
 ```
 
I went ahead and restarted the agent and it seemed to clear the issue. 

I found that running `fly agent restart` seems to resolve the issue.
