### ISSUE TITLE
flyctl deploy --remote-only leaves a strange app hanging around

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#477]
I'm running the following command:

    flyctl deploy . --app myapp --config fly.toml --remote-only

I'm using `--remote-only` because I don't want to have to worry about whether or not I have a local Docker daemon working.

After I do this, an additional Fly app shows up in my dashboard called something like `fly-builder-lively-snowflake-2915`:

<img width="1315" alt="Mozilla_Firefox" src="https://user-images.githubusercontent.com/9599/127716008-2a5da655-e92f-4437-9bbf-2a2a5c86ec7b.png">

This seemed to stick around after the deploy completed (in particular when an earlier deploy returned an error). I manually deleted it, but it wasn't clear to me if I had been charged for it.

On a successful deploy the app seems to delete itself shortly after the deploy completes.

My guess is that this temporary app runs the remote build. It would be useful if that app included a note explaining what it was for (or ideally if it didn't show up at all, I'd like to be able to run remote deploys without needing to think too hard about the implementation details).

**Comment by michaeldwan** [comment]
You're right, that's the app that runs the docker daemon for your organization's builds. They get created on demand and are excluded from billing at the moment. We opted to show them since some people have connected to them to configure remote registries or purge caches. The lack of any description is confusing though.

**Comment by simonw** [comment]
That's reassuring to hear (they they aren't billed) - I had fun SSHing in and poking around a bit.

How about changing the naming scheme to something like this?

    fly-docker-builder-excluded-from-billing-lively-snowflake-2915
