### ISSUE TITLE
Missing documentation for MemoryIncrementsMB

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#478]
If I run `flyctl platform vm-sizes --json` one of the fields I get back is called `MemoryIncrementsMB`:
```json
{
    "Name": "dedicated-cpu-8x",
    "CPUCores": 8,
    "MemoryGB": 16,
    "MemoryMB": 16384,
    "PriceMonth": 248,
    "PriceSecond": 0.00009568,
    "MemoryIncrementsMB": [
        16384,
        32768,
        65536
    ]
}
```
I can't find any documentation about what this means.

Are these the only allowed values to pass to `--memory` when scaling an app to use that VM size?

If so, it conflicts with the documentation on https://fly.io/docs/flyctl/scale-vm/ which says about `--memory`:

> For dedicated vms, this should be a multiple of 1024MB.

**Comment by mrkurt** [comment]
`MemoryIncrementsMB` is an internal implementation detail you _shouldn't_ need to know about, but it's leaking.

Our VM sizes have a base memory amount and then an allowed _additional_ memory amount. When you run `fly scale vm shared-cpu-1x --memory 1024` we do magic to abstract that. I'm guessing this is only in the API output for displaying VM sizes, but it's pretty gross: https://github.com/superfly/flyctl/search?q=MemoryIncrementsMB

**Comment by simonw** [comment]
> The allowed values for `--memory` are `MemoryMB + MemoryIncrementMB`

Does that mean the information on this page is out-of-date? https://fly.io/docs/flyctl/scale-vm/
