### ISSUE TITLE
Eagerly open a WireGuard tunnel when running `flyctl launch`

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#486]
We eagerly create a builder now, consider opening and probing a tunnel in parallel while the user completes the launch prompts.

**Comment by rugwirobaker** [comment]
Doesn't this require a special mutation of this sort: https://github.com/superfly/flyctl/blob/3329f0d65eabec9786ccf4a5e302ecf51c9ca40f/api/resource_remote_builders.go#L31-L39

**Comment by jsierles** [comment]
I don't think this requires backend work. We would be trying to open a tunnel in parallel instead of waiting.

**Comment by rugwirobaker** [comment]
Picking this up

**Comment by rugwirobaker** [comment]
Picking this up

**Comment by jsierles** [comment]
Cool. Though, something that may be more urgently useful is #819. I feel like we should not be piling any more behavior on this old launch command when we still have a lot of wireguard instability.

**Comment by rugwirobaker** [comment]
I'll wait

**Comment by michaeldwan** [comment]
done
