### ISSUE TITLE
The agent should detect peers removed without changing the config file

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#488]
#483 added support for pruning invalid peers from the config, and fixing #464 will make sure the agent detects config file changes. There's still the case where peers are removed without changing the config file, such as from the API. To handle that case, the agent should periodically validate peers, maybe every 1-5 minutes. A simple/naive way to do this might be a goroutine that runs [`wireguard.PruneInvalidPeers`](https://github.com/superfly/flyctl/blob/master/internal/wireguard/wg.go#L154) (slow, removes peers from the config after checking the API) and [`server.validateTunnels`](https://github.com/superfly/flyctl/pull/485/commits/18216494d4302ba6d41a499b8ca519ef4cfa31c3#diff-18bf746206c8ac217eb16ffb0cf91a6e676e05a7b517dc70aef0260d0871028fR396) (fast, closes tunnels not in the config) on a ticker.

**Comment by rugwirobaker** [comment]
@michaeldwan  With #487 merged almost ready to be merged do we still need to do this?

> To handle that case, the agent should periodically validate peers, maybe every 1-5 minutes.

**Comment by michaeldwan** [comment]
@rugwirobaker yeah that looks great. I'll try it out tonight.
