### ISSUE TITLE
Autoscale doesn't get disabled

### ISSUE THREAD

**Issue by virajsoni06** [superfly/flyctl#512]
Once autoscale is enabled, running `flyctl autoscale disable` doesn't disable autoscaling.

Check the image below, which shows the autoscale enabled, after disabling still it's enabled
![image](https://user-images.githubusercontent.com/13236286/131221140-a6d88448-7467-45ec-a2a7-5d400bd79785.png)

**Comment by jsierles** [comment]
Sorry for the delay. This is a backend issue and has been raised there.

**Comment by pborzenkov** [comment]
This has been fixed.
