### ISSUE TITLE
Unable to authenticate/get docker apps which are under Heroku organisations

### ISSUE THREAD

**Issue by virajsoni06** [superfly/flyctl#514]
Hi guys, trying to deploy an existing Heroku app. I can see apps from Heroku which are under my personal account. However, I cannot see apps which are under a organisation. Any workaround for this?

**Comment by rugwirobaker** [comment]
You will probably get s solution faster on https://community.fly.io if you don't mind re asking the question there.

**Comment by virajsoni06** [comment]
Thanks, didn't knew there was a discussion board as well. Cheers!
