### ISSUE TITLE
go install github.com/superfly/flyctl@latest fails...

### ISSUE THREAD

**Issue by gedw99** [superfly/flyctl#538]
**Describe the bug**

For CI and Ops automation it would be really nice if go install worked...
Makes it easy to pin versions for teams and lots of other geeky reasons.

I actually had no idea that go 1.17 had issues with go.mods like is happening in this repo..
So you think it is possible to refactor the go.mod such that the replace directives failure does not occur for a ``` go install ``` scenario ?

**Reproduction**

````

go install github.com/superfly/flyctl@latest
go: downloading github.com/superfly/flyctl v0.0.242
go install: github.com/superfly/flyctl@latest (in github.com/superfly/flyctl@v0.0.242):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
make: *** [dep-fly] Error 1

```

**Comment by gedw99** [comment]
thanks. i know about the other ways to install  https://fly.io/docs/flyctl/installing/

will do that for now..

**Comment by gedw99** [comment]
Hey

i just saw the new beta release includes the separation of the API and was thinking that maybe now this issue will be fixable 


Here is the or in question 


https://github.com/superfly/flyctl/pull/548

**Comment by jsierles** [comment]
This probably will continue to be a problem with the current CLI setup. We aren't going to prioritize this, and instead recommend that people use the binary releases in CI.
