### ISSUE TITLE
Cannot create new app with "flyctl launch" or add billing information

### ISSUE THREAD

**Issue by kirajano** [superfly/flyctl#546]
**Describe the bug**
Started to create my first application in fly.io and ran `flyctl auth login` with GitHub. After successfully loging in, tried to run `flyctl launch` and selected the region for the application. The response was `Error We need your payment information to continue! Add a credit card or buy credit: https://fly.io/organizations/personal`

When following the link and going to the website, and trying to add billing info, you are forwarded to the the app list page (in my case no apps). Clicking "Create App" takes to speedrun page where, it is documented that you need to run `flyctl launch` *"to create, configure, and deploy a new application by inspecting your source code"*. In the end, I ended up where I started.

**Comment by mrkurt** [comment]
Will you give this another try? We managed to break our stripe integration with a recent release, we've just reverted. This should work now: https://fly.io/organizations/personal

**Comment by soobrosa** [comment]
Just checked `Manage Billing` and it works fine for me.

**Comment by kirajano** [comment]
Thanks, I tried again and seems to work as expected. I will close
