### ISSUE TITLE
flyctl cannot be installed from the home directory

### ISSUE THREAD

**Issue by hungrybluedev** [superfly/flyctl#555]
I am using PopOS (Linux) and I was following the instructions to install the command-line tool. I pasted the following script into my terminal, but the script was hanging, and it eventually exit with a non-zero error code.

```
curl -L https://fly.io/install.sh | sh
```
Tried saving the script, then executing it afterwards, but no luck. I was repeating these executions in my home folder.

Moved into another directory and tried executing it again, and this time installation was successful.

**Comment by jsierles** [comment]
This script is not doing much, so I can't imagine what would cause this. You could try adding some `echo` debug statements between the commands to see where it's hanging.
