### ISSUE TITLE
`flyctl auth logout` results in `os: process already finished` error

### ISSUE THREAD

**Issue by aldy505** [superfly/flyctl#568]
**Describe the bug**
Tell us what broke, what operating system you're using, etc.
- OS: Debian 10 on WSL (Windows Subsystem Linux)
- Linux kernel: Linux 4.19.128-microsoft-standard (if this helps)
- Flyctl version: flyctl v0.0.247 linux/amd64 Commit: 8068b7f BuildDate: 2021-10-11T16:25:15Z

Simply by running `flyctl auth logout` I got an error which I don't know what happened. I just opened my terminal first thing in the morning and this happened. What I want to do is to logout and switch to my personal fly.io account.

If there's any other information that you guys need to debug this, please let me know. Thanks.

**Add `fly.toml`**

No config file because I'm on my home directory. Also shows the same error message when I'm on a directory where there is a `fly.toml` file.

**Command output:**

```text
~
❯ flyctl auth whoami
Current user: ***@gmail.com

~
❯ flyctl auth logout

Error os: process already finished
```

**Comment by azazeal** [comment]
Closed with #714
