### ISSUE TITLE
Skip app mismatch confirmation for readonly commands

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#57]
flyctl requires confirmation if the app name in fly.toml doesn't match the -a flag or FLY_APP_NAME variable. This should only apply to write commands like deploy not readonly commands like status and logs.

**Comment by jsierles** [comment]
This no longer happens because the mismatch check has been removed in the new CLI command chains. For read-only commands, the `-a` option takes precedence. For writes, the `fly.toml` takes precedence. If we want different behavior, we can open a new issue.
