### ISSUE TITLE
`flyctl secrets import` should be able to ignore comments

### ISSUE THREAD

**Issue by tmm1** [superfly/flyctl#575]
I'd like to use `fly secrets import` with the .env file in  mastodon, which has a lot of comments: https://github.com/mastodon/mastodon/blob/main/.env.production.sample

```
$ fly secrets import
# test
A=1
^D
Oops, something went wrong! Could you try that again?
```

**Comment by jsierles** [comment]
Sorry for missing this one. Good catch! A workaround for now would be:

`cat secrets.txt | grep -v ^# | fly secrets import`

**Comment by z3ugma** [comment]
Similarly! Being able to handle .env files that start with `export` 

```
export FLASK_DEBUG=true
export DEBUG=False
export SECRET_KEY=`1324`
```

**Comment by me-diru** [comment]
Hello,

may I work on this? thanks!
