### ISSUE TITLE
Can't deploy local docker image

### ISSUE THREAD

**Issue by dyaa** [superfly/flyctl#58]
When I build a docker image locally and try to deploy it to Fly get an error 

How to reproduce:
- Build an image with docker `docker build ...`
- Check the image using `docker images` and its there and found
- Try to deploy it using `flyctl deploy -a APP_NAME --image IMAGE_NAME`

it returns 
> Error Unable to access image IMAGE_NAME: 401 Unauthorized

Also the same happens if I try to deploy a docker image that is located in Github's docker registry

**Comment by codepope** [comment]
I'm assuming that you have already run `flyctl apps create` in the directory to get your app name and create a `fly.toml` file. (if not, you'll want to do that).

You don't deploy local images to Fly. When you deploy, the application image is built and transferred to the Fly platform. All you need to do is run `flyctl deploy` on its own to let the system use the local Dockerfile as a guide to what needs to be built. 

You only need `-a` if you are overriding the app name in  the `fly.toml` file. 

Using `-i/--image` overrides all that behaviour above and asks flyctl to deploy a publicly available docker registry image. The reason you get 401 Unauthorized is because your image is probably created under your own account and private.

**Comment by dyaa** [comment]
> I'm assuming that you have already run flyctl apps create in the directory to get your app name and create a fly.toml file. (if not, you'll want to do that).

Indeed I did that

> You don't deploy local images to Fly.

The reason why I wanna deploy a locally built image is that I'm deploying an app within a monorepo using [lerna](https://github.com/lerna/lerna), The built itself is being done using docker-compose with this docker-compose configuration

```yaml
    build:
      dockerfile: ./web/one/Dockerfile
      context: .
```

So if I built & deployed using `flyctl deploy -a ...` i would get errors like

> no such file or directory since the context is different for the build directory

Any ideas on how can I make this work? also, I would be really nice to have deployments using privately hosted registry or a locally built image tag

**Comment by dyaa** [comment]
> I'm assuming that you have already run flyctl apps create in the directory to get your app name and create a fly.toml file. (if not, you'll want to do that).

Indeed I did that

> You don't deploy local images to Fly.

The reason why I wanna deploy a locally built image is that I'm deploying an app within a monorepo using [lerna](https://github.com/lerna/lerna), The built itself is being done using docker-compose with this docker-compose configuration

```yaml
...
    build:
      dockerfile: ./packages/app/Dockerfile
      context: .
...
```

So if I built & deployed using `flyctl deploy -a ...` i would get errors like

> no such file or directory since the context is different for the build directory

Any ideas on how can I make this work? also, I would be really nice to have deployments using privately hosted registry or a locally built image tag

**Comment by jeromegn** [comment]
Oh, we should add a feature to allow passing a Dockerfile path and context path.

**Comment by dyaa** [comment]
> Oh, we should add a feature to allow passing a Dockerfile path and context path.

Indeed I see a value in being able to pass the context path as well, but also why not to give the dev the ability to push a locally built image? does flyctl apply some sort of optimization on top of the docker image build?

**Comment by michaeldwan** [comment]
@dyaa that's a bug, we'll git it fixed

**Comment by mrkurt** [comment]
@dyaa There's a hacky workaround for this. If you create a new `Dockerfile` with `FROM LOCAL_IMAGE_NAME:TAG`, then run `flyctl deploy` in that directory, it will use layers from your local image.

**Comment by dyaa** [comment]
Smart 👏, That would be a workaround ATM

**Comment by 0az** [comment]
> There's a hacky workaround for this. If you create a new Dockerfile with FROM LOCAL_IMAGE_NAME:TAG, then run flyctl deploy in that directory, it will use layers from your local image.

I was hoping that this would get around that particular limitation, but unfortunately, this doesn't work with BuildKit. 

```
Using Dockerfile: Dockerfile.fly
Error Error response from daemon: Dockerfile parse error line 15: Unknown flag: mount
```

**Comment by mrkurt** [comment]
@0az oh dang I didn't see your response! Hopefully this fix takes care of you in our next release though.

**Comment by mbrevda** [comment]
Would be great if was possible to push an already-built container (perhaps by running `docker save` under the hood?). Has there been any progress in that direction since this issue?

**Comment by mbrevda** [comment]
Update: I see this can be done by pushing to the [docker registry](https://github.com/superfly/flyctl/issues/104#issuecomment-977109064) first. Would still be great to have the ability to push a local container in one step
