### ISSUE TITLE
Windows agent

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#584]
The WireGuard agent lets flyctl multiplex connections through a single tunnel using a daemon process that's launched on demand. Without it, a new connection will immediately kill an existing one. We open connections for a lot of things, like remote builds, ssh console, proxy, and logs.

The agent is only supported on Linux and macOS but we need it on Windows too. The actual agent code is identical across platforms, but we might need some abstractions to get windows working. Specifically, the agent and client use unix sockets to communicate which may or may not work the same on windows. Windows also might have some differences in how the agent process is started, tracked with pid files, and killed. 

Lastly, as we refactor the agent api we should have flyctl fallback to an in-process agent on all platforms if the agent daemon is unavailable and fails to start. This happens occasionally now and it would be better to work in a less ideal way than fail all together with no workaround.

**Comment by azazeal** [comment]
Closed with #718
