### ISSUE TITLE
Version check lag

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#586]
The update check is happening synchronously now which is causing random lag. I suggest splitting the logic up into two parts, first is fetching information on the latest release and saving it to `~/.fly/state.yml`, and the second is printing the update warning based on the cached version info.

We should only print the update warning based on what we have in state.yml, if available. Update info should be fetched asynchronously and cached to state.yml so the _next_ flyctl invocation can print the warning. There was a `safeExit` function that used a wait group to block on background tasks for this purpose, but there's probably a better way to do this. We should also only fetch updated version info for commands that have a run function. Otherwise commands that should be instant, like `flyctl`, `flyctl auth`, and `flyctl deploy --help` are slowed down by the update check. `flyctl` should feel snappy after these fixes.

**Comment by azazeal** [comment]
#572 should should eliminate the problems completely.
