### ISSUE TITLE
MaxPerRegion is always "Not Set"

### ISSUE THREAD

**Issue by sudhirj** [superfly/flyctl#596]
**Describe the bug**
Even after running `fly scale count 2 --max-per-region 1`, `fly scale show` still shows the following output:
```
VM Resources for summer-dream-6105
        VM Size: shared-cpu-1x
      VM Memory: 256 MB
          Count: 2
 Max Per Region: Not set
```

The command to set the --max-per-region seems to be effective, in that it looks like it's working as intended. On the display doesn't doesn't seem to be up to date.

**Comment by mrkurt** [comment]
This might be using "old" API. It should actually show this stuff from the `processGroups` types.

**Comment by gwuah** [comment]
A fix for this has been released.
