### ISSUE TITLE
Redirect http to https 

### ISSUE THREAD

**Issue by dyaa** [superfly/flyctl#61]
Is there's a way to redirect http to https requests? otherwise, we can add a config in `fly.toml` for that

**Comment by mrkurt** [comment]
There's not! We've thought about an option on the `http` handler, but usually these kinds of redirects are better in the app themselves so we've been procrastinating. What are you running? Most app frameworks have some nice middleware for handling this.

**Comment by dyaa** [comment]
> Most app frameworks have some nice middleware for handling this.

That's right, But what do you think about having a `default` handler for example to redirect calls to it?
