### ISSUE TITLE
Feature request: support remote docker contexts

### ISSUE THREAD

**Issue by ashtuchkin** [superfly/flyctl#618]
I'm on an M1 Macbook (arm64) and would like to use externally-built docker images with flyctl. 

Building amd64 images on this laptop is very slow due to Docker using qemu, not Rosetta (I'm talking 10x-100x slower). To alleviate this problem, I'm using a remote docker context, with dockerd daemon running on a separate x86 host. I've set it as the default context using `docker context set xxx`. This overall works really well - all the docker commands, including builds, pulls, pushes are running transparently. Flyctl unfortunately doesn't.

When I set "image"  in `[build]` section, `flyctl deploy` tries to find this image in two places:
 1. In the local (not default) docker context. This doesn't work in my case because the image is in the remote context, not the local one.  Making the extra step to pull the image to the local context doesn't work either because the image is multiarch and it pulls image for arm64 platform instead of amd64.
 2. In remote registry. This only works for public registries, which is not my case.

So, my feature request would be to use default docker context instead of local one. This would match developer experience when issuing `docker` commands. 
Alternatively, supporting private registries would work. Let me know if you'd like me to file a separate issue for that.

I've noticed that this behavior was changed in c61c9f760298613ec176155a41bbbe97a420e62f. Commit message does not provide the reasoning though, so I'm hoping that the reason is not something fundamental.

**Add `fly.toml`**

```toml
[build]
  image = "registry.gitlab.com/ashtuchkin/****"
```

**Command output:**

```text
Deploying myapp
==> Validating app configuration
--> Validating app configuration done
Searching for image 'registry.gitlab.com/ashtuchkin/****' locally...
Searching for image 'registry.gitlab.com/ashtuchkin/****' remotely...
Error Authentication required to access image "registry.gitlab.com/ashtuchkin/****:latest"
```

**Comment by michaeldwan** [comment]
We're very familiar with qemu performance/segfault issues on the m1. Thankfully you can get `flyctl` to use a different docker host as the "local" daemon using the `DOCKER_HOST` env variable without any code changes. I use it all the time to build on an amd64 linux box at home:

```
DOCKER_HOST=192.168.1.100 flyctl deploy ...
```
