### ISSUE TITLE
Can't use public images from AWS ECR

### ISSUE THREAD

**Issue by ashtuchkin** [superfly/flyctl#619]
Using any public image in AWS ECR results in "unknown error":
```bash
$ flyctl deploy -a bug --image public.ecr.aws/nginx/nginx:latest
Deploying bug
==> Validating app configuration
--> Validating app configuration done
Searching for image 'public.ecr.aws/nginx/nginx:latest' locally...
Searching for image 'public.ecr.aws/nginx/nginx:latest' remotely...
Error An unknown error occured.
```

Other public repositories are shown here: https://gallery.ecr.aws/  Looks like none of them work.

**Comment by jsierles** [comment]
Thanks for the report! It looks like these images are lacking a manifest, which we're trying to fetch for storing in our backend. We'll take a look at it.

**Comment by ashtuchkin** [comment]
Thank you! I'm using a different public repo for now, so not blocked on it. Just wanted to let you know about this error so other people would not bump into it when they try to use ECR.

**Comment by jsierles** [comment]
It looks like we are fetching a manifest, but we're not storing it correctly on our backend. For internal reference, here's the related exception: https://sentry.io/organizations/flyio/issues/2817669443
