### ISSUE TITLE
Prevent ssh console lockup from dead VMs

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#636]
**Describe the bug**
Log into an instance with `flyctl ssh console`. 

Kill the instance (`kill -9 <master-process>`, whatever).

Now try to get out of `flyctl ssh console`.

**Comment by kzys** [comment]
What is the master process here? Both `kill -9 $(pidof hallpass)` and `fly machine stop [machine ID]` (from #455) correctly closed the terminals for me now. We may be fixed the issue already.

**Comment by pborzenkov** [comment]
Yeah, this has been fixed in `init` by `SIGTERM`ing `hallpass` before machine's reboot, so guest kernel has a chance to tear-down TCP connection properly.

**Comment by kzys** [comment]
https://github.com/superfly/init/pull/86

Awesome! Resolving.
