### ISSUE TITLE
ALPN certificate verification doesn't work

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#64]
`flyctl certs create` and then just pointing a hostname at the app IP doesn't properly work. Lets Encrypt gets an error validating:

```
{"type"=>"urn:ietf:params:acme:error:tls", "detail"=>"remote error: tls: access denied", "status"=>400}
```

cc @jeromegn

**Comment by jeromegn** [comment]
Now fixed.

**Comment by mrkurt** [comment]
@codepope I'm not sure how best to explain this to people, but now you can either:
1. Point your DNS at your app ips (ipv6 entry required) and we'll issue you a cert
2. Do the existing DNS acme challenge (required for wildcards)

I suspect most people will want to do #1, it's basically one step. A cname to their <app>.fly.dev might be easiest since it handles both A/AAAA record but I don't love it.

**Comment by codepope** [comment]
So for ALPN, you need to have an AAAA record that points at the IPv6 address; I assume you still need an A for IPv4 anyway.  Let's explain #1 in documentation.

**Comment by mrkurt** [comment]
Yep. We require to AAAA record to validate and you'll want the A to route traffic (probably).

**Comment by mrkurt** [comment]
Just for more fun information, we require the AAAA record to validate because ipv6's are almost never reused. So people can't squat certificate hostnames, or claim one by using an IP that's already been validated.

**Comment by jeromegn** [comment]
Right now, this is not restricted to IPv6, but it could be.

**Comment by mrkurt** [comment]
@jeromegn the rails app will only do the setup if ipv6 is configured, so it's good enough for now. :D
