### ISSUE TITLE
flyctl postgres create <flags>

### ISSUE THREAD

**Issue by jgttech** [superfly/flyctl#645]
**Describe the bug**
Tell us what broke, what operating system you're using, etc.
When you attempt to run `flyctl postgres create <flags>` there is no flag to bypassing the configuration prompt. I have attempted to review the `postgres.go` file and it appears that on `line 214` there is a condition for a FALSE `customConfig` flag. Then, on `line 236` there is a FALSE condition. The `else` condition on `line 271` never appears to actually get executed and, as a result, there is no way to bypass the prompt for configuration. I have tried all the permutations of the `flyctl postgres create <flags>` to try and bypass the prompt but it does not seem to work.

I think we need a `--config`, `--conf`, `-c`, and/or `--configuration` for bypassing this prompt in some way.

**Comment by jgttech** [comment]
Line 214:
https://github.com/superfly/flyctl/blob/c87dc007012bbfb5fdac6cefcac3d95cc5c2bb08/cmd/postgres.go#L214

Line 236:
https://github.com/superfly/flyctl/blob/c87dc007012bbfb5fdac6cefcac3d95cc5c2bb08/cmd/postgres.go#L236

Line 271:
https://github.com/superfly/flyctl/blob/c87dc007012bbfb5fdac6cefcac3d95cc5c2bb08/cmd/postgres.go#L271

**Comment by davissp14** [comment]
Got it, I think all we'd need is a way to dictate development "standalone" vs. production "HA".  Then as long as everything else is manually set, we could skip the interactive prompt.
