### ISSUE TITLE
Improve `fly checks list` formatting.

### ISSUE THREAD

**Issue by davissp14** [superfly/flyctl#669]
The health checks listed via `fly checks list --app <postgres-app>` are not easy to read.  It would be awesome if we could make these more presentable and easier to read. 

<img width="820" alt="Screen Shot 2021-12-17 at 4 28 02 PM" src="https://user-images.githubusercontent.com/423038/146615214-912f82f4-8d5d-4856-85f7-8d5f688eb659.png">

**Comment by redjonzaci** [comment]
@davissp14 @jsierles can we close this since @shortdiv's work is merged?
