### ISSUE TITLE
`fly doctor`

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#675]
We need a single diagnostic command that collects information about an installation, suggests fixes for problems, and optionally bundles up and sends diagnostic reports to us.

The command should at a minimum:

* Verify API connectivity and authorization
* Report the status of the agent
* Report all current WireGuard connections in the configuration
* Report the status of all WireGuard connections in the agent (incl. bytes sent/received)
* Check WebSockets connectivity for WireGuard
* Report the `_apps.internal` TXT record for which apps are in each account linked with WireGuard
* Report the `AAAA x.internal` for each app on each connection.

We should have an API endpoint that collects these reports; `flyctl` should just use `archive/zip` to bundle up all these artifacts and post them to the endpoint.

We can noodle more on this, this issue is just to plant a flag. Any suggestion we'd give for debugging on the forum, we should build into `fly doctor`.

**Comment by mrkurt** [comment]
I think this could be smaller to start. What we need right now is a way to see everything we can about these things for a _specific_ org:

1. agent status
2. wireguard status (is it doing anything?)
3. dns information, as much as possible (txt lookups fail sometimes when things go badly)
4. ssh key information

If we can get like 2 things in and it's easy to add checks, we can help people a bit quicker with new builds.

**Comment by azazeal** [comment]
there should probably also be some sort of `udp` connectivity test

**Comment by tqbf** [comment]
udp is a good thought. The thing you _really_ want is udp to 51820/udp, but you can't make that port respond w/o keying material. I'll add a dummy 51821 echo to wgtcpd though and we can test against that.

**Comment by azazeal** [comment]
I was thinking of a more complex integration:

   - flyctl receives a unique ID from an app hosted on fly (via HTTP)
   - it then proceeds to send a UDP packet containing this ID to said app
   - at the same time it's already subscribed to a SSE channel waiting for
   a response from that app
   - the app responds when it's received the UDP message

after 10s, we'll know if the user can send UDP or not.

Thoughts?

**Comment by azazeal** [comment]
The initial version of this command has been shipped already - can we close this @tqbf / @mrkurt ?

**Comment by michaeldwan** [comment]
@azazeal we should keep this open until all of the requested items are printed in the doctor output and results are collected. Right now it's a good start, but there's a lot missing for it to be a useful debugging tool for users and for us.

**Comment by michaeldwan** [comment]
@azazeal also, you were right, the udp echo handler in the debug app isn't listening to `fly-global-services`. Would you be able to get that working? Here's the code https://github.com/superfly/debug/blob/master/main.go#L169-L195

This repo needs a little bit of care to deploy since we use it for a ton of monitoring, so someone in #dev or #ops can help get it out once a PR is merged.

**Comment by azazeal** [comment]
> @azazeal also, you were right, the udp echo handler in the debug app isn't listening to `fly-global-services`. Would you be able to get that working? Here's the code https://github.com/superfly/debug/blob/master/main.go#L169-L195
> 
> This repo needs a little bit of care to deploy since we use it for a ton of monitoring, so someone in #dev or #ops can help get it out once a PR is merged.

I have a couple more questions around this, on the internal forum. If you'd take a look there that'd be great.
