### ISSUE TITLE
flyctl CLI survey default selected results in error

### ISSUE THREAD

**Issue by jphenow** [superfly/flyctl#680]
**Describe the bug**

Context: I was creating a new app via `flyctl create`. I have both an organization and a "personal" organization.

* I ran `flyctl create`
* I was prompted for a new app name, I entered one
* I was then prompted to select an organization
  - My "personal" organization was first in the list 
  - If I just hit enter (seemingly selecting that "personal" organization) it responds with "Oops, something went wrong! Could you try that again?"

I was able to work around this by arrowing down, and back up to my personal organization, _then_ selecting it. Pretty minor hiccup I'd say :-) 

I did do a bit of digging and found [here](https://github.com/superfly/flyctl/blob/56d53d4350b0f88fff0efadd3c490f411e59044f/cmd/input.go#L70) that it's using this lib: https://github.com/AlecAivazis/survey. I then found an [open issue](https://github.com/AlecAivazis/survey/issues/342) for this behavior.

I'm hoping to take a look at this in some free time soon - I just wanted to write it down in case I forget or something!

**Comment by azazeal** [comment]
This has [hopefully] been patched in `v0.0.272-pre-6` and later.
