### ISSUE TITLE
Support NO_COLOR or TERM=dumb

### ISSUE THREAD

**Issue by hherman1** [superfly/flyctl#687]
**Describe the bug**
My terminal (rc in acme) doesn't support ANSI escape codes. Would love it if flyctl would just not emit them for me! See below:

![image](https://user-images.githubusercontent.com/611822/147629745-23601ef5-3333-488d-8c43-2b2cd5f27ff8.png)

**Comment by azazeal** [comment]
Hi there - this is for sure in our pipeline but unfortunately I don't have an ETA for you :(

**Comment by jsierles** [comment]
Now colorization passes through a single function in #796, this should be a simple change for commands that use it (including `deploy`).

**Comment by ramiel** [comment]
Any news about this? I need to run the script with no colors because I need to re-redirect logs output.

**Comment by usrme** [comment]
With this pull request (https://github.com/superfly/flyctl/pull/2585) being merged, there should now be support for `NO_COLOR` in the latest release of `flyctl`.

**Comment by usrme** [comment]
@dangra, I think this can be closed as well given the above.
