### ISSUE TITLE
0.0.96 release is missing assets

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#71]
Specifically - 
* flyctl_0.0.96_macOS_x86_64.tar.gz
* flyctl_0.0.96_Windows_x86_64.tar.gz
* flyctl_0.0.96_Linux_i386.tar.gz

Also - Brew is delivering 0.0.95 flyctl

**Comment by dyaa** [comment]
I was so confused 😄

**Comment by michaeldwan** [comment]
Good catch! It looks like the action couldn’t save the artifacts. Maybe this happened during the outage yesterday. I’ll try again shortly.

**Comment by codepope** [comment]
0.0.97 release should fix all issues.
