### ISSUE TITLE
Launching a new Ruby app is broken!

### ISSUE THREAD

**Issue by Qqwy** [superfly/flyctl#719]
**Describe the bug**

Creating a new Ruby app (such as by following the [Ruby guide](https://fly.io/docs/getting-started/ruby/#inside-fly-toml) to the letter) results in the following error:

```
fly launch
Creating app in /run/media/qqwy/Serendipity/Programming/Vanpelt/flytest2
Scanning source code
Detected a Ruby app
Using the following build configuration:
        Builder: heroku/buildpacks:20
? App Name (leave blank to use an auto-generated name): flytest2
? Select organization: Qqwy / Marten (personal)
? Select region: ams (Amsterdam, Netherlands)
Created app flytest2 in organization personal
Wrote config file fly.toml
? Would you like to deploy now? Yes
App is not running, deploy...
Deploying flytest2
==> Validating app configuration
--> Validating app configuration done
Services
TCP 80/443 ⇢ 8080
Error app does not have a Dockerfile or buildpacks configured. See https://fly.io/docs/reference/configuration/#the-build-section
```

This using Flyctl v. 0.0.280 ( `flyctl v0.0.280 linux/amd64 Commit: eea5515 BuildDate: 2022-01-06T13:55:37Z`)

This seems to be some kine of regression, as using v0.0.270 (`flyctl v0.0.270 linux/amd64 Commit: 7da8b26 BuildDate: 2021-12-17T22:27:41Z`) it works without any problems.

The `fly.toml` generated by both versions of the `flyctl` executable is identical.

**Comment by jsierles** [comment]
Thanks, we'll look into it!
