### ISSUE TITLE
Command `flyctl scale vm` does not work with no args as is documented

### ISSUE THREAD

**Issue by grempe** [superfly/flyctl#730]
**Describe the bug**
The docs say you can run `flyctl scale vm` with no args to view current VM type. This does not work as this command requires args.

https://fly.io/docs/reference/scaling/#viewing-the-current-vm-size

> Using flyctl scale vm on its own will display the details of the application's current VM sizing.

** Command output: **

```sh
❯ flyctl version
flyctl v0.0.282 darwin/amd64 Commit: 02c46ec BuildDate: 2022-01-12T17:44:39Z

❯ flyctl scale vm
Error: accepts 1 arg(s), received 0
Usage:
  flyctl scale vm [SIZENAME] [flags]

Flags:
  -a, --app string      App name to operate on
  -c, --config string   Path to an app config file or directory containing one (default "./fly.toml")
      --group string    The process group to apply the VM size to
  -h, --help            help for vm
      --memory int      Memory in MB for the VM

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
      --verbose               verbose output

Error accepts 1 arg(s), received 0
```

**Comment by jsierles** [comment]
Thanks for the report. The docs are wrong - you can use `fly scale show`. We'll get the docs updated.

**Comment by jsierles** [comment]
Closing this in favor of an issue on our docs repo.
