### ISSUE TITLE
Post-create instructions for "example.com" certificate creation

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#736]
People almost always want both `example.com` and `www.example.com` when they add one or the other, but it's not obvious they need to manually configure both. We'd save them a lot of agony if we just told them that. Something like:

> You've just created a certificate for `example.com`, make sure you create another certificate for `www.example.com`

**Comment by kurious-diru** [comment]
Hey, 

this looks like a decent task to get started on flyctl, may I work on this? thanks!

**Comment by jsierles** [comment]
Go for it!
