### ISSUE TITLE
[Question] UDP pass through

### ISSUE THREAD

**Issue by CommonLoon102** [superfly/flyctl#74]
Based on this page: https://fly.io/docs/services/
There is no UDP pass through, only TCP.
Can somebody confirm that it is the case? And that it is not just missing from the documentation.

**Comment by jeromegn** [comment]
UDP is not supported yet. It's definitely in the plans though as we want to do QUIC, DNS and UDP proxying in general.

**Comment by mrkurt** [comment]
Out of curiosity, what do you want to solve with UDP? There are some interesting problems routing stateless packets like that, most of what we've thought about is how to basically turn UDP protocols (like QUIC) into TCP for apps to consume.

**Comment by CommonLoon102** [comment]
Multiplayer games.

**Comment by mrkurt** [comment]
Oh neat! Do you have a particular game server engine you're using? I'm curious about logic for routing individual UDP packets to specific processes.

**Comment by CommonLoon102** [comment]
I don't know what you mean, maybe this fly.io stuff wouldn't be even good for the thing I want to use it for. Every process has its own port number that it listens to.

I was thinking about hosting this:
https://github.com/CommonLoon102/NBloodServerSupervisor

Not that it has a large community... It just would have been nice to deploy a server for free in EU too. One guy hosted this in Canada on his VPS so far.

But in general, hosting game servers would be easier, maybe(?).

**Comment by mrkurt** [comment]
Ah that's a good one! That's definitely something we'd like to make work, although it won't yet.
