### ISSUE TITLE
Confusion about '--builder' option

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#754]
**Describe the bug**
I'm getting an "unknown flag: --builder" error from this command:

    flyctl apps create --name x --builder Docker

This used to work.

It looks like things have changed quite a bit since then - I'm working my way through [the changelog](https://fly.io/blog/topic/changelog/) and I think I need to switch to `fly create` now, though that doesn't support `--builder` either.

If `--builder` has indeed been removed then here is a definite bug:

```
% flyctl create --help
The CREATE command will both register a new application 
with the Fly platform and create the fly.toml file which controls how 
the application will be deployed. The --builder flag allows a cloud native 
buildpack to be specified which will be used instead of a Dockerfile to 
create the application image when it is deployed.
```
The `--help` output for `flyctl create` still says "The --builder flag allows..." - so it looks like that help wasn't updated when `--builder` was removed.

**Comment by simonw** [comment]
This page of documentation also mentions the `--builder` flag: https://fly.io/docs/flyctl/apps-create/

**Comment by simonw** [comment]
The context here is that I'm trying to create an app with a volume that I can write SQLite files to.

As far as I can tell, `flyctl launch` won't work for this because I need to create a volume before I deploy my app - but you can't create a volume without first creating the app. Since `launch` combines app creation and deploy it doesn't work for me, because I need to create the volume in between those two operations.

**Comment by jsierles** [comment]
Thanks for raising this. You can use `fly launch --no-deploy`, then create the volume, then deploy. However, you would still need to update `fly.toml` to add the volume to the `mounts` section. One way to do this automatically is `fly launch --no-deploy --copy-config` with an existing `fly.toml` with the mounts and builder section already set.

We'll take a look at the documentation and update accordingly.

**Comment by simonw** [comment]
Related:
- https://github.com/superfly/flyctl/issues/767

**Comment by simonw** [comment]
> Thanks for raising this. You can use `fly launch --no-deploy`, then create the volume, then deploy

Is there any benefit to using `fly launch --no-deploy` over `fly apps create` followed by `fly deploy` if I'm going to be manually creating my own `fly.toml` and creating my own volumes?

**Comment by jsierles** [comment]
No benefit! `launch` is really more of a 'help get started' command.

**Comment by jsierles** [comment]
Closing in favor of #767
