### ISSUE TITLE
fly deploy runs locally on aarm

### ISSUE THREAD

**Issue by grepsedawk** [superfly/flyctl#756]
**Describe the bug**
`fly deploy` on the m1 results in a local docker build, instead of automatically calling `--remote-only`

** Command output: **

Runs docker build, but locally instead of using remote builder

**Comment by jsierles** [comment]
Builds on M1 are not disabled if there's a Docker installation available. This was briefly the case, but was [quickly reverted](https://github.com/superfly/flyctl/pull/544).
