### ISSUE TITLE
Deploy doesn't detect all lowercase `dockerfile`

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#76]
This seems like it's especially a problem on Windows. Docker does fine with one though!

**Comment by dyaa** [comment]
Shouldn't the naming convention of the file be `Dockerfile` instead of all lowercase?

**Comment by mrkurt** [comment]
@dyaa yes but it appears Docker proper supports lowercase `dockerfile`, and we want `flyctl deploy` and `docker build .` to behave the same as much as possible. I have a feeling they relaxed that a bit for case insensitive file systems.

**Comment by dyaa** [comment]
Valid point 👍
