### ISSUE TITLE
Can't authenticate on Arch Linux

### ISSUE THREAD

**Issue by AndrewVos** [superfly/flyctl#764]
**Describe the bug**

I can't authenticate on Arch Linux

I have tried the installer on https://fly.io/docs/getting-started/installing-flyctl/ and also the AUR package.

```sh
~ fly auth login
WARN failed querying for new release: Get "https://api.fly.io/app/flyctl_releases/linux/amd64/latest": dial tcp: lookup api.fly.io on [::1]:53: read udp [::1]:38671->[::1]:53: read: connection refused
Error Post "https://api.fly.io/api/v1/cli_sessions": dial tcp: lookup api.fly.io on [::1]:53: read udp [::1]:38671->[::1]:53: read: connection refused


~ curl https://api.fly.io/app/flyctl_releases/linux/amd64/latest
https://github.com/superfly/flyctl/releases/download/v0.0.286/flyctl_0.0.286_Linux_x86_64.tar.gz⏎    
```

**Comment by jsierles** [comment]
Are you able to reach `api.fly.io` in general? For example with `curl api.fly.io`.

**Comment by AndrewVos** [comment]
@jsierles yep, take a look at the code snippet I pasted.

**Comment by michaeldwan** [comment]
@AndrewVos Are you still having this issue? I'm not sure why dns is failing, but an update check it absolutely shouldn't be causing commands to fail. We'll take a look at that separately. In the meantime, can you try that again with `FLY_UPDATE_CHECK=0 flyctl auth login`?

**Comment by michaeldwan** [comment]
@azazeal any idea why the update check error is bubbling up to the caller?

**Comment by azazeal** [comment]
This isn't an error from the update check. Yes, the update check fails and that results in a warning but the terminal error the program encounters is during the `POST` to `https://api.fly.io/api/v1/cli_sessions`.

The specific error that renders the program unable to continue happens during DNS lookup and is this:

```
lookup api.fly.io on [::1]:53: read udp [::1]:38671->[::1]:53: read: connection refused
```

Does the error still persist for you, @AndrewVos?

**Comment by AndrewVos** [comment]
Hiya, I've found that if `resolv.conf` specifics nameservers then the error goes away.

I think it's because golang uses `resolv.conf` internally, but not sure. 

The Arch Linux wiki specifically mentions that not having a nameserver there can break things, so I think this is my bad.

Sorry about the confusion, but I think maybe this ticket can be closed?

**Comment by azazeal** [comment]
There's really no need to apologize, @AndrewVos :) Thank you for both using Fly and for your report!
