### ISSUE TITLE
Display logs when agent fails to start

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#774]
I'm testing agent start failures by running `touch ~/.fly/fly-agent.sock` then a command that needs the agent, like `flyctl dig _apps.internal -a debug`.

Here's some example output

```
$ flyctl dig _apps.internal -a debug
INFO started agent process (pid: 16530, log: /Users/md/.fly/agent-logs/2643414345.log)
Error agent: failed to start


The agent failed to start. You may review the log file here: /Users/md/.fly/agent-logs/2643414345.log
```

Printing the log file path is a big improvement to help debug, but it would also be great if `flyctl` read the last _n_ lines from that file and printed it along with the error message. This will make it more obvious what failed when running interactively, and include some failure logs if running in CI.

**Comment by azazeal** [comment]
This is an agent _start_ error, so it'll be maybe _a_ line long. I'll include it to the output.

**Comment by azazeal** [comment]
This is how this would look in the related PR I opened a while ago:

```bash
$ touch ~/.fly/fly-agent.sock
$ flyctl agent start
Error failed establishing connection to agent: agent: failed to start


The agent failed to start with the following error log:

2022/01/27 15:20:35.006334 srv failed removing existing socket: not a socket


A copy of this log has been saved at /home/azazeal/.fly/agent-logs/3166058538.log
```

You can go ahead and merge if that's OK :)
