### ISSUE TITLE
status and info are too similar

### ISSUE THREAD

**Issue by jeromegn** [superfly/flyctl#78]
I never know which one I should use to see the information I want.

Maybe they could be unified or renamed more distinctly.

**Comment by codepope** [comment]
As it is currently interpreted, info is the static configuration of the app, status is the dynamic configuration for allocations. They look similar because the app info appears at the top for both.

```
❯ flyctl status
App
  Name     = hellodeno-dockerfile
  Owner    = dj
  Version  = 79
  Status   = running
  Hostname = hellodeno-dockerfile.fly.dev

Allocations
ID       VERSION REGION DESIRED STATUS  HEALTH CHECKS      RESTARTS CREATED
178d3616 79      ams    run     running 1 total, 1 passing 0        2020-06-22T14:31:33Z
c6245100 79      fra    run     running 1 total, 1 passing 0        2020-06-22T14:30:30Z
db262269 79      mrs    run     running 1 total, 1 passing 0        2020-06-22T14:30:55Z


~/demobox/hellodeno-dockerfile master
❯ flyctl info
App
  Name     = hellodeno-dockerfile
  Owner    = dj
  Version  = 79
  Status   = running
  Hostname = hellodeno-dockerfile.fly.dev

Services
PROTOCOL PORTS
TCP      80 => 8080 [HTTP]
         443 => 8080 [TLS, HTTP]

IP Adresses
TYPE ADDRESS                              CREATED AT
v4   77.83.140.153                        2020-05-14T12:23:16Z
v6   2a09:8280:1:2d25:fb3e:66b3:de90:905b 2020-05-14T12:23:16Z
```

So, if we make status purely about the dynamic allocations...

```
❯ flyctl status
App
  Name     = hellodeno-dockerfile
  Version  = 79
  Status   = running

Allocations
ID       VERSION REGION DESIRED STATUS  HEALTH CHECKS      RESTARTS CREATED
178d3616 79      ams    run     running 1 total, 1 passing 0        2020-06-22T14:31:33Z
c6245100 79      fra    run     running 1 total, 1 passing 0        2020-06-22T14:30:30Z
db262269 79      mrs    run     running 1 total, 1 passing 0        2020-06-22T14:30:55Z
```

That would tighten up status - info could remain as is.

If we unify them it gets pretty crowded ....

We could tho drop the services entry from the list and give it its own command (services list) (like ips already - flyctl ips list) - flyctl info could be dropped and we can put all the fields back in status.....

```
$ flyctl status
App
  Name     = hellodeno-dockerfile
  Owner    = dj
  Version  = 79
  Status   = running
  Hostname = hellodeno-dockerfile.fly.dev

Allocations
ID       VERSION REGION DESIRED STATUS  HEALTH CHECKS      RESTARTS CREATED
178d3616 79      ams    run     running 1 total, 1 passing 0        2020-06-22T14:31:33Z
c6245100 79      fra    run     running 1 total, 1 passing 0        2020-06-22T14:30:30Z
db262269 79      mrs    run     running 1 total, 1 passing 0        2020-06-22T14:30:55Z
```

No info command apart from maybe explaining where to find information in a friendly way?

**Comment by michaeldwan** [comment]
@codepope taking services out of status sounds good. The service list is only relaying what came out of the config file so it might not need a command yet

**Comment by codepope** [comment]
flyctl config display - currently dumps a JSONish config...

I don't think anyone uses that, so either retire it and replace it with config show (ready for the great recommanding ... show config)... something.

So scoping the changes
Services out of status
Rework the config display to show status readably
Kill the info command (with a guide to finding out about your app as a transitional phase)

**Comment by jsierles** [comment]
There are too many things in this issue, and some have been resolved. So let's open new issues for:

* Dropping `fly config display`
* Add `fly config show` with recommendations
* Removing `fly info`
* Adding a separate `fly services` command
