### ISSUE TITLE
`flyctl regions list --json` doesn't match output from `flyctl regions list`

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#788]
For example:
```
% flyctl regions list -a squirrel-map       
Region Pool: 
sjc
Backup Region: 
lax
sea
% flyctl regions list -a squirrel-map --json
[
    {
        "Code": "sjc",
        "Name": "Sunnyvale, California (US)",
        "Latitude": 0,
        "Longitude": 0,
        "GatewayAvailable": false
    }
]
```
The "Backup region" section from the non-JSON version is not reflected in the JSON output.

**Comment by simonw** [comment]
I was also hoping to find a way to list all of the regions that are possible options for deploying a brand new app - but `flyctl regions list` currently requires an app name, so it doesn't seem right for the question of "where can I deploy a new app that I am about to create?".

**Comment by simonw** [comment]
I found a way of listing all available regions (I think) - using the following GraphQL query to https://api.fly.io/graphql

```graphql
{
  __schema {
    types {
      name
      enumValues {
        name
        description
      }
    }
  }
}
```
Then scanning through the output for the `RegionEnum` definition:
```json
{
  "name": "RegionEnum",
  "enumValues": [
    {
      "name": "AMS",
      "description": "Amsterdam, NL"
    },
    {
      "name": "ATL",
      "description": "Atlanta, US"
    },
    {
      "name": "DFW",
      "description": "Dallas, US"
    },
    {
      "name": "EWR",
      "description": "New York, US"
    },
    {
      "name": "FRA",
      "description": "Frankfurt, DE"
    },
    {
      "name": "HKG",
      "description": "Hong Kong, CN"
    },
    {
      "name": "IAD",
      "description": "Virginia, US"
    },
    {
      "name": "LAX",
      "description": "Los Angeles, US"
    },
    {
      "name": "NRT",
      "description": "Tokyo, JP"
    },
    {
      "name": "ORD",
      "description": "Chicago, US"
    },
    {
      "name": "SEA",
      "description": "Seattle, US"
    },
    {
      "name": "SIN",
      "description": "Singapore, SG"
    },
    {
      "name": "SJC",
      "description": "San Jose, US"
    },
    {
      "name": "SYD",
      "description": "Sydney, AU"
    },
    {
      "name": "YYZ",
      "description": "Toront, CA"
    }
  ]
}
```

**Comment by rugwirobaker** [comment]
> I was also hoping to find a way to list all of the regions that are possible options for deploying a brand new app - but `flyctl regions list` currently requires an app name, so it doesn't seem right for the question of "where can I deploy a new app that I am about to create?".

What you are looking for is `flyctl platform regions`

**Comment by rugwirobaker** [comment]
@simonw thank you for bringing this to our attention by the way. We're trying to make flyctl more script friendly. There is an incoming PR that will fix this and a couple of others cases like this one.
