### ISSUE TITLE
Flag to force remote builds

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#80]
https://news.ycombinator.com/item?id=22619414

**Comment by simonw** [comment]
I'd really appreciate this, just because I don't fully trust the internet at the moment (I'm getting worse performance now that everyone's home for the pandemic) so I'd much rather push a few hundred bytes of Dockerfile than run the build on my laptop and then push the resulting image.

**Comment by michaeldwan** [comment]
@simonw this is now released. `flyctl deploy --remote-only`. Thanks for the suggestion!

**Comment by simonw** [comment]
The documentation didn't cover upgrading, but I figured out it's `brew upgrade superfly/tap/flyctl` on OS X with Homebrew.

**Comment by simonw** [comment]
Tiny detail: when you use this command it still outputs the following, which is a tiny bit misleading since the Docker daemon may still be available:
```
Docker daemon unavailable, performing remote build...
```

**Comment by michaeldwan** [comment]
Good point, I'll tidy that up!
