### ISSUE TITLE
Something scanned my app shortly after I deployed it

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#81]
Not sure if this is something I should post here, but I found it interesting. I deployed my first app to Fly a few hours ago and I just ran `flyctl logs -a lively-bush-4573` and spotted this:
```
2020-03-18T21:36:52.992Z 25a14f0e sjc [info] [32mINFO:  
  147.75.70.177:54302 - "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1"
  404 Not Found
```
Looks like someone is scanning for vulnerabilities. What's interesting to me is that I don't know how they found my URL to scan - I haven't linked to it from anywhere.

Oh... each of my apps gets assigned a unique IP address, right? So I guess someone is scanning IP ranges.

Feel free to close this.

**Comment by michaeldwan** [comment]
Heh yes every IP and LE cert seems to get scanned for an hour after launching. It's annoying *shakes fist at cloud*
