### ISSUE TITLE
Signup fails, sign in succeeds with error. Is your IPv6 broken?

### ISSUE THREAD

**Issue by SleeplessByte** [superfly/flyctl#817]
> ℹ️ I do not need help signin in or up, as `flyctl auth whoami` returns my e-mail address. The sign up experience was jarring, and there seems to be some sort of issue with connecting to `api.fly.io` on Windows. This may definitely be a problem with _my setup_, but given that this is an almost brand new installation of the OS without any extra firewall setup, this may be a problem for more people.
>
> Microsoft Windows 11 Pro
> Version	10.0.22000 Build 22000
>
> No extra firewall
> No pihole
> No custom DNS

## Describe the bug
Following <https://fly.io/docs/getting-started/log-in-to-fly/> I am on Windows 11.

### Installing
 `iwr https://fly.io/install.ps1 -useb | iex` in PowerShell. Succeeds without warning

> flyctl was installed successfully to C:\Users\Derk-Jan\.fly\bin\flyctl.exe
> Run 'flyctl --help' to get started

### Sign-up
So I wanted to sign up:

```shell
$ flyctl auth signup
Error Post "https://api.fly.io/api/v1/cli_sessions": read tcp [<snip>]:55807->[<snip>]:443: wsarecv: An existing connection was forcibly closed by the remote host.
```

I tried a few more times, also in a new shell. Could not get it to work. 

I tried `flyctl --help` instead, to see if it was correctly installed (it was), and then ran `flyctl auth --help` to find out I could just try to login

### Login

```shell
$ flyctl auth login
WARN failed querying for new release: Get "https://api.fly.io/app/flyctl_releases/windows/amd64/latest": read tcp [<snip>]:54496->[<snip>]:443: wsarecv: An existing connection was forcibly closed by the remote host.
Opening https://fly.io/app/auth/cli/<snip> ...
```

I was shown an _error_ (similar to the error above) but the browser automatically reloaded (instantly) and showed me a sign in page. I pressed Sign In with GitHub (which I had never done before), and authorized fly.io. 

I was redirected to an "empty" page with an error message:

> CLI Session Expired, please restart the process

However, on my PowerShell:

```shell
Waiting for session... Done
successfully logged in as derk-jan<snip>@<snip>
```

Retrying the command to login shows the same warning for "failed quering for new release" but allows me to login again with my GitHub (via a quick button) and then it goes throw without CLI Session Expired error.

## Trying DNS settings to resolve

When configuring ipv4 DNS by CloudFlare (which should synthetically resolve IPv6 as well), <https://test-ipv6.com/> gives a 10/10 and <https://ipv4.google.com/> loads correctly meaning both IPv6 and IPv4 are correctly working. However, if I now try to `whoami`:

>failed retrieving current user: Post "https://api.fly.io/graphql": read tcp [<my ipv6>]:55057->[2a09:8280:1:f28:246e:d6a:949:dbbf]:443: wsarecv: An existing connection was forcibly closed by the remote host.

There seems to be something wrong with the IPv6 connection on `fly.io`'s end, which seemed to happen in Chrome too right before it reloaded. I have no clue how to further debug or resolve this, and I am fine relying on manual updates and turning off CloudFlare DNS for now, but this seems like something that's not actually broken on my end.

Let me know if I can provide further information to revolve this.

**Comment by jsierles** [comment]
Thanks for the report. This repo is for more specific `flyctl` bugs, and is not monitored by that many people. Can you repost this on https://community.fly.io? Thanks!

**Comment by SleeplessByte** [comment]
Will do!

**Comment by michaelbromley** [comment]
Dropping this here as we ran into the same issue, and there was no solution to be found on the community forum:

The solution for us was found in the following tweet from a Fly.io employee: https://twitter.com/mrkurt/status/1533489925575872512

> Maybe try ipv4? You can make a hosts entry pointing [http://api.fly.io](https://t.co/ohrYOlLl1w) -> 77.83.143.220 to do that, I think.

**Comment by jonhoo** [comment]
For anyone else who ends up here, this appears to be because `fly` and `flyctl` both require a DNS resolver to be running `[::1]:53` (i.e., on the IPv6 localhost address). To force `systemd-resolved` to do that, you can add
```
DNSStubListenerExtra=[::1]:53
```
to `/etc/systemd/resolved.conf` (see [this SO answer](https://askubuntu.com/a/1420958)).
