### ISSUE TITLE
datasette-publish-fly - a plugin I built with Fly

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#82]
Hi team,

I'm really excited about Fly - I'm always interested in new Docker hosting options, and Fly looks like a really great addition to the ecosystem.

My project [Datasette](https://datasette.readthedocs.io/) is a tool for exploring and publishing data. It's a web application that provides a UI and JSON API on top of a SQLite database. It also has a set of tools for publishing SQLite databases wrapped in Datasette to different hosting providers.

Datasette comes with a command for publishing data, which currently works with Cloud Run, Heroku and the deprecated Zeit Now v1:

    $ datasette publish heroku my-database.db
    $ datasette publish cloudrun my-database.db
    $ datasette publish nowv1 my-database.db

This mechanism can be extended to support new hosting providers via [a plugin hook](https://datasette.readthedocs.io/en/stable/plugins.html#publish-subcommand-publish). So I built a plugin for Fly!

https://github.com/simonw/datasette-publish-fly

If you install this plugin you get a new option that looks like this:

    $ datasette publish fly my-database.py --app myapp

Here's an example Datasette instance: https://datasette-demo.fly.dev/

I deployed it like so:
```
$ datasette publish fly trees.db fixtures.db --app datasette-demo
Selected App Name: datasette-demo
? Select organization: Simon Willison (simon-willison)
New app created
  Name     = datasette-demo  
  Owner    = simon-willison  
  Version  = 0               
  Status   =                 
  Hostname = <empty>         

Wrote config file fly.toml
==> Validating app configuration
...
Successfully built 74ff85999177
Successfully tagged registry.fly.io/datasette-demo:build-moyw73qel934xjk5
Image: registry.fly.io/datasette-demo:build-moyw73qel934xjk5
Image size: 1.1 GB
==> Pushing image
The push refers to repository [registry.fly.io/datasette-demo]
cb3c592d5833: Preparing
...
271910c4c150: Pushed
build-moyw73qel934xjk5: digest: sha256:80641567cb3603115daac53d04f2c5b9bcc8267c17557d25d91312d8685bd1ba size: 2853
--> done
Image: registry.fly.io/datasette-demo:build-moyw73qel934xjk5
[2020-03-19T01:58:58+00:00]
Build complete - succeeded
==> Optimizing image
--> done
==> Creating Release
Release v0 created
==> Monitoring Deployment
You can detach the terminal anytime without stopping the deployment
v0 is being deployed
1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
v0 deployed successfully
```
I'm posting this here partly because I thought you'd be interested, but also because I'd like to get a sanity-check that I'm using Fly in the right way here.

The plugin works by shelling out to the `flyctl` command - you can see the code here: https://github.com/simonw/datasette-publish-fly/blob/c95c21d22fc70396eb55afa5c91cc343f60af607/datasette_publish_fly/__init__.py#L106-L115

Currently I'm forcing users to specify a `--app` name, rather than using your default randomly created ones. The reason for this is that I worry about people deploying too many different applications, and running out of budget. I want to make it as easy as possible for my users to deploy a new version of an app that overwrites the previous one, and to do that I need them to reuse the same app name to update their existing app.

I also needed to figure out if I should run the `flyctl apps create` command or not. I'm currently doing that by checking your requested app name against a list of existing apps, obtained by parsing the output of `flyctl apps list` - which means if you change the output of that command my parser will break!

A `flyctl apps list --json` option for outputting that data as JSON would be useful here.

The command also pauses for an interactive selection of the user's organization the first time they run a deploy. I'd like it if I could avoid this entirely, but there doesn't seem to be a way of saying "use the default organization when creating this app" when running `flyctl apps create`.

Would love to get your feedback on this, I only just released the first alpha version.

Thanks,

Simon

**Comment by simonw** [comment]
```
Usage:
  flyctl apps create [APPNAME] [flags]

Flags:
      --builder string   The Cloud Native Buildpacks builder to use when deploying the app
  -h, --help             help for create
      --name string      The app name to use
      --org string       The organization that will own the app
  -p, --port string      Internal port on application to connect to external services
```
It looks like I can pass the organization name to `flyctl apps create`, which could fix my problem with the interactive question asked during a deploy... but there doesn't seem to be a mechanism for listing organizations so I can automatically pick one (`flyctl organizations list` might be useful).

**Comment by simonw** [comment]
Wrote about this here: https://simonwillison.net/2020/Mar/25/weeknotes/#weeknotes-datasette-publish-fly

**Comment by codepope** [comment]
Hi @simonw I'm just doing a blog post for the fly blog about this. Drop me a line at dj@fly.io.

**Comment by mrkurt** [comment]
Community content 🙌 

https://fly.io/blog/making-datasets-fly-with-datasette-and-fly/
