### ISSUE TITLE
'fly ssh' should throw a clearer error when trying to ssh to an app without VMs

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#826]
An unhealthy or undeployed app will have no hosts to contact, so we see this unhelpful error:

```
$ fly ssh console
Waiting for host ⣟ Error host unavailable: no such host
```

This error could at least give more useful information like:

```
We couldn't find any VMs for this application. It may be unhealthy or not have been deployed yet. Try these commands to verify:

fly status
fly ips private
```

**Comment by redjonzaci** [comment]
I could work on this, but I am not sure if still needed.

**Comment by jsierles** [comment]
If you're not sure if an issue is valid, try it out and see, then use your best judgment if it's worth changing.

**Comment by redjonzaci** [comment]
I now get: "Error: app APP-NAME has no started VMs",
but I can append the part about suggested actions.
