### ISSUE TITLE
Documentation for "flyctl scale vm" could do with more details

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#83]
I'm trying to figure out how to scale my instance up from the default `micro-1x`.

It looks like I need to use `flyctl scale vm` - but the docs at https://fly.io/docs/flyctl/scale-vm/ don't specify how the `SIZE` parameter should be used.

At a guess I feed it one of the "type" values on https://fly.io/docs/pricing/ - but it would be great if the documentation page for that command was expanded to include some examples.

**Comment by simonw** [comment]
If the documentation was in a public GitHub repo I'd be happy to open pull requests against it.

**Comment by mrkurt** [comment]
Those docs are actually generated from this project: https://github.com/superfly/flyctl/blob/master/helpgen/flyctlhelp.toml#L247

Right now it references `flyctl platform vm-sizes`, which might be new since you submitted this issue, but putting some sizes in the help directly is a good idea.

**Comment by codepope** [comment]
More details now in PR #90
