### ISSUE TITLE
I can't access my account settings because I signed up with GitHub

### ISSUE THREAD

**Issue by simonw** [superfly/flyctl#86]
I created my Fly account by signing in with GitHub, so that I wouldn't have to create a new password.

When I click "Settings" in the menu:

<img width="397" alt="apps___Fly_io" src="https://user-images.githubusercontent.com/9599/77119539-e51bdf80-69f3-11ea-81d8-b57115e6dce0.png">

I get this screen: https://fly.io/app/sign-in/refresh

<img width="652" alt="Refresh_session_·_Fly" src="https://user-images.githubusercontent.com/9599/77119570-f49b2880-69f3-11ea-9124-55d1a4f9bc5f.png">

But I don't have a password so I can't verify it here.

**Comment by simonw** [comment]
Also the placeholder text "Something hard to guess" here is confusing - it made me think "maybe this is a form where I set a new password?" - but it's not.

**Comment by mrkurt** [comment]
@simonw ahh good catch. Our password confirmation doesn't make much sense for signups from Github. For now, you'll need to use the password reset function to set a new password: https://fly.io/app/password_resets/new

We'll figure that out, I think we might be able to bounce you through Github to re-auth or something.

That placeholder text _is_ confusing. Good call.

**Comment by simonw** [comment]
OK, that worked - I had to sign out, then click "Reset password". Your reset password screen needs a bit of a touch-up!

<img width="718" alt="Fly_and_Lifecycle_hooks_-_Watchtower" src="https://user-images.githubusercontent.com/9599/77120411-07aef800-69f6-11ea-8d1c-ae031776e919.png">
