### ISSUE TITLE
Nit:`fly launch` + auto-detected Remix app = extraneous `start_with_migrations.sh` file

### ISSUE THREAD

**Issue by cweekly** [superfly/flyctl#861]
Tiny nit. 

macOS Monterey
fly v0.0.303 darwin/amd64 Commit: d09e39d BuildDate: 2022-03-08T00:22:46Z

```text
npx create-remix@latest
...
fly launch
...

git status
?? .dockerignore
?? Dockerfile
?? fly.toml
?? start_with_migrations.sh

cat start_with_migrations.sh

#!/bin/sh

set -ex
npx prisma migrate deploy
npm run start

```

Looks specific to the original remix jokes app (which uses prisma).

**Comment by jsierles** [comment]
That script should only be installed if prisma is installed in the app and uses `sqlite` as its database. You can't use Sqlite without a script like this that runs migrations at boot time.
