### ISSUE TITLE
Dockerfile not running

### ISSUE THREAD

**Issue by gregpalaci** [superfly/flyctl#874]
sorry for the simple question but who could I run ```docker run -d --name vaultwarden -v /vw-data/:/data/ -p 80:80 vaultwarden/server:latest```

I've tried with Dockerfile
```
FROM vaultwarden/server

EXPOSE "8011:80"

VOLUME "/data/:/data/"
```

**Comment by jsierles** [comment]
This repo is for issues and bugs specific to the flyctl CLI. Can you post on https://community.fly.io where more people will see this? Thanks!
