### ISSUE TITLE
Flask App misrecognized as Django App by flyctl launch

### ISSUE THREAD

**Issue by staeff** [superfly/flyctl#878]
**Describe the bug**

The flask app [https://github.com/fly-apps/python-hellofly-flask](https://github.com/fly-apps/python-hellofly-flask) from the tutorial [https://fly.io/docs/getting-started/python/](https://fly.io/docs/getting-started/python/) is recognized as Django app by `flyctl launch`. Therefore it uses the Docker template for Django, which has specific commands, that don't work with Flask.

* MacOS Monterey
* fly v0.0.306 darwin/amd64 Commit: b5101f2 BuildDate: 2022-03-15T18:17:35Z

Could it be that the `configureDjango` checker `checksPass` even if there is only `requirements.txt` and not `manage.py`?

[https://github.com/superfly/flyctl/blob/8460965950c02314a7d4d4510202b5423db44e19/internal/sourcecode/scan.go#L479](https://github.com/superfly/flyctl/blob/8460965950c02314a7d4d4510202b5423db44e19/internal/sourcecode/scan.go#L479)

**Comment by staeff** [comment]
Some additional info on this: https://github.com/superfly/flyctl/blob/8460965950c02314a7d4d4510202b5423db44e19/internal/sourcecode/helpers.go#L10 - is the `fileExists` function and I have the sneaking suspicion it happily returns true, if just one condition holds true. So it evaluates to true even when `manage.py` does not exist and therefore generated to wrong Dockerfile.

**Comment by hemmer** [comment]
Is there a known workaround for this?

**Comment by benwaffle** [comment]
The linked flask app (https://github.com/fly-apps/python-hellofly-flask) is no longer detected as Django app.
