### ISSUE TITLE
brew install requires xcode command line tools for some reason

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#880]
I've seen this a few times now, people being forced to install xcode CLI tools when they install flyctl from brew: https://twitter.com/patio11/status/1506729385721704450

It shouldn't need it! It'd be better not to require a ginormous download to get our single Go binary. :)

**Comment by jsierles** [comment]
Maybe related:

https://github.com/Homebrew/discussions/discussions/3102
https://github.com/goreleaser/goreleaser/issues/2914

**Comment by darthShadow** [comment]
Is there any specific reason this is being distributed through a custom tap rather than being part of the core homebrew formulae?

That should give you bottles which shouldn't require installing xcode CLI tools.

**Comment by mrkurt** [comment]
That's a good question! The simple answer is that we weren't big enough to be relevant when we created the tap. But it looks like we fit the guidelines now: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by darthShadow** [comment]
https://github.com/Homebrew/homebrew-core/pull/97781

**Comment by jsierles** [comment]
Nice 💯

**Comment by jsierles** [comment]
If this is accepted, will we need to change the goreleaser task to publish it?

**Comment by darthShadow** [comment]
I don't think goreleaser supports creating a PR to bump the version: https://github.com/goreleaser/goreleaser/issues/1139

You will probably need to use this action instead as a part of the workflow: https://github.com/dawidd6/action-homebrew-bump-formula

**Comment by darthShadow** [comment]
PR has been merged to Homebrew and the formula is now available. The next step would probably be to add the above linked action after running goreleaser as part of the github release workflow and if that works, remove the reference to the custom tap from the README and point to the official homebrew formula instead.

**Comment by jsierles** [comment]
Thanks @darthShadow. I'm working on the releaser now.

**Comment by jsierles** [comment]
The releaser [seems to be working](https://github.com/Homebrew/homebrew-core/pull/98046), so closing. 👏
