### ISSUE TITLE
Allow `--build-arg "file:/..."

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#886]
People pass file paths in as builds args for Prisma. The last flyctl with build arg processing tries to read those, and breaks peoples' deploys.

I reverted this change while we figure out a better mechanism. It doesn't look like we rely on that file loading yet: https://github.com/superfly/flyctl/commit/7af5c27708d5ea328370199ef2322d5e6b5cfbf7

**Comment by jsierles** [comment]
Yeah, this turned out not to be needed for Rails. Such a mechanism might be useful, but shouldn't be done in this hackish way (note to self).
