### ISSUE TITLE
It'd be nice to use local `builder` directories

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#9]
Maybe something like `flyctl build --builder /path/to/my/dev/builder/`.

I'm trying to make a `static` builder work and it's just slightly different enough from docker build to give me hives.

**Comment by michaeldwan** [comment]
We're using [go-getter](https://github.com/hashicorp/go-getter) to fetch builders and should support everything it supports, though I've only tested remote git, local git, and local paths.

Here's how to use a local directory from fly.toml:

```toml
[build]
  builder = "../builders//fly-js"
```

Note the double slash is important to fetch only the `fly-js` subdirectory from the `../builders` git repo directory.
