### ISSUE TITLE
flyctl freezes my network on my MacBook Pro M1 Max

### ISSUE THREAD

**Issue by patlux** [superfly/flyctl#903]
**Describe the bug**
Briefly, describe what broke and provide the following details:

Not sure since when this occurs. But when I run a task which needs a network connection, my network freezes after some time and then **only a restart helps**. I can't even exit the process. `Ctrl+C` etc. doesn't work.

It doesn't matter which command I'm using. If it's `fly deploy` or something simpler like `fly auth whoami`.

* Operating system: macOS 12.3.1
* `fly version`: flyctl v0.0.312 darwin/arm64 Commit: 66fc69d BuildDate: 2022-04-01T15:36:17Z

```sh
$ which flyctl
/opt/homebrew/bin/flyctl
```

** Paste your `fly.toml`

Doesn't matter

** Command output: **

Doesn't matter
![CleanShot 2022-04-04 at 16 03 49](https://user-images.githubusercontent.com/4481570/161565431-137a43ab-3349-4d22-855c-3e57b23744eb.png)

![CleanShot 2022-04-04 at 16 04 16](https://user-images.githubusercontent.com/4481570/161565438-65a21655-6897-4716-a142-324f4cd1d0b5.png)

![CleanShot 2022-04-04 at 08 58 14@2x](https://user-images.githubusercontent.com/4481570/161565413-5b4ce1ce-a1bd-4fb2-add8-a9d2471ce866.png)

![CleanShot 2022-04-04 at 16 27 30](https://user-images.githubusercontent.com/4481570/161565943-999f410e-a26b-4e77-b624-d95850c7de79.png)

Please, tell me what you need for information. I will provide anything to fix this...

**Comment by patlux** [comment]
Even restarting is a nightmare. The last opened application just won't close. Doesn't matter how often I click "Force quit" it just won't close. And macOS doesn't allow restarting if a application is still open. It's ridiculous. How in the earth can a small cli tool just kill my whole system?

**Comment by jsierles** [comment]
Thanks for the report. Are you using a VPN or do you have something like [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) installed?

**Comment by patlux** [comment]
Hi @jsierles, yes I'm using Little Snitch

**Comment by jsierles** [comment]
We've seen reports of LS causing problems on OSX Monterey. Here's one [report for another tool](https://github.com/zerotier/ZeroTierOne/issues/1523#issuecomment-1023521022). Our CLI is making simple HTTP requests for commands like `fly auth whoami`.

**Comment by mrkurt** [comment]
@patlux are you running Tailscale or the Wireguard UI app along with Little Snitch by chance? Monterey changed network extensions and it sounds like conflicts are a problem.

Our `flyctl agent` speaks Wireguard, but it does not have permissions to mess with networking. It wouldn't surprise me at all to find out that Wireguard traffic from that is triggering Little Snitch problems.

**Comment by patlux** [comment]
I'm using all of them you mentioned.

But I already closed Tailscale and Wireguard and the issue still occurred. Only after disabling Little Snitch in the Network preferences helped me.

It worked fine a while ago. I think it started with the uprade to 12.3.1

**Comment by karniv00l** [comment]
I'm having the same issue 

I believe the problem and resolution is described here: https://github.com/planetscale/discussion/discussions/181

**Comment by karniv00l** [comment]
Solved by building with `CGO_ENABLED=1`

**Comment by redjonzaci** [comment]
@michaeldwan can we close this?
