### ISSUE TITLE
Frameworks that plant Dockerfiles are detected as Dockerfile apps

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#907]
Rerunning `fly launch` on apps that plant Dockerfiles lead to the surprising behavior of the app being detected as `Dockerfile`. This prevents such apps from getting their `[env]` settings or anything else from launch scanners.

flyctl should detect framework apps first, and warn if they already contain Dockerfiles that may get overwritten by `fly launch`.

**Comment by staeff** [comment]
#878 is another case of surprising behaviour of fly launch

**Comment by alichay** [comment]
At some point, this happened :)
https://github.com/superfly/flyctl/blob/43d99f535a25a54f39b3f46aca8be140a07b602f/scanner/scanner.go#L79-L99
