### ISSUE TITLE
flyctl should validate fly.toml before initiating a build

### ISSUE THREAD

**Issue by rugwirobaker** [superfly/flyctl#932]
The validation method we are using to catch mistakes in `fly.toml` before initializing a  build on commands like `fly deploy` might be different from what the API is using. We sometimes get a validation error just as a new release is about to be deployed, which can be frustrating after waiting for a very large build.

**Comment by jsierles** [comment]
We now have a mostly-accurate [JSON schema](https://github.com/superfly/taplo/blob/fly-toml/schemas/fly.toml.json) to use for validation. `taplo` is in Rust, unfortunately. I have not found a TOML validator in Goland that would work with this schema. Marshalling first to JSON could work, but may not give very user-friendly output.

**Comment by jsierles** [comment]
I found this https://github.com/the4thamigo-uk/conflate
