### ISSUE TITLE
can’t use command ’ flyctl ssh issue –agent’ in windows

### ISSUE THREAD

**Issue by lyj0309** [superfly/flyctl#949]
when i want to issue a new ssh key, the flyctl goes worng like this in windows.
![image](https://user-images.githubusercontent.com/50474995/165548826-3e7392b3-a376-4420-b48c-b36ba899304a.png)

**Comment by lyj0309** [comment]
for more details see in <https://community.fly.io/t/cant-use-command-flyctl-ssh-issue-agent/4903/5>

**Comment by mrkishi** [comment]
Duplicate of #944.

**Comment by jsierles** [comment]
Oops, indeed a duplicate. Will close here and comment on the other thread.
