### ISSUE TITLE
Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by skorotkiewicz** [superfly/flyctl#956]
```sh
flyctl deploy --remote-only
```

```
==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-frosty-bird-xxxx ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  176.6kB
[+] Building 5.5s (3/3) FINISHED                                                       
 => CACHED [internal] load remote build context                                   0.0s
 => CACHED copy /context /                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/node:14-alpine           5.4s
------
 > [internal] load metadata for docker.io/library/node:14-alpine:
------
Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to create LLB definition: no active session for ec2m11p3pil0o6657f8q8xt80: context deadline exceeded
```

* Operating system: macOS Big Sur
```
flyctl v0.0.324 darwin/amd64 Commit: dcb5132 BuildDate: 2022-04-26T13:51:01Z
```

```toml
app = "app"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

Dockerfile:

```dockerfile
FROM node:14-alpine

WORKDIR /app
COPY package.json .
RUN npm install --production

COPY . .

ENV PORT=5000
CMD [ "npm","start" ]
```

**Comment by jsierles** [comment]
Can you try `fly wg websockets enable` then try the deploy again?

**Comment by RobertoVidaSoota** [comment]
In Windows 10

`==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-dawn-sun-2933 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  726.6kB
[+] Building 1.7s (4/4) FINISHED
 => [internal] load remote build context                                                                                                                                                   0.0s
 => copy /context /                                                                                                                                                                        0.1s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                      1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                 0.0s
Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to create LLB definition: circular dependency detected on stage: base`

**Comment by RobertoVidaSoota** [comment]
In windows 10

> ==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-dawn-sun-2933 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  726.6kB
[+] Building 1.7s (4/4) FINISHED
 => [internal] load remote build context                                                                                                                                                   0.0s
 => copy /context /                                                                                                                                                                        0.1s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                      1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                 0.0s
Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to create LLB definition: circular dependency detected on stage: base

**Comment by TmLev** [comment]
> fly wg websockets enable

This just fixed my problem with
```logs
Error: failed to fetch an image or build from source: error fetching docker server info: Get "http://[...]:2375/v1.41/info": context deadline exceeded
```

Which I was battling for the past hour.

Thank you!

**Comment by redjonzaci** [comment]
@jsierles can we close this?
