### ISSUE TITLE
Statics cannot be removed once created

### ISSUE THREAD

**Issue by jsierles** [superfly/flyctl#968]
See:

https://community.fly.io/t/removing-statics-from-fly-toml-has-no-effect/5099/4
https://community.fly.io/t/cant-disable-statics-once-enabled/2892/3?u=eli

Removing statics from TOML should result in them being removed from the remote app config.

**Comment by pborzenkov** [comment]
Looks like this has already been fixed. Removing `[[statics]]` section updates machine's configuration after deploy.
