### ISSUE TITLE
Gotcha with `Update available` announcements when using `–json`

### ISSUE THREAD

**Issue by DazWilkin** [superfly/flyctl#974]
**Describe the bug**

This [Gotcha with `Update available` announcements when using `–json`](https://community.fly.io/t/gotcha-with-update-available-announcements-when-using-json/1141) continues and it's a bash script breaker :-(

I'm using `flyctl status --app=${APP} --json | jq -r .Hostname` to get the endpoint for deployed apps; I could assume `${APP}.fly.dev` but this feels *better*.

A version (`v0.0.325`) with an update prompt piped to stdout alongside the JSON:

```bash
VERS="v0.0.325"
podman run \
--interactive --tty --rm \
--volume=${PWD}/.fly:/.fly \
--volume=${PWD}/fly.toml:/fly.toml \
flyio/flyctl:${VERS} apps list --json \
| jq -r .
parse error: Invalid numeric literal at line 1, column 2
kill container: No such process
broken pipe
```
But:
```bash
VERS="v0.0.326"
... flyio/flyctl:${VERS} apps list --json \
| jq -r .
[]
```

* Operating system

Linux

* `fly version`

+ v0.0.207
+ v0.0.325
+ v0.0.326

**Comment by jphenow** [comment]
👋🏻 I could not reproduce this for a few minutes - stderr was working great. Then I noticed you're running flyctl via containers - this seems to be the issue. I tinkered with [`--attach`](https://docs.podman.io/en/latest/markdown/podman-run.1.html#attach-a-stdin-stdout-stderr) which didn't seem to get anywhere.

for this particular use-case if you drop the `--tty` on your podman/docker run it should work fine - let us know if it does?

**Comment by beninsydney** [comment]
Here are some that I have observed, using ubuntu 20.10 and flyctl 0.0.327 --

Creating a postgres db:

`$ flyctl postgres create --name xxx --organization yyy --region $REGION --vm-size shared-cpu-1x --volume-size 1 --initial-cluster-size 1 --json`

```

Creating postgres cluster xxx in organization yyy
  Username:    postgres
  Password:    asdfasdfasdfasdfasdfasdfasdfasdf
  Hostname:    xxx.internal
  Proxy Port:  5432
  PG Port: 5433
[3mSave your credentials in a secure place, you won't be able to see them again![0m

```

Attaching a postgres db:

`$ flyctl postgres attach --postgres-app xxx --json`

```

[1mConnect to postgres[0m
Any app within the yyy organization can connect to postgres using the above credentials and the hostname "xxx.internal."
For example: postgres://postgres:asdfasdfasdf@xxx.internal:5432

See the postgres docs for more information on next steps, managing postgres, connecting from outside fly:  https://fly.io/docs/reference/postgres/

Postgres cluster xxx is now attached to xxx
The following secret was added to xxx:
  DATABASE_URL=postgres://xxx:zzzz@top2.nearest.of.xxx.internal:5432/xxx
```

Creating a Redis db:

`fly launch --image flyio/redis:6.2.6 --no-deploy --name xxx --org yyy --region $REGION --json`

```
Creating app in /home/xxx/temp
Using image flyio/redis:6.2.6
Selected App Name: xxx
Created app xxx in organization yyy
Wrote config file fly.toml
Your app is ready. Deploy with `flyctl deploy`
```
