### ISSUE TITLE
During ssh, when the remote is terminated, ssh hangs without remedy

### ISSUE THREAD

**Issue by robacarp** [superfly/flyctl#988]
**Describe the bug**

If I'm trying to diagnose a failing deploy, I have a small window of time to ssh to the vm before it gets terminated. Using `fly ssh connect` opens ssh, but when the vm is terminated I need to send QUIT to the local fly process in order to recover the terminal -- and then it dumps a stacktrace into my window.

Vanilla SSH natively provides for this with an escape sequence but it doesn't work when using `fly ssh connect`. I'd like to be able to send `~.` to my terminal in order to cause the local flyctl/ssh process to exit cleanly.

* fly v0.0.330 darwin/arm64 Commit: 851f549 BuildDate: 2022-05-26T17:59:56Z

**Comment by robacarp** [comment]
Additionally, if an ssh command is slow or failing to connect, it cannot be interrupted during the "connecting to [ip::addr]" phase. Sending `^c` simply prints the control character until the spinner repaints. The process must be similarly QUIT-ted.

**Comment by jsierles** [comment]
Thanks for the report. This is a known issue we just haven't gotten around to yet.

**Comment by matttpt** [comment]
#1958 should fix the second part of this (^C unable to interrupt connection attempts).

**Comment by redjonzaci** [comment]
@jsierles can we close this?
