### ISSUE TITLE
`flyctl secrets import` does not handle `\r\n` line endings

### ISSUE THREAD

**Issue by robbyphillips** [superfly/flyctl#996]
**Describe the bug**
On windows, `flyctl secrets import` will set secrets including a trailing `\r` character.

```powershell
Get-Content .env | flyctl secrets import
```

Looks like this is where the current line split logic is: https://github.com/superfly/flyctl/blob/4d3bed4271f8a7abbdfd4b859c90e678cf06a12d/cmd/secrets.go#L134

Simplest solution is probably to just do something like this:
```golang
strings.Split(strings.ReplaceAll(secretsString, "\r\n", "\n"), "\n")
```

* Operating system
windows.

* `fly version`
v0.0.332

** Paste your `fly.toml`
n/a

** Command output: **
Secrets are successfully set...

**Comment by matttpt** [comment]
This should be fixed now; see #1824.
